-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity detection_head is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    output_r_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
    buf_conv3_4_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_conv3_4_ce0 : OUT STD_LOGIC;
    buf_conv3_4_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    buf_conv3_0_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    buf_conv3_0_ce0 : OUT STD_LOGIC;
    buf_conv3_0_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    buf_conv3_1_address0 : OUT STD_LOGIC_VECTOR (10 downto 0);
    buf_conv3_1_ce0 : OUT STD_LOGIC;
    buf_conv3_1_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    buf_conv3_2_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_conv3_2_ce0 : OUT STD_LOGIC;
    buf_conv3_2_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    buf_conv3_3_address0 : OUT STD_LOGIC_VECTOR (9 downto 0);
    buf_conv3_3_ce0 : OUT STD_LOGIC;
    buf_conv3_3_q0 : IN STD_LOGIC_VECTOR (30 downto 0) );
end;


architecture behav of detection_head is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (10 downto 0) := "00000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (10 downto 0) := "00000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (10 downto 0) := "00000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (10 downto 0) := "00000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (10 downto 0) := "00000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (10 downto 0) := "00001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (10 downto 0) := "00010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (10 downto 0) := "00100000000";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (10 downto 0) := "01000000000";
    constant ap_ST_fsm_state15 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv11_0 : STD_LOGIC_VECTOR (10 downto 0) := "00000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv11_400 : STD_LOGIC_VECTOR (10 downto 0) := "10000000000";
    constant ap_const_lv11_1 : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    constant ap_const_lv8_40 : STD_LOGIC_VECTOR (7 downto 0) := "01000000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv10_1A : STD_LOGIC_VECTOR (9 downto 0) := "0000011010";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv8_A0 : STD_LOGIC_VECTOR (7 downto 0) := "10100000";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (10 downto 0) := "00000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal w_det_0_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal w_det_0_ce0 : STD_LOGIC;
    signal w_det_0_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_det_1_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal w_det_1_ce0 : STD_LOGIC;
    signal w_det_1_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_det_2_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal w_det_2_ce0 : STD_LOGIC;
    signal w_det_2_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_det_3_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal w_det_3_ce0 : STD_LOGIC;
    signal w_det_3_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_det_4_address0 : STD_LOGIC_VECTOR (11 downto 0);
    signal w_det_4_ce0 : STD_LOGIC;
    signal w_det_4_q0 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten_reg_486 : STD_LOGIC_VECTOR (7 downto 0);
    signal ic_reg_497 : STD_LOGIC_VECTOR (5 downto 0);
    signal sum_1_reg_508 : STD_LOGIC_VECTOR (31 downto 0);
    signal ky_reg_521 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_block_state10_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state11_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state12_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state13_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state14_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exitcond_flatten_reg_1570 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten_reg_1570_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal arrayNo_reg_1511 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten_next3_fu_658_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal indvar_flatten_next3_reg_1462 : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal exitcond_flatten1_fu_664_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten1_reg_1467 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten3_fu_652_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ox_mid2_fu_708_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal ox_mid2_reg_1473 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_49_fu_716_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_49_reg_1484 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_mid2_v_fu_736_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_mid2_v_reg_1491 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal tmp_mid2_cast1_fu_743_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_mid2_cast1_reg_1496 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_mid2_cast_fu_747_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_mid2_cast_reg_1501 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_50_fu_758_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_50_reg_1506 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_724_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal newIndex2_cast1_fu_785_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal newIndex2_cast1_reg_1515 : STD_LOGIC_VECTOR (5 downto 0);
    signal newIndex2_cast_fu_789_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal newIndex2_cast_reg_1520 : STD_LOGIC_VECTOR (6 downto 0);
    signal ox_1_fu_793_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ox_1_reg_1525 : STD_LOGIC_VECTOR (3 downto 0);
    signal newIndex4_cast1_fu_822_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal newIndex4_cast1_reg_1530 : STD_LOGIC_VECTOR (5 downto 0);
    signal newIndex4_cast_fu_826_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal newIndex4_cast_reg_1535 : STD_LOGIC_VECTOR (6 downto 0);
    signal newIndex7_cast1_fu_859_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal newIndex7_cast1_reg_1540 : STD_LOGIC_VECTOR (5 downto 0);
    signal newIndex7_cast_fu_863_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal newIndex7_cast_reg_1545 : STD_LOGIC_VECTOR (6 downto 0);
    signal newIndex9_cast1_fu_896_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal newIndex9_cast1_reg_1550 : STD_LOGIC_VECTOR (5 downto 0);
    signal newIndex9_cast_fu_900_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal newIndex9_cast_reg_1555 : STD_LOGIC_VECTOR (6 downto 0);
    signal newIndex5_cast1_fu_933_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal newIndex5_cast1_reg_1560 : STD_LOGIC_VECTOR (5 downto 0);
    signal newIndex5_cast_fu_937_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal newIndex5_cast_reg_1565 : STD_LOGIC_VECTOR (6 downto 0);
    signal exitcond_flatten_fu_941_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal exitcond_flatten_reg_1570_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten_reg_1570_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_next_fu_947_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal ky_mid2_fu_965_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ky_mid2_reg_1579 : STD_LOGIC_VECTOR (2 downto 0);
    signal tmp_8_mid2_v_fu_973_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_8_mid2_v_reg_1584 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_9_fu_985_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_9_reg_1592 : STD_LOGIC_VECTOR (3 downto 0);
    signal ky_1_fu_990_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal w_det_0_load_reg_1754 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_det_1_load_reg_1759 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_det_2_load_reg_1764 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_det_3_load_reg_1769 : STD_LOGIC_VECTOR (4 downto 0);
    signal w_det_4_load_reg_1774 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_1337_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_reg_1779 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_1_fu_1350_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_1_reg_1784 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_2_fu_1363_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_2_reg_1789 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_3_fu_1376_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_3_reg_1794 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_4_fu_1389_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_4_reg_1799 : STD_LOGIC_VECTOR (31 downto 0);
    signal sum_3_4_fu_1414_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal indvar_flatten_next8_fu_1452_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state15 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state15 : signal is "none";
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state10 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal indvar_flatten3_reg_429 : STD_LOGIC_VECTOR (10 downto 0);
    signal oc_reg_440 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten7_reg_452 : STD_LOGIC_VECTOR (7 downto 0);
    signal oy_reg_464 : STD_LOGIC_VECTOR (3 downto 0);
    signal ox_reg_475 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_phi_mux_ic_phi_fu_501_p4 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_reg_pp0_iter0_input_load_0_phi_reg_532 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter1_input_load_0_phi_reg_532 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter2_input_load_0_phi_reg_532 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter3_input_load_0_phi_reg_532 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter0_input_load_1_phi_reg_547 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter1_input_load_1_phi_reg_547 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter2_input_load_1_phi_reg_547 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter3_input_load_1_phi_reg_547 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter0_input_load_2_phi_reg_562 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter1_input_load_2_phi_reg_562 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter2_input_load_2_phi_reg_562 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter3_input_load_2_phi_reg_562 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter0_input_load_3_phi_reg_577 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter1_input_load_3_phi_reg_577 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter2_input_load_3_phi_reg_577 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter3_input_load_3_phi_reg_577 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter0_input_load_4_phi_reg_592 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter1_input_load_4_phi_reg_592 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter2_input_load_4_phi_reg_592 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_phi_reg_pp0_iter3_input_load_4_phi_reg_592 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_67_cast_fu_1044_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_71_cast_fu_1069_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_75_cast_fu_1094_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_79_cast_fu_1119_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_83_cast_fu_1144_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_89_cast_fu_1180_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_93_cast_fu_1206_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_97_cast_fu_1232_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_101_cast_fu_1258_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_105_cast_fu_1284_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_111_cast_fu_1321_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_61_cast_fu_1441_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal exitcond_fu_684_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten_fu_678_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal oy_mid_fu_670_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond3_mid_fu_690_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_702_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal oy_1_fu_696_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal grp_fu_724_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal oc_1_fu_730_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_47_fu_751_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal mul1_fu_765_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul1_fu_765_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_48_fu_771_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal newIndex1_fu_781_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul8_fu_802_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul8_fu_802_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_51_fu_808_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal newIndex3_fu_818_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_26_2_fu_830_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul5_fu_839_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul5_fu_839_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_52_fu_845_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal newIndex6_fu_855_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_26_3_fu_867_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul2_fu_876_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul2_fu_876_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_53_fu_882_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal newIndex8_fu_892_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_26_4_fu_904_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_fu_913_p0 : STD_LOGIC_VECTOR (3 downto 0);
    signal mul_fu_913_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_54_fu_919_p4 : STD_LOGIC_VECTOR (2 downto 0);
    signal newIndex_fu_929_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond1_fu_959_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ic_1_fu_953_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ky_cast_fu_981_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_57_fu_1008_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl_cast_fu_1015_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_6_cast_fu_1005_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_58_fu_1019_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_59_fu_1025_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_66_cast_fu_1030_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_8_mid2_cast_fu_1002_p1 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_60_fu_1038_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_61_fu_1050_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_70_cast_fu_1055_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_62_fu_1063_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_63_fu_1075_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_74_cast_fu_1080_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_64_fu_1088_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_65_fu_1100_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_78_cast_fu_1105_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_66_fu_1113_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_67_fu_1125_p2 : STD_LOGIC_VECTOR (6 downto 0);
    signal tmp_82_cast_fu_1130_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_68_fu_1138_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_69_fu_1150_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_85_cast_fu_1157_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_70_fu_1161_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_88_cast_fu_1166_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_8_mid2_cast2_fu_999_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_71_fu_1174_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_72_fu_1187_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_92_cast_fu_1192_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_73_fu_1200_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_74_fu_1213_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_96_cast_fu_1218_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_75_fu_1226_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_76_fu_1239_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_100_cast_fu_1244_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_77_fu_1252_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_78_fu_1265_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_104_cast_fu_1270_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_79_fu_1278_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_80_fu_1291_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_107_cast_fu_1298_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_8_mid2_cast1_fu_996_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_81_fu_1302_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_110_cast_fu_1308_p3 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_82_fu_1316_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_s_fu_1337_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_1337_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_29_1_fu_1350_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_29_1_fu_1350_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_29_2_fu_1363_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_29_2_fu_1363_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_29_3_fu_1376_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_29_3_fu_1376_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp_29_4_fu_1389_p0 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_29_4_fu_1389_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal tmp3_fu_1399_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp2_fu_1403_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp1_fu_1395_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_1_fu_1408_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_7_fu_1420_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_55_fu_1423_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_60_cast_fu_1428_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_56_fu_1436_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal indvar_flatten7_op_fu_1446_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal grp_fu_724_ap_start : STD_LOGIC;
    signal grp_fu_724_ap_done : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (10 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;
    signal mul1_fu_765_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul2_fu_876_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul5_fu_839_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul8_fu_802_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal mul_fu_913_p00 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_29_1_fu_1350_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_2_fu_1363_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_3_fu_1376_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_29_4_fu_1389_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_s_fu_1337_p10 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_condition_161 : BOOLEAN;
    signal ap_condition_1077 : BOOLEAN;
    signal ap_condition_392 : BOOLEAN;

    component tinyyolo_lite_ureIfE IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        start : IN STD_LOGIC;
        done : OUT STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (3 downto 0);
        din1 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component detection_head_w_DeQ IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (11 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (4 downto 0) );
    end component;



begin
    w_det_0_U : component detection_head_w_DeQ
    generic map (
        DataWidth => 5,
        AddressRange => 2560,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w_det_0_address0,
        ce0 => w_det_0_ce0,
        q0 => w_det_0_q0);

    w_det_1_U : component detection_head_w_DeQ
    generic map (
        DataWidth => 5,
        AddressRange => 2560,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w_det_1_address0,
        ce0 => w_det_1_ce0,
        q0 => w_det_1_q0);

    w_det_2_U : component detection_head_w_DeQ
    generic map (
        DataWidth => 5,
        AddressRange => 2560,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w_det_2_address0,
        ce0 => w_det_2_ce0,
        q0 => w_det_2_q0);

    w_det_3_U : component detection_head_w_DeQ
    generic map (
        DataWidth => 5,
        AddressRange => 2560,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w_det_3_address0,
        ce0 => w_det_3_ce0,
        q0 => w_det_3_q0);

    w_det_4_U : component detection_head_w_DeQ
    generic map (
        DataWidth => 5,
        AddressRange => 2560,
        AddressWidth => 12)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w_det_4_address0,
        ce0 => w_det_4_ce0,
        q0 => w_det_4_q0);

    tinyyolo_lite_ureIfE_U74 : component tinyyolo_lite_ureIfE
    generic map (
        ID => 1,
        NUM_STAGE => 8,
        din0_WIDTH => 4,
        din1_WIDTH => 4,
        dout_WIDTH => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        start => grp_fu_724_ap_start,
        done => grp_fu_724_ap_done,
        din0 => grp_fu_724_p0,
        din1 => ap_const_lv4_5,
        ce => ap_const_logic_1,
        dout => grp_fu_724_p2);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state10) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state10)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state10);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ap_phi_reg_pp0_iter3_input_load_0_phi_reg_532_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_const_boolean_1 = ap_condition_161)) then 
                    ap_phi_reg_pp0_iter3_input_load_0_phi_reg_532 <= buf_conv3_4_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_3) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_0_phi_reg_532 <= buf_conv3_3_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_2) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_0_phi_reg_532 <= buf_conv3_2_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_1) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_0_phi_reg_532 <= buf_conv3_1_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_0) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_0_phi_reg_532 <= buf_conv3_0_q0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_input_load_0_phi_reg_532 <= ap_phi_reg_pp0_iter2_input_load_0_phi_reg_532;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_input_load_1_phi_reg_547_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_const_boolean_1 = ap_condition_161)) then 
                    ap_phi_reg_pp0_iter3_input_load_1_phi_reg_547 <= buf_conv3_0_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_3) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_1_phi_reg_547 <= buf_conv3_4_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_2) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_1_phi_reg_547 <= buf_conv3_3_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_1) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_1_phi_reg_547 <= buf_conv3_2_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_0) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_1_phi_reg_547 <= buf_conv3_1_q0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_input_load_1_phi_reg_547 <= ap_phi_reg_pp0_iter2_input_load_1_phi_reg_547;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_input_load_2_phi_reg_562_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_const_boolean_1 = ap_condition_161)) then 
                    ap_phi_reg_pp0_iter3_input_load_2_phi_reg_562 <= buf_conv3_1_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_3) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_2_phi_reg_562 <= buf_conv3_0_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_2) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_2_phi_reg_562 <= buf_conv3_4_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_1) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_2_phi_reg_562 <= buf_conv3_3_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_0) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_2_phi_reg_562 <= buf_conv3_2_q0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_input_load_2_phi_reg_562 <= ap_phi_reg_pp0_iter2_input_load_2_phi_reg_562;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_input_load_3_phi_reg_577_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_const_boolean_1 = ap_condition_161)) then 
                    ap_phi_reg_pp0_iter3_input_load_3_phi_reg_577 <= buf_conv3_2_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_3) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_3_phi_reg_577 <= buf_conv3_1_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_2) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_3_phi_reg_577 <= buf_conv3_0_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_1) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_3_phi_reg_577 <= buf_conv3_4_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_0) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_3_phi_reg_577 <= buf_conv3_3_q0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_input_load_3_phi_reg_577 <= ap_phi_reg_pp0_iter2_input_load_3_phi_reg_577;
                end if;
            end if; 
        end if;
    end process;

    ap_phi_reg_pp0_iter3_input_load_4_phi_reg_592_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                if ((ap_const_boolean_1 = ap_condition_161)) then 
                    ap_phi_reg_pp0_iter3_input_load_4_phi_reg_592 <= buf_conv3_3_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_3) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_4_phi_reg_592 <= buf_conv3_2_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_2) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_4_phi_reg_592 <= buf_conv3_1_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_1) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_4_phi_reg_592 <= buf_conv3_0_q0;
                elsif (((arrayNo_reg_1511 = ap_const_lv4_0) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0))) then 
                    ap_phi_reg_pp0_iter3_input_load_4_phi_reg_592 <= buf_conv3_4_q0;
                elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                    ap_phi_reg_pp0_iter3_input_load_4_phi_reg_592 <= ap_phi_reg_pp0_iter2_input_load_4_phi_reg_592;
                end if;
            end if; 
        end if;
    end process;

    ic_reg_497_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ic_reg_497 <= tmp_8_mid2_v_reg_1584;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                ic_reg_497 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    indvar_flatten3_reg_429_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                indvar_flatten3_reg_429 <= indvar_flatten_next3_reg_1462;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten3_reg_429 <= ap_const_lv11_0;
            end if; 
        end if;
    end process;

    indvar_flatten7_reg_452_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                indvar_flatten7_reg_452 <= indvar_flatten_next8_fu_1452_p3;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                indvar_flatten7_reg_452 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_486_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_fu_941_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                indvar_flatten_reg_486 <= indvar_flatten_next_fu_947_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                indvar_flatten_reg_486 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    ky_reg_521_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_fu_941_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                ky_reg_521 <= ky_1_fu_990_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                ky_reg_521 <= ap_const_lv3_0;
            end if; 
        end if;
    end process;

    oc_reg_440_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                oc_reg_440 <= tmp_mid2_v_reg_1491;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                oc_reg_440 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    ox_reg_475_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                ox_reg_475 <= ox_1_reg_1525;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                ox_reg_475 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    oy_reg_464_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
                oy_reg_464 <= tmp_49_reg_1484;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                oy_reg_464 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    sum_1_reg_508_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (exitcond_flatten_reg_1570_pp0_iter3_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
                sum_1_reg_508 <= sum_3_4_fu_1414_p2;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state9)) then 
                sum_1_reg_508 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter1_input_load_0_phi_reg_532 <= ap_phi_reg_pp0_iter0_input_load_0_phi_reg_532;
                ap_phi_reg_pp0_iter1_input_load_1_phi_reg_547 <= ap_phi_reg_pp0_iter0_input_load_1_phi_reg_547;
                ap_phi_reg_pp0_iter1_input_load_2_phi_reg_562 <= ap_phi_reg_pp0_iter0_input_load_2_phi_reg_562;
                ap_phi_reg_pp0_iter1_input_load_3_phi_reg_577 <= ap_phi_reg_pp0_iter0_input_load_3_phi_reg_577;
                ap_phi_reg_pp0_iter1_input_load_4_phi_reg_592 <= ap_phi_reg_pp0_iter0_input_load_4_phi_reg_592;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ap_phi_reg_pp0_iter2_input_load_0_phi_reg_532 <= ap_phi_reg_pp0_iter1_input_load_0_phi_reg_532;
                ap_phi_reg_pp0_iter2_input_load_1_phi_reg_547 <= ap_phi_reg_pp0_iter1_input_load_1_phi_reg_547;
                ap_phi_reg_pp0_iter2_input_load_2_phi_reg_562 <= ap_phi_reg_pp0_iter1_input_load_2_phi_reg_562;
                ap_phi_reg_pp0_iter2_input_load_3_phi_reg_577 <= ap_phi_reg_pp0_iter1_input_load_3_phi_reg_577;
                ap_phi_reg_pp0_iter2_input_load_4_phi_reg_592 <= ap_phi_reg_pp0_iter1_input_load_4_phi_reg_592;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                arrayNo_reg_1511 <= grp_fu_724_p2;
                    newIndex2_cast1_reg_1515(3 downto 0) <= newIndex2_cast1_fu_785_p1(3 downto 0);
                    newIndex2_cast_reg_1520(3 downto 0) <= newIndex2_cast_fu_789_p1(3 downto 0);
                    newIndex4_cast1_reg_1530(3 downto 0) <= newIndex4_cast1_fu_822_p1(3 downto 0);
                    newIndex4_cast_reg_1535(3 downto 0) <= newIndex4_cast_fu_826_p1(3 downto 0);
                    newIndex5_cast1_reg_1560(3 downto 0) <= newIndex5_cast1_fu_933_p1(3 downto 0);
                    newIndex5_cast_reg_1565(3 downto 0) <= newIndex5_cast_fu_937_p1(3 downto 0);
                    newIndex7_cast1_reg_1540(3 downto 0) <= newIndex7_cast1_fu_859_p1(3 downto 0);
                    newIndex7_cast_reg_1545(3 downto 0) <= newIndex7_cast_fu_863_p1(3 downto 0);
                    newIndex9_cast1_reg_1550(3 downto 0) <= newIndex9_cast1_fu_896_p1(3 downto 0);
                    newIndex9_cast_reg_1555(3 downto 0) <= newIndex9_cast_fu_900_p1(3 downto 0);
                ox_1_reg_1525 <= ox_1_fu_793_p2;
                    tmp_50_reg_1506(6 downto 3) <= tmp_50_fu_758_p1(6 downto 3);
                    tmp_mid2_cast1_reg_1496(4 downto 0) <= tmp_mid2_cast1_fu_743_p1(4 downto 0);
                    tmp_mid2_cast_reg_1501(4 downto 0) <= tmp_mid2_cast_fu_747_p1(4 downto 0);
                tmp_mid2_v_reg_1491 <= tmp_mid2_v_fu_736_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_flatten3_fu_652_p2 = ap_const_lv1_0))) then
                exitcond_flatten1_reg_1467 <= exitcond_flatten1_fu_664_p2;
                ox_mid2_reg_1473 <= ox_mid2_fu_708_p3;
                tmp_49_reg_1484 <= tmp_49_fu_716_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                exitcond_flatten_reg_1570 <= exitcond_flatten_fu_941_p2;
                exitcond_flatten_reg_1570_pp0_iter1_reg <= exitcond_flatten_reg_1570;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                exitcond_flatten_reg_1570_pp0_iter2_reg <= exitcond_flatten_reg_1570_pp0_iter1_reg;
                exitcond_flatten_reg_1570_pp0_iter3_reg <= exitcond_flatten_reg_1570_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                indvar_flatten_next3_reg_1462 <= indvar_flatten_next3_fu_658_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_fu_941_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                ky_mid2_reg_1579 <= ky_mid2_fu_965_p3;
                tmp_9_reg_1592 <= tmp_9_fu_985_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_reg_1570_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_29_1_reg_1784 <= tmp_29_1_fu_1350_p2;
                tmp_29_2_reg_1789 <= tmp_29_2_fu_1363_p2;
                tmp_29_3_reg_1794 <= tmp_29_3_fu_1376_p2;
                tmp_29_4_reg_1799 <= tmp_29_4_fu_1389_p2;
                tmp_s_reg_1779 <= tmp_s_fu_1337_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_fu_941_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                tmp_8_mid2_v_reg_1584 <= tmp_8_mid2_v_fu_973_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                w_det_0_load_reg_1754 <= w_det_0_q0;
                w_det_1_load_reg_1759 <= w_det_1_q0;
                w_det_2_load_reg_1764 <= w_det_2_q0;
                w_det_3_load_reg_1769 <= w_det_3_q0;
                w_det_4_load_reg_1774 <= w_det_4_q0;
            end if;
        end if;
    end process;
    tmp_mid2_cast1_reg_1496(12 downto 5) <= "00000000";
    tmp_mid2_cast_reg_1501(11 downto 5) <= "0000000";
    tmp_50_reg_1506(2 downto 0) <= "000";
    tmp_50_reg_1506(7) <= '0';
    newIndex2_cast1_reg_1515(5 downto 4) <= "00";
    newIndex2_cast_reg_1520(6 downto 4) <= "000";
    newIndex4_cast1_reg_1530(5 downto 4) <= "00";
    newIndex4_cast_reg_1535(6 downto 4) <= "000";
    newIndex7_cast1_reg_1540(5 downto 4) <= "00";
    newIndex7_cast_reg_1545(6 downto 4) <= "000";
    newIndex9_cast1_reg_1550(5 downto 4) <= "00";
    newIndex9_cast_reg_1555(6 downto 4) <= "000";
    newIndex5_cast1_reg_1560(5 downto 4) <= "00";
    newIndex5_cast_reg_1565(6 downto 4) <= "000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, exitcond_flatten3_fu_652_p2, exitcond_flatten_fu_941_p2, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter4, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_flatten3_fu_652_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state8;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (exitcond_flatten_fu_941_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) and not(((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (exitcond_flatten_fu_941_p2 = ap_const_lv1_1) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state15;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state15 => 
                ap_NS_fsm <= ap_ST_fsm_state2;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(9);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state15 <= ap_CS_fsm(10);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state10_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state11_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state12_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state13_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state14_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_1077_assign_proc : process(arrayNo_reg_1511)
    begin
                ap_condition_1077 <= (not((arrayNo_reg_1511 = ap_const_lv4_0)) and not((arrayNo_reg_1511 = ap_const_lv4_1)) and not((arrayNo_reg_1511 = ap_const_lv4_2)) and not((arrayNo_reg_1511 = ap_const_lv4_3)));
    end process;


    ap_condition_161_assign_proc : process(exitcond_flatten_reg_1570_pp0_iter1_reg, arrayNo_reg_1511)
    begin
                ap_condition_161 <= (not((arrayNo_reg_1511 = ap_const_lv4_0)) and not((arrayNo_reg_1511 = ap_const_lv4_1)) and not((arrayNo_reg_1511 = ap_const_lv4_2)) and not((arrayNo_reg_1511 = ap_const_lv4_3)) and (exitcond_flatten_reg_1570_pp0_iter1_reg = ap_const_lv1_0));
    end process;


    ap_condition_392_assign_proc : process(exitcond_flatten_reg_1570, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
                ap_condition_392 <= ((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_reg_1570 = ap_const_lv1_0));
    end process;


    ap_condition_pp0_exit_iter0_state10_assign_proc : process(exitcond_flatten_fu_941_p2)
    begin
        if ((exitcond_flatten_fu_941_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state10 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state10 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, exitcond_flatten3_fu_652_p2)
    begin
        if ((((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)) or ((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_flatten3_fu_652_p2 = ap_const_lv1_1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3)
    begin
        if (((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_ic_phi_fu_501_p4_assign_proc : process(ic_reg_497, exitcond_flatten_reg_1570, ap_CS_fsm_pp0_stage0, tmp_8_mid2_v_reg_1584, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_reg_1570 = ap_const_lv1_0))) then 
            ap_phi_mux_ic_phi_fu_501_p4 <= tmp_8_mid2_v_reg_1584;
        else 
            ap_phi_mux_ic_phi_fu_501_p4 <= ic_reg_497;
        end if; 
    end process;

    ap_phi_reg_pp0_iter0_input_load_0_phi_reg_532 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_input_load_1_phi_reg_547 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_input_load_2_phi_reg_562 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_input_load_3_phi_reg_577 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
    ap_phi_reg_pp0_iter0_input_load_4_phi_reg_592 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";

    ap_ready_assign_proc : process(ap_CS_fsm_state2, exitcond_flatten3_fu_652_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_flatten3_fu_652_p2 = ap_const_lv1_1))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    buf_conv3_0_address0_assign_proc : process(arrayNo_reg_1511, tmp_67_cast_fu_1044_p1, tmp_71_cast_fu_1069_p1, tmp_75_cast_fu_1094_p1, tmp_79_cast_fu_1119_p1, tmp_83_cast_fu_1144_p1, ap_condition_1077, ap_condition_392)
    begin
        if ((ap_const_boolean_1 = ap_condition_392)) then
            if ((arrayNo_reg_1511 = ap_const_lv4_1)) then 
                buf_conv3_0_address0 <= tmp_83_cast_fu_1144_p1(11 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_2)) then 
                buf_conv3_0_address0 <= tmp_79_cast_fu_1119_p1(11 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_3)) then 
                buf_conv3_0_address0 <= tmp_75_cast_fu_1094_p1(11 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_1077)) then 
                buf_conv3_0_address0 <= tmp_71_cast_fu_1069_p1(11 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_0)) then 
                buf_conv3_0_address0 <= tmp_67_cast_fu_1044_p1(11 - 1 downto 0);
            else 
                buf_conv3_0_address0 <= "XXXXXXXXXXX";
            end if;
        else 
            buf_conv3_0_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    buf_conv3_0_ce0_assign_proc : process(ap_block_pp0_stage0_11001, exitcond_flatten_reg_1570, arrayNo_reg_1511, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
        if (((not((arrayNo_reg_1511 = ap_const_lv4_0)) and not((arrayNo_reg_1511 = ap_const_lv4_1)) and not((arrayNo_reg_1511 = ap_const_lv4_2)) and not((arrayNo_reg_1511 = ap_const_lv4_3)) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_0) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_1) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_2) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_3) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_conv3_0_ce0 <= ap_const_logic_1;
        else 
            buf_conv3_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_conv3_1_address0_assign_proc : process(arrayNo_reg_1511, tmp_67_cast_fu_1044_p1, tmp_71_cast_fu_1069_p1, tmp_75_cast_fu_1094_p1, tmp_79_cast_fu_1119_p1, tmp_83_cast_fu_1144_p1, ap_condition_1077, ap_condition_392)
    begin
        if ((ap_const_boolean_1 = ap_condition_392)) then
            if ((arrayNo_reg_1511 = ap_const_lv4_2)) then 
                buf_conv3_1_address0 <= tmp_83_cast_fu_1144_p1(11 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_3)) then 
                buf_conv3_1_address0 <= tmp_79_cast_fu_1119_p1(11 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_1077)) then 
                buf_conv3_1_address0 <= tmp_75_cast_fu_1094_p1(11 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_0)) then 
                buf_conv3_1_address0 <= tmp_71_cast_fu_1069_p1(11 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_1)) then 
                buf_conv3_1_address0 <= tmp_67_cast_fu_1044_p1(11 - 1 downto 0);
            else 
                buf_conv3_1_address0 <= "XXXXXXXXXXX";
            end if;
        else 
            buf_conv3_1_address0 <= "XXXXXXXXXXX";
        end if; 
    end process;


    buf_conv3_1_ce0_assign_proc : process(ap_block_pp0_stage0_11001, exitcond_flatten_reg_1570, arrayNo_reg_1511, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
        if (((not((arrayNo_reg_1511 = ap_const_lv4_0)) and not((arrayNo_reg_1511 = ap_const_lv4_1)) and not((arrayNo_reg_1511 = ap_const_lv4_2)) and not((arrayNo_reg_1511 = ap_const_lv4_3)) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_0) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_1) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_2) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_3) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_conv3_1_ce0 <= ap_const_logic_1;
        else 
            buf_conv3_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_conv3_2_address0_assign_proc : process(arrayNo_reg_1511, tmp_89_cast_fu_1180_p1, tmp_93_cast_fu_1206_p1, tmp_97_cast_fu_1232_p1, tmp_101_cast_fu_1258_p1, tmp_105_cast_fu_1284_p1, ap_condition_1077, ap_condition_392)
    begin
        if ((ap_const_boolean_1 = ap_condition_392)) then
            if ((arrayNo_reg_1511 = ap_const_lv4_3)) then 
                buf_conv3_2_address0 <= tmp_105_cast_fu_1284_p1(10 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_1077)) then 
                buf_conv3_2_address0 <= tmp_101_cast_fu_1258_p1(10 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_0)) then 
                buf_conv3_2_address0 <= tmp_97_cast_fu_1232_p1(10 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_1)) then 
                buf_conv3_2_address0 <= tmp_93_cast_fu_1206_p1(10 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_2)) then 
                buf_conv3_2_address0 <= tmp_89_cast_fu_1180_p1(10 - 1 downto 0);
            else 
                buf_conv3_2_address0 <= "XXXXXXXXXX";
            end if;
        else 
            buf_conv3_2_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    buf_conv3_2_ce0_assign_proc : process(ap_block_pp0_stage0_11001, exitcond_flatten_reg_1570, arrayNo_reg_1511, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
        if (((not((arrayNo_reg_1511 = ap_const_lv4_0)) and not((arrayNo_reg_1511 = ap_const_lv4_1)) and not((arrayNo_reg_1511 = ap_const_lv4_2)) and not((arrayNo_reg_1511 = ap_const_lv4_3)) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_0) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_1) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_2) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_3) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_conv3_2_ce0 <= ap_const_logic_1;
        else 
            buf_conv3_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_conv3_3_address0_assign_proc : process(arrayNo_reg_1511, tmp_89_cast_fu_1180_p1, tmp_93_cast_fu_1206_p1, tmp_97_cast_fu_1232_p1, tmp_101_cast_fu_1258_p1, tmp_105_cast_fu_1284_p1, ap_condition_1077, ap_condition_392)
    begin
        if ((ap_const_boolean_1 = ap_condition_392)) then
            if ((ap_const_boolean_1 = ap_condition_1077)) then 
                buf_conv3_3_address0 <= tmp_105_cast_fu_1284_p1(10 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_0)) then 
                buf_conv3_3_address0 <= tmp_101_cast_fu_1258_p1(10 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_1)) then 
                buf_conv3_3_address0 <= tmp_97_cast_fu_1232_p1(10 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_2)) then 
                buf_conv3_3_address0 <= tmp_93_cast_fu_1206_p1(10 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_3)) then 
                buf_conv3_3_address0 <= tmp_89_cast_fu_1180_p1(10 - 1 downto 0);
            else 
                buf_conv3_3_address0 <= "XXXXXXXXXX";
            end if;
        else 
            buf_conv3_3_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    buf_conv3_3_ce0_assign_proc : process(ap_block_pp0_stage0_11001, exitcond_flatten_reg_1570, arrayNo_reg_1511, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
        if (((not((arrayNo_reg_1511 = ap_const_lv4_0)) and not((arrayNo_reg_1511 = ap_const_lv4_1)) and not((arrayNo_reg_1511 = ap_const_lv4_2)) and not((arrayNo_reg_1511 = ap_const_lv4_3)) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_0) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_1) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_2) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_3) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_conv3_3_ce0 <= ap_const_logic_1;
        else 
            buf_conv3_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_conv3_4_address0_assign_proc : process(arrayNo_reg_1511, tmp_89_cast_fu_1180_p1, tmp_93_cast_fu_1206_p1, tmp_97_cast_fu_1232_p1, tmp_101_cast_fu_1258_p1, tmp_105_cast_fu_1284_p1, ap_condition_1077, ap_condition_392)
    begin
        if ((ap_const_boolean_1 = ap_condition_392)) then
            if ((arrayNo_reg_1511 = ap_const_lv4_0)) then 
                buf_conv3_4_address0 <= tmp_105_cast_fu_1284_p1(10 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_1)) then 
                buf_conv3_4_address0 <= tmp_101_cast_fu_1258_p1(10 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_2)) then 
                buf_conv3_4_address0 <= tmp_97_cast_fu_1232_p1(10 - 1 downto 0);
            elsif ((arrayNo_reg_1511 = ap_const_lv4_3)) then 
                buf_conv3_4_address0 <= tmp_93_cast_fu_1206_p1(10 - 1 downto 0);
            elsif ((ap_const_boolean_1 = ap_condition_1077)) then 
                buf_conv3_4_address0 <= tmp_89_cast_fu_1180_p1(10 - 1 downto 0);
            else 
                buf_conv3_4_address0 <= "XXXXXXXXXX";
            end if;
        else 
            buf_conv3_4_address0 <= "XXXXXXXXXX";
        end if; 
    end process;


    buf_conv3_4_ce0_assign_proc : process(ap_block_pp0_stage0_11001, exitcond_flatten_reg_1570, arrayNo_reg_1511, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
        if (((not((arrayNo_reg_1511 = ap_const_lv4_0)) and not((arrayNo_reg_1511 = ap_const_lv4_1)) and not((arrayNo_reg_1511 = ap_const_lv4_2)) and not((arrayNo_reg_1511 = ap_const_lv4_3)) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_0) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_1) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_2) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (arrayNo_reg_1511 = ap_const_lv4_3) and (exitcond_flatten_reg_1570 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001)))) then 
            buf_conv3_4_ce0 <= ap_const_logic_1;
        else 
            buf_conv3_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    exitcond1_fu_959_p2 <= "1" when (ky_reg_521 = ap_const_lv3_5) else "0";
    exitcond3_mid_fu_690_p2 <= (not_exitcond_flatten_fu_678_p2 and exitcond_fu_684_p2);
    exitcond_flatten1_fu_664_p2 <= "1" when (indvar_flatten7_reg_452 = ap_const_lv8_40) else "0";
    exitcond_flatten3_fu_652_p2 <= "1" when (indvar_flatten3_reg_429 = ap_const_lv11_400) else "0";
    exitcond_flatten_fu_941_p2 <= "1" when (indvar_flatten_reg_486 = ap_const_lv8_A0) else "0";
    exitcond_fu_684_p2 <= "1" when (ox_reg_475 = ap_const_lv4_8) else "0";

    grp_fu_724_ap_start_assign_proc : process(ap_CS_fsm_state2, exitcond_flatten3_fu_652_p2)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state2) and (exitcond_flatten3_fu_652_p2 = ap_const_lv1_0))) then 
            grp_fu_724_ap_start <= ap_const_logic_1;
        else 
            grp_fu_724_ap_start <= ap_const_logic_0;
        end if; 
    end process;

    grp_fu_724_p0 <= 
        ap_const_lv4_0 when (tmp_fu_702_p2(0) = '1') else 
        ox_reg_475;
    ic_1_fu_953_p2 <= std_logic_vector(unsigned(ap_phi_mux_ic_phi_fu_501_p4) + unsigned(ap_const_lv6_1));
    indvar_flatten7_op_fu_1446_p2 <= std_logic_vector(unsigned(indvar_flatten7_reg_452) + unsigned(ap_const_lv8_1));
    indvar_flatten_next3_fu_658_p2 <= std_logic_vector(unsigned(indvar_flatten3_reg_429) + unsigned(ap_const_lv11_1));
    indvar_flatten_next8_fu_1452_p3 <= 
        ap_const_lv8_1 when (exitcond_flatten1_reg_1467(0) = '1') else 
        indvar_flatten7_op_fu_1446_p2;
    indvar_flatten_next_fu_947_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_486) + unsigned(ap_const_lv8_1));
    ky_1_fu_990_p2 <= std_logic_vector(unsigned(ky_mid2_fu_965_p3) + unsigned(ap_const_lv3_1));
    ky_cast_fu_981_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ky_mid2_fu_965_p3),4));
    ky_mid2_fu_965_p3 <= 
        ap_const_lv3_0 when (exitcond1_fu_959_p2(0) = '1') else 
        ky_reg_521;
    mul1_fu_765_p0 <= mul1_fu_765_p00(4 - 1 downto 0);
    mul1_fu_765_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ox_mid2_reg_1473),10));
    mul1_fu_765_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul1_fu_765_p0) * unsigned(ap_const_lv10_1A), 10));
    mul2_fu_876_p0 <= mul2_fu_876_p00(4 - 1 downto 0);
    mul2_fu_876_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_26_3_fu_867_p2),10));
    mul2_fu_876_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul2_fu_876_p0) * unsigned(ap_const_lv10_1A), 10));
    mul5_fu_839_p0 <= mul5_fu_839_p00(4 - 1 downto 0);
    mul5_fu_839_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_26_2_fu_830_p2),10));
    mul5_fu_839_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul5_fu_839_p0) * unsigned(ap_const_lv10_1A), 10));
    mul8_fu_802_p0 <= mul8_fu_802_p00(4 - 1 downto 0);
    mul8_fu_802_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ox_1_fu_793_p2),10));
    mul8_fu_802_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul8_fu_802_p0) * unsigned(ap_const_lv10_1A), 10));
    mul_fu_913_p0 <= mul_fu_913_p00(4 - 1 downto 0);
    mul_fu_913_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_26_4_fu_904_p2),10));
    mul_fu_913_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(mul_fu_913_p0) * unsigned(ap_const_lv10_1A), 10));
        newIndex1_fu_781_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_48_fu_771_p4),4));

    newIndex2_cast1_fu_785_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(newIndex1_fu_781_p1),6));
    newIndex2_cast_fu_789_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(newIndex1_fu_781_p1),7));
        newIndex3_fu_818_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_51_fu_808_p4),4));

    newIndex4_cast1_fu_822_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(newIndex3_fu_818_p1),6));
    newIndex4_cast_fu_826_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(newIndex3_fu_818_p1),7));
    newIndex5_cast1_fu_933_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(newIndex_fu_929_p1),6));
    newIndex5_cast_fu_937_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(newIndex_fu_929_p1),7));
        newIndex6_fu_855_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_52_fu_845_p4),4));

    newIndex7_cast1_fu_859_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(newIndex6_fu_855_p1),6));
    newIndex7_cast_fu_863_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(newIndex6_fu_855_p1),7));
        newIndex8_fu_892_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_53_fu_882_p4),4));

    newIndex9_cast1_fu_896_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(newIndex8_fu_892_p1),6));
    newIndex9_cast_fu_900_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(newIndex8_fu_892_p1),7));
        newIndex_fu_929_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_54_fu_919_p4),4));

    not_exitcond_flatten_fu_678_p2 <= (exitcond_flatten1_fu_664_p2 xor ap_const_lv1_1);
    oc_1_fu_730_p2 <= std_logic_vector(unsigned(oc_reg_440) + unsigned(ap_const_lv5_1));
    output_r_address0 <= tmp_61_cast_fu_1441_p1(10 - 1 downto 0);

    output_r_ce0_assign_proc : process(ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            output_r_ce0 <= ap_const_logic_1;
        else 
            output_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_r_d0 <= sum_1_reg_508;

    output_r_we0_assign_proc : process(ap_CS_fsm_state15)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state15)) then 
            output_r_we0 <= ap_const_logic_1;
        else 
            output_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    ox_1_fu_793_p2 <= std_logic_vector(unsigned(ox_mid2_reg_1473) + unsigned(ap_const_lv4_1));
    ox_mid2_fu_708_p3 <= 
        ap_const_lv4_0 when (tmp_fu_702_p2(0) = '1') else 
        ox_reg_475;
    oy_1_fu_696_p2 <= std_logic_vector(unsigned(oy_mid_fu_670_p3) + unsigned(ap_const_lv4_1));
    oy_mid_fu_670_p3 <= 
        ap_const_lv4_0 when (exitcond_flatten1_fu_664_p2(0) = '1') else 
        oy_reg_464;
    p_shl_cast_fu_1015_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_57_fu_1008_p3),7));
    sum_3_4_fu_1414_p2 <= std_logic_vector(unsigned(sum_1_reg_508) + unsigned(tmp_1_fu_1408_p2));
    tmp1_fu_1395_p2 <= std_logic_vector(unsigned(tmp_s_reg_1779) + unsigned(tmp_29_1_reg_1784));
    tmp2_fu_1403_p2 <= std_logic_vector(unsigned(tmp3_fu_1399_p2) + unsigned(tmp_29_2_reg_1789));
    tmp3_fu_1399_p2 <= std_logic_vector(unsigned(tmp_29_3_reg_1794) + unsigned(tmp_29_4_reg_1799));
    tmp_100_cast_fu_1244_p3 <= (tmp_76_fu_1239_p2 & ap_const_lv5_0);
    tmp_101_cast_fu_1258_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_77_fu_1252_p2),64));
    tmp_104_cast_fu_1270_p3 <= (tmp_78_fu_1265_p2 & ap_const_lv5_0);
    tmp_105_cast_fu_1284_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_79_fu_1278_p2),64));
    tmp_107_cast_fu_1298_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_80_fu_1291_p3),9));
    tmp_110_cast_fu_1308_p3 <= (tmp_81_fu_1302_p2 & ap_const_lv4_0);
    tmp_111_cast_fu_1321_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_82_fu_1316_p2),64));
    tmp_1_fu_1408_p2 <= std_logic_vector(unsigned(tmp2_fu_1403_p2) + unsigned(tmp1_fu_1395_p2));
    tmp_26_2_fu_830_p2 <= std_logic_vector(unsigned(ox_mid2_reg_1473) + unsigned(ap_const_lv4_2));
    tmp_26_3_fu_867_p2 <= std_logic_vector(unsigned(ox_mid2_reg_1473) + unsigned(ap_const_lv4_3));
    tmp_26_4_fu_904_p2 <= std_logic_vector(unsigned(ox_mid2_reg_1473) + unsigned(ap_const_lv4_4));
    tmp_29_1_fu_1350_p0 <= w_det_1_load_reg_1759;
    tmp_29_1_fu_1350_p1 <= tmp_29_1_fu_1350_p10(31 - 1 downto 0);
    tmp_29_1_fu_1350_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter3_input_load_1_phi_reg_547),32));
    tmp_29_1_fu_1350_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(tmp_29_1_fu_1350_p0) * signed('0' &tmp_29_1_fu_1350_p1))), 32));
    tmp_29_2_fu_1363_p0 <= w_det_2_load_reg_1764;
    tmp_29_2_fu_1363_p1 <= tmp_29_2_fu_1363_p10(31 - 1 downto 0);
    tmp_29_2_fu_1363_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter3_input_load_2_phi_reg_562),32));
    tmp_29_2_fu_1363_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(tmp_29_2_fu_1363_p0) * signed('0' &tmp_29_2_fu_1363_p1))), 32));
    tmp_29_3_fu_1376_p0 <= w_det_3_load_reg_1769;
    tmp_29_3_fu_1376_p1 <= tmp_29_3_fu_1376_p10(31 - 1 downto 0);
    tmp_29_3_fu_1376_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter3_input_load_3_phi_reg_577),32));
    tmp_29_3_fu_1376_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(tmp_29_3_fu_1376_p0) * signed('0' &tmp_29_3_fu_1376_p1))), 32));
    tmp_29_4_fu_1389_p0 <= w_det_4_load_reg_1774;
    tmp_29_4_fu_1389_p1 <= tmp_29_4_fu_1389_p10(31 - 1 downto 0);
    tmp_29_4_fu_1389_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter3_input_load_4_phi_reg_592),32));
    tmp_29_4_fu_1389_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(tmp_29_4_fu_1389_p0) * signed('0' &tmp_29_4_fu_1389_p1))), 32));
    tmp_47_fu_751_p3 <= (tmp_49_reg_1484 & ap_const_lv3_0);
    tmp_48_fu_771_p4 <= mul1_fu_765_p2(9 downto 7);
    tmp_49_fu_716_p3 <= 
        oy_1_fu_696_p2 when (exitcond3_mid_fu_690_p2(0) = '1') else 
        oy_mid_fu_670_p3;
    tmp_50_fu_758_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_47_fu_751_p3),8));
    tmp_51_fu_808_p4 <= mul8_fu_802_p2(9 downto 7);
    tmp_52_fu_845_p4 <= mul5_fu_839_p2(9 downto 7);
    tmp_53_fu_882_p4 <= mul2_fu_876_p2(9 downto 7);
    tmp_54_fu_919_p4 <= mul_fu_913_p2(9 downto 7);
    tmp_55_fu_1423_p2 <= std_logic_vector(unsigned(tmp_50_reg_1506) + unsigned(tmp_7_fu_1420_p1));
    tmp_56_fu_1436_p2 <= std_logic_vector(unsigned(tmp_60_cast_fu_1428_p3) + unsigned(tmp_mid2_cast_reg_1501));
    tmp_57_fu_1008_p3 <= (tmp_9_reg_1592 & ap_const_lv2_0);
    tmp_58_fu_1019_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_1015_p1) - unsigned(tmp_6_cast_fu_1005_p1));
    tmp_59_fu_1025_p2 <= std_logic_vector(unsigned(tmp_58_fu_1019_p2) + unsigned(newIndex2_cast_reg_1520));
    tmp_60_cast_fu_1428_p3 <= (tmp_55_fu_1423_p2 & ap_const_lv4_0);
    tmp_60_fu_1038_p2 <= std_logic_vector(unsigned(tmp_66_cast_fu_1030_p3) + unsigned(tmp_8_mid2_cast_fu_1002_p1));
    tmp_61_cast_fu_1441_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_56_fu_1436_p2),64));
    tmp_61_fu_1050_p2 <= std_logic_vector(unsigned(tmp_58_fu_1019_p2) + unsigned(newIndex4_cast_reg_1535));
    tmp_62_fu_1063_p2 <= std_logic_vector(unsigned(tmp_70_cast_fu_1055_p3) + unsigned(tmp_8_mid2_cast_fu_1002_p1));
    tmp_63_fu_1075_p2 <= std_logic_vector(unsigned(tmp_58_fu_1019_p2) + unsigned(newIndex7_cast_reg_1545));
    tmp_64_fu_1088_p2 <= std_logic_vector(unsigned(tmp_74_cast_fu_1080_p3) + unsigned(tmp_8_mid2_cast_fu_1002_p1));
    tmp_65_fu_1100_p2 <= std_logic_vector(unsigned(tmp_58_fu_1019_p2) + unsigned(newIndex9_cast_reg_1555));
    tmp_66_cast_fu_1030_p3 <= (tmp_59_fu_1025_p2 & ap_const_lv5_0);
    tmp_66_fu_1113_p2 <= std_logic_vector(unsigned(tmp_78_cast_fu_1105_p3) + unsigned(tmp_8_mid2_cast_fu_1002_p1));
    tmp_67_cast_fu_1044_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_60_fu_1038_p2),64));
    tmp_67_fu_1125_p2 <= std_logic_vector(unsigned(tmp_58_fu_1019_p2) + unsigned(newIndex5_cast_reg_1565));
    tmp_68_fu_1138_p2 <= std_logic_vector(unsigned(tmp_82_cast_fu_1130_p3) + unsigned(tmp_8_mid2_cast_fu_1002_p1));
    tmp_69_fu_1150_p3 <= (tmp_9_reg_1592 & ap_const_lv1_0);
    tmp_6_cast_fu_1005_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_9_reg_1592),7));
    tmp_70_cast_fu_1055_p3 <= (tmp_61_fu_1050_p2 & ap_const_lv5_0);
    tmp_70_fu_1161_p2 <= std_logic_vector(unsigned(tmp_85_cast_fu_1157_p1) + unsigned(newIndex2_cast1_reg_1515));
    tmp_71_cast_fu_1069_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_62_fu_1063_p2),64));
    tmp_71_fu_1174_p2 <= std_logic_vector(unsigned(tmp_88_cast_fu_1166_p3) + unsigned(tmp_8_mid2_cast2_fu_999_p1));
    tmp_72_fu_1187_p2 <= std_logic_vector(unsigned(tmp_85_cast_fu_1157_p1) + unsigned(newIndex4_cast1_reg_1530));
    tmp_73_fu_1200_p2 <= std_logic_vector(unsigned(tmp_92_cast_fu_1192_p3) + unsigned(tmp_8_mid2_cast2_fu_999_p1));
    tmp_74_cast_fu_1080_p3 <= (tmp_63_fu_1075_p2 & ap_const_lv5_0);
    tmp_74_fu_1213_p2 <= std_logic_vector(unsigned(tmp_85_cast_fu_1157_p1) + unsigned(newIndex7_cast1_reg_1540));
    tmp_75_cast_fu_1094_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_64_fu_1088_p2),64));
    tmp_75_fu_1226_p2 <= std_logic_vector(unsigned(tmp_96_cast_fu_1218_p3) + unsigned(tmp_8_mid2_cast2_fu_999_p1));
    tmp_76_fu_1239_p2 <= std_logic_vector(unsigned(tmp_85_cast_fu_1157_p1) + unsigned(newIndex9_cast1_reg_1550));
    tmp_77_fu_1252_p2 <= std_logic_vector(unsigned(tmp_100_cast_fu_1244_p3) + unsigned(tmp_8_mid2_cast2_fu_999_p1));
    tmp_78_cast_fu_1105_p3 <= (tmp_65_fu_1100_p2 & ap_const_lv5_0);
    tmp_78_fu_1265_p2 <= std_logic_vector(unsigned(tmp_85_cast_fu_1157_p1) + unsigned(newIndex5_cast1_reg_1560));
    tmp_79_cast_fu_1119_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_66_fu_1113_p2),64));
    tmp_79_fu_1278_p2 <= std_logic_vector(unsigned(tmp_104_cast_fu_1270_p3) + unsigned(tmp_8_mid2_cast2_fu_999_p1));
    tmp_7_fu_1420_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ox_mid2_reg_1473),8));
    tmp_80_fu_1291_p3 <= (ky_mid2_reg_1579 & ap_const_lv5_0);
    tmp_81_fu_1302_p2 <= std_logic_vector(unsigned(tmp_107_cast_fu_1298_p1) + unsigned(tmp_8_mid2_cast1_fu_996_p1));
    tmp_82_cast_fu_1130_p3 <= (tmp_67_fu_1125_p2 & ap_const_lv5_0);
    tmp_82_fu_1316_p2 <= std_logic_vector(unsigned(tmp_110_cast_fu_1308_p3) + unsigned(tmp_mid2_cast1_reg_1496));
    tmp_83_cast_fu_1144_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_68_fu_1138_p2),64));
    tmp_85_cast_fu_1157_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_69_fu_1150_p3),6));
    tmp_88_cast_fu_1166_p3 <= (tmp_70_fu_1161_p2 & ap_const_lv5_0);
    tmp_89_cast_fu_1180_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_71_fu_1174_p2),64));
    tmp_8_mid2_cast1_fu_996_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_mid2_v_reg_1584),9));
    tmp_8_mid2_cast2_fu_999_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_mid2_v_reg_1584),11));
    tmp_8_mid2_cast_fu_1002_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_mid2_v_reg_1584),12));
    tmp_8_mid2_v_fu_973_p3 <= 
        ic_1_fu_953_p2 when (exitcond1_fu_959_p2(0) = '1') else 
        ap_phi_mux_ic_phi_fu_501_p4;
    tmp_92_cast_fu_1192_p3 <= (tmp_72_fu_1187_p2 & ap_const_lv5_0);
    tmp_93_cast_fu_1206_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_73_fu_1200_p2),64));
    tmp_96_cast_fu_1218_p3 <= (tmp_74_fu_1213_p2 & ap_const_lv5_0);
    tmp_97_cast_fu_1232_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_75_fu_1226_p2),64));
    tmp_9_fu_985_p2 <= std_logic_vector(unsigned(ky_cast_fu_981_p1) + unsigned(tmp_49_reg_1484));
    tmp_fu_702_p2 <= (exitcond_flatten1_fu_664_p2 or exitcond3_mid_fu_690_p2);
    tmp_mid2_cast1_fu_743_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_mid2_v_fu_736_p3),13));
    tmp_mid2_cast_fu_747_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_mid2_v_fu_736_p3),12));
    tmp_mid2_v_fu_736_p3 <= 
        oc_1_fu_730_p2 when (exitcond_flatten1_reg_1467(0) = '1') else 
        oc_reg_440;
    tmp_s_fu_1337_p0 <= w_det_0_load_reg_1754;
    tmp_s_fu_1337_p1 <= tmp_s_fu_1337_p10(31 - 1 downto 0);
    tmp_s_fu_1337_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_phi_reg_pp0_iter3_input_load_0_phi_reg_532),32));
    tmp_s_fu_1337_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(tmp_s_fu_1337_p0) * signed('0' &tmp_s_fu_1337_p1))), 32));
    w_det_0_address0 <= tmp_111_cast_fu_1321_p1(12 - 1 downto 0);

    w_det_0_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            w_det_0_ce0 <= ap_const_logic_1;
        else 
            w_det_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    w_det_1_address0 <= tmp_111_cast_fu_1321_p1(12 - 1 downto 0);

    w_det_1_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            w_det_1_ce0 <= ap_const_logic_1;
        else 
            w_det_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    w_det_2_address0 <= tmp_111_cast_fu_1321_p1(12 - 1 downto 0);

    w_det_2_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            w_det_2_ce0 <= ap_const_logic_1;
        else 
            w_det_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    w_det_3_address0 <= tmp_111_cast_fu_1321_p1(12 - 1 downto 0);

    w_det_3_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            w_det_3_ce0 <= ap_const_logic_1;
        else 
            w_det_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    w_det_4_address0 <= tmp_111_cast_fu_1321_p1(12 - 1 downto 0);

    w_det_4_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            w_det_4_ce0 <= ap_const_logic_1;
        else 
            w_det_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
