// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "decode.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic decode::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic decode::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<9> decode::ap_ST_fsm_state1 = "1";
const sc_lv<9> decode::ap_ST_fsm_state2 = "10";
const sc_lv<9> decode::ap_ST_fsm_state3 = "100";
const sc_lv<9> decode::ap_ST_fsm_state4 = "1000";
const sc_lv<9> decode::ap_ST_fsm_state5 = "10000";
const sc_lv<9> decode::ap_ST_fsm_state6 = "100000";
const sc_lv<9> decode::ap_ST_fsm_state7 = "1000000";
const sc_lv<9> decode::ap_ST_fsm_state8 = "10000000";
const sc_lv<9> decode::ap_ST_fsm_state9 = "100000000";
const sc_lv<32> decode::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> decode::ap_const_lv32_1 = "1";
const sc_lv<1> decode::ap_const_lv1_0 = "0";
const sc_lv<32> decode::ap_const_lv32_2 = "10";
const sc_lv<32> decode::ap_const_lv32_3 = "11";
const sc_lv<32> decode::ap_const_lv32_4 = "100";
const sc_lv<32> decode::ap_const_lv32_5 = "101";
const sc_lv<32> decode::ap_const_lv32_6 = "110";
const sc_lv<32> decode::ap_const_lv32_7 = "111";
const sc_lv<4> decode::ap_const_lv4_0 = "0000";
const sc_lv<1> decode::ap_const_lv1_1 = "1";
const sc_lv<2> decode::ap_const_lv2_0 = "00";
const sc_lv<32> decode::ap_const_lv32_8 = "1000";
const sc_lv<4> decode::ap_const_lv4_8 = "1000";
const sc_lv<4> decode::ap_const_lv4_1 = "1";
const sc_lv<3> decode::ap_const_lv3_0 = "000";
const sc_lv<2> decode::ap_const_lv2_2 = "10";
const sc_lv<2> decode::ap_const_lv2_1 = "1";
const sc_lv<4> decode::ap_const_lv4_4 = "100";
const sc_lv<64> decode::ap_const_lv64_3 = "11";
const sc_lv<4> decode::ap_const_lv4_2 = "10";
const sc_lv<12> decode::ap_const_lv12_1 = "1";
const sc_lv<12> decode::ap_const_lv12_2 = "10";
const sc_lv<4> decode::ap_const_lv4_3 = "11";
const sc_lv<32> decode::ap_const_lv32_FFFFFFF8 = "11111111111111111111111111111000";
const sc_lv<12> decode::ap_const_lv12_3 = "11";
const sc_lv<12> decode::ap_const_lv12_4 = "100";
const sc_lv<10> decode::ap_const_lv10_3E8 = "1111101000";
const sc_lv<10> decode::ap_const_lv10_0 = "0000000000";
const sc_lv<4> decode::ap_const_lv4_5 = "101";
const sc_lv<2> decode::ap_const_lv2_3 = "11";
const sc_lv<3> decode::ap_const_lv3_5 = "101";
const bool decode::ap_const_boolean_1 = true;

decode::decode(sc_module_name name) : sc_module(name), mVcdFile(0) {
    sigmoid_lut_U = new decode_sigmoid_lut("sigmoid_lut_U");
    sigmoid_lut_U->clk(ap_clk);
    sigmoid_lut_U->reset(ap_rst);
    sigmoid_lut_U->address0(sigmoid_lut_address0);
    sigmoid_lut_U->ce0(sigmoid_lut_ce0);
    sigmoid_lut_U->q0(sigmoid_lut_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_265_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_265_p2 );

    SC_METHOD(thread_b_1_fu_336_p2);
    sensitive << ( b_reg_242 );

    SC_METHOD(thread_buf_det_address0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_53_fu_363_p1 );
    sensitive << ( tmp_59_fu_422_p1 );
    sensitive << ( tmp_61_fu_485_p1 );

    SC_METHOD(thread_buf_det_address1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( tmp_62_fu_381_p1 );
    sensitive << ( tmp_60_fu_439_p1 );
    sensitive << ( tmp_94_cast_fu_609_p1 );

    SC_METHOD(thread_buf_det_ce0);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_buf_det_ce1);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state8 );

    SC_METHOD(thread_c_1_fu_589_p2);
    sensitive << ( c_reg_254 );

    SC_METHOD(thread_c_cast4_fu_575_p1);
    sensitive << ( c_reg_254 );

    SC_METHOD(thread_c_cast_fu_579_p1);
    sensitive << ( c_reg_254 );

    SC_METHOD(thread_exitcond1_fu_330_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( b_reg_242 );

    SC_METHOD(thread_exitcond2_fu_289_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( gx_reg_231 );

    SC_METHOD(thread_exitcond3_fu_265_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( gy_reg_220 );

    SC_METHOD(thread_exitcond_fu_583_p2);
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( c_reg_254 );

    SC_METHOD(thread_gx_1_fu_295_p2);
    sensitive << ( gx_reg_231 );

    SC_METHOD(thread_gy_1_fu_271_p2);
    sensitive << ( gy_reg_220 );

    SC_METHOD(thread_offset_fu_346_p3);
    sensitive << ( tmp_32_fu_342_p1 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_36_fu_403_p2 );
    sensitive << ( tmp_86_cast_fu_457_p1 );
    sensitive << ( tmp_89_cast_fu_525_p1 );

    SC_METHOD(thread_output_r_address1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_87_cast_fu_468_p1 );
    sensitive << ( tmp_88_cast_fu_515_p1 );
    sensitive << ( tmp_64_fu_619_p3 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_output_r_ce1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( buf_det_q0 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( p_0_i_cast_fu_561_p1 );

    SC_METHOD(thread_output_r_d1);
    sensitive << ( buf_det_q0 );
    sensitive << ( buf_det_q1 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_output_r_we1);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_p_0_i_cast_fu_561_p1);
    sensitive << ( p_0_i_fu_553_p3 );

    SC_METHOD(thread_p_0_i_fu_553_p3);
    sensitive << ( sigmoid_lut_q0 );
    sensitive << ( tmp_1_fu_548_p2 );
    sensitive << ( sel_tmp_cast_fu_540_p3 );

    SC_METHOD(thread_sel_tmp1_fu_530_p2);
    sensitive << ( tmp_i_reg_731 );

    SC_METHOD(thread_sel_tmp2_fu_535_p2);
    sensitive << ( tmp_1_i_reg_737 );
    sensitive << ( sel_tmp1_fu_530_p2 );

    SC_METHOD(thread_sel_tmp_cast_fu_540_p3);
    sensitive << ( sel_tmp2_fu_535_p2 );

    SC_METHOD(thread_sigmoid_lut_address0);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( tmp_3_i_fu_505_p1 );

    SC_METHOD(thread_sigmoid_lut_ce0);
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_tmp_14_fu_386_p1);
    sensitive << ( b_reg_242 );

    SC_METHOD(thread_tmp_15_fu_410_p2);
    sensitive << ( offset_reg_675 );

    SC_METHOD(thread_tmp_17_fu_427_p2);
    sensitive << ( offset_reg_675 );

    SC_METHOD(thread_tmp_19_fu_473_p2);
    sensitive << ( offset_reg_675 );

    SC_METHOD(thread_tmp_1_fu_548_p2);
    sensitive << ( tmp_i_reg_731 );
    sensitive << ( sel_tmp2_fu_535_p2 );

    SC_METHOD(thread_tmp_1_i_fu_495_p2);
    sensitive << ( buf_det_load_4_reg_713 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_tmp_21_fu_368_p2);
    sensitive << ( offset_fu_346_p3 );

    SC_METHOD(thread_tmp_24_cast_fu_571_p1);
    sensitive << ( tmp_24_fu_566_p2 );

    SC_METHOD(thread_tmp_24_fu_566_p2);
    sensitive << ( offset_reg_675 );

    SC_METHOD(thread_tmp_25_fu_595_p2);
    sensitive << ( tmp_24_cast_reg_747 );
    sensitive << ( c_cast4_fu_575_p1 );

    SC_METHOD(thread_tmp_26_cast_fu_600_p1);
    sensitive << ( tmp_25_fu_595_p2 );

    SC_METHOD(thread_tmp_27_fu_614_p2);
    sensitive << ( c_cast_reg_752 );

    SC_METHOD(thread_tmp_2_i_fu_500_p2);
    sensitive << ( buf_det_load_4_reg_713 );

    SC_METHOD(thread_tmp_31_fu_318_p3);
    sensitive << ( tmp_s_fu_305_p2 );

    SC_METHOD(thread_tmp_32_fu_342_p1);
    sensitive << ( b_reg_242 );

    SC_METHOD(thread_tmp_33_fu_354_p4);
    sensitive << ( tmp_s_reg_648 );
    sensitive << ( tmp_32_fu_342_p1 );

    SC_METHOD(thread_tmp_34_fu_395_p1);
    sensitive << ( tmp_54_fu_390_p2 );

    SC_METHOD(thread_tmp_35_fu_399_p1);
    sensitive << ( tmp_54_fu_390_p2 );

    SC_METHOD(thread_tmp_36_fu_403_p2);
    sensitive << ( tmp_54_fu_390_p2 );

    SC_METHOD(thread_tmp_37_fu_415_p3);
    sensitive << ( tmp_s_reg_648 );
    sensitive << ( tmp_15_fu_410_p2 );

    SC_METHOD(thread_tmp_38_fu_432_p3);
    sensitive << ( tmp_s_reg_648 );
    sensitive << ( tmp_17_fu_427_p2 );

    SC_METHOD(thread_tmp_39_fu_478_p3);
    sensitive << ( tmp_s_reg_648 );
    sensitive << ( tmp_19_fu_473_p2 );

    SC_METHOD(thread_tmp_3_i_fu_505_p1);
    sensitive << ( tmp_2_i_fu_500_p2 );

    SC_METHOD(thread_tmp_40_fu_374_p3);
    sensitive << ( tmp_s_reg_648 );
    sensitive << ( tmp_21_fu_368_p2 );

    SC_METHOD(thread_tmp_52_fu_326_p1);
    sensitive << ( tmp_31_fu_318_p3 );

    SC_METHOD(thread_tmp_53_fu_363_p1);
    sensitive << ( tmp_33_fu_354_p4 );

    SC_METHOD(thread_tmp_54_fu_390_p2);
    sensitive << ( tmp_52_reg_662 );
    sensitive << ( tmp_14_fu_386_p1 );

    SC_METHOD(thread_tmp_55_fu_451_p2);
    sensitive << ( tmp_85_cast_fu_444_p3 );

    SC_METHOD(thread_tmp_56_fu_462_p2);
    sensitive << ( tmp_85_cast_fu_444_p3 );

    SC_METHOD(thread_tmp_57_fu_510_p2);
    sensitive << ( tmp_85_cast_reg_720 );

    SC_METHOD(thread_tmp_58_fu_520_p2);
    sensitive << ( tmp_85_cast_reg_720 );

    SC_METHOD(thread_tmp_59_fu_422_p1);
    sensitive << ( tmp_37_fu_415_p3 );

    SC_METHOD(thread_tmp_60_fu_439_p1);
    sensitive << ( tmp_38_fu_432_p3 );

    SC_METHOD(thread_tmp_61_fu_485_p1);
    sensitive << ( tmp_39_fu_478_p3 );

    SC_METHOD(thread_tmp_62_fu_381_p1);
    sensitive << ( tmp_40_fu_374_p3 );

    SC_METHOD(thread_tmp_63_fu_604_p2);
    sensitive << ( tmp_78_cast_reg_657 );
    sensitive << ( tmp_26_cast_fu_600_p1 );

    SC_METHOD(thread_tmp_64_fu_619_p3);
    sensitive << ( tmp_34_reg_693 );
    sensitive << ( tmp_27_fu_614_p2 );

    SC_METHOD(thread_tmp_75_cast_fu_285_p1);
    sensitive << ( tmp_fu_277_p3 );

    SC_METHOD(thread_tmp_78_cast_fu_310_p3);
    sensitive << ( tmp_s_fu_305_p2 );

    SC_METHOD(thread_tmp_85_cast_fu_444_p3);
    sensitive << ( tmp_35_reg_698 );

    SC_METHOD(thread_tmp_86_cast_fu_457_p1);
    sensitive << ( tmp_55_fu_451_p2 );

    SC_METHOD(thread_tmp_87_cast_fu_468_p1);
    sensitive << ( tmp_56_fu_462_p2 );

    SC_METHOD(thread_tmp_88_cast_fu_515_p1);
    sensitive << ( tmp_57_fu_510_p2 );

    SC_METHOD(thread_tmp_89_cast_fu_525_p1);
    sensitive << ( tmp_58_fu_520_p2 );

    SC_METHOD(thread_tmp_94_cast_fu_609_p1);
    sensitive << ( tmp_63_fu_604_p2 );

    SC_METHOD(thread_tmp_cast_fu_301_p1);
    sensitive << ( gx_reg_231 );

    SC_METHOD(thread_tmp_fu_277_p3);
    sensitive << ( gy_reg_220 );

    SC_METHOD(thread_tmp_i_fu_490_p2);
    sensitive << ( buf_det_load_4_reg_713 );
    sensitive << ( ap_CS_fsm_state6 );

    SC_METHOD(thread_tmp_s_fu_305_p2);
    sensitive << ( tmp_75_cast_reg_635 );
    sensitive << ( tmp_cast_fu_301_p1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond3_fu_265_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond2_fu_289_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond1_fu_330_p2 );
    sensitive << ( ap_CS_fsm_state8 );
    sensitive << ( exitcond_fu_583_p2 );

    ap_CS_fsm = "000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "decode_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, output_r_address1, "(port)output_r_address1");
    sc_trace(mVcdFile, output_r_ce1, "(port)output_r_ce1");
    sc_trace(mVcdFile, output_r_we1, "(port)output_r_we1");
    sc_trace(mVcdFile, output_r_d1, "(port)output_r_d1");
    sc_trace(mVcdFile, buf_det_address0, "(port)buf_det_address0");
    sc_trace(mVcdFile, buf_det_ce0, "(port)buf_det_ce0");
    sc_trace(mVcdFile, buf_det_q0, "(port)buf_det_q0");
    sc_trace(mVcdFile, buf_det_address1, "(port)buf_det_address1");
    sc_trace(mVcdFile, buf_det_ce1, "(port)buf_det_ce1");
    sc_trace(mVcdFile, buf_det_q1, "(port)buf_det_q1");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, sigmoid_lut_address0, "sigmoid_lut_address0");
    sc_trace(mVcdFile, sigmoid_lut_ce0, "sigmoid_lut_ce0");
    sc_trace(mVcdFile, sigmoid_lut_q0, "sigmoid_lut_q0");
    sc_trace(mVcdFile, gy_1_fu_271_p2, "gy_1_fu_271_p2");
    sc_trace(mVcdFile, gy_1_reg_630, "gy_1_reg_630");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_75_cast_fu_285_p1, "tmp_75_cast_fu_285_p1");
    sc_trace(mVcdFile, tmp_75_cast_reg_635, "tmp_75_cast_reg_635");
    sc_trace(mVcdFile, exitcond3_fu_265_p2, "exitcond3_fu_265_p2");
    sc_trace(mVcdFile, gx_1_fu_295_p2, "gx_1_fu_295_p2");
    sc_trace(mVcdFile, gx_1_reg_643, "gx_1_reg_643");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_s_fu_305_p2, "tmp_s_fu_305_p2");
    sc_trace(mVcdFile, tmp_s_reg_648, "tmp_s_reg_648");
    sc_trace(mVcdFile, exitcond2_fu_289_p2, "exitcond2_fu_289_p2");
    sc_trace(mVcdFile, tmp_78_cast_fu_310_p3, "tmp_78_cast_fu_310_p3");
    sc_trace(mVcdFile, tmp_78_cast_reg_657, "tmp_78_cast_reg_657");
    sc_trace(mVcdFile, tmp_52_fu_326_p1, "tmp_52_fu_326_p1");
    sc_trace(mVcdFile, tmp_52_reg_662, "tmp_52_reg_662");
    sc_trace(mVcdFile, b_1_fu_336_p2, "b_1_fu_336_p2");
    sc_trace(mVcdFile, b_1_reg_670, "b_1_reg_670");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, offset_fu_346_p3, "offset_fu_346_p3");
    sc_trace(mVcdFile, offset_reg_675, "offset_reg_675");
    sc_trace(mVcdFile, exitcond1_fu_330_p2, "exitcond1_fu_330_p2");
    sc_trace(mVcdFile, tmp_34_fu_395_p1, "tmp_34_fu_395_p1");
    sc_trace(mVcdFile, tmp_34_reg_693, "tmp_34_reg_693");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_35_fu_399_p1, "tmp_35_fu_399_p1");
    sc_trace(mVcdFile, tmp_35_reg_698, "tmp_35_reg_698");
    sc_trace(mVcdFile, buf_det_load_4_reg_713, "buf_det_load_4_reg_713");
    sc_trace(mVcdFile, tmp_85_cast_fu_444_p3, "tmp_85_cast_fu_444_p3");
    sc_trace(mVcdFile, tmp_85_cast_reg_720, "tmp_85_cast_reg_720");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_i_fu_490_p2, "tmp_i_fu_490_p2");
    sc_trace(mVcdFile, tmp_i_reg_731, "tmp_i_reg_731");
    sc_trace(mVcdFile, tmp_1_i_fu_495_p2, "tmp_1_i_fu_495_p2");
    sc_trace(mVcdFile, tmp_1_i_reg_737, "tmp_1_i_reg_737");
    sc_trace(mVcdFile, tmp_24_cast_fu_571_p1, "tmp_24_cast_fu_571_p1");
    sc_trace(mVcdFile, tmp_24_cast_reg_747, "tmp_24_cast_reg_747");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, c_cast_fu_579_p1, "c_cast_fu_579_p1");
    sc_trace(mVcdFile, c_cast_reg_752, "c_cast_reg_752");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, c_1_fu_589_p2, "c_1_fu_589_p2");
    sc_trace(mVcdFile, c_1_reg_760, "c_1_reg_760");
    sc_trace(mVcdFile, exitcond_fu_583_p2, "exitcond_fu_583_p2");
    sc_trace(mVcdFile, gy_reg_220, "gy_reg_220");
    sc_trace(mVcdFile, gx_reg_231, "gx_reg_231");
    sc_trace(mVcdFile, b_reg_242, "b_reg_242");
    sc_trace(mVcdFile, c_reg_254, "c_reg_254");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, tmp_53_fu_363_p1, "tmp_53_fu_363_p1");
    sc_trace(mVcdFile, tmp_62_fu_381_p1, "tmp_62_fu_381_p1");
    sc_trace(mVcdFile, tmp_36_fu_403_p2, "tmp_36_fu_403_p2");
    sc_trace(mVcdFile, tmp_59_fu_422_p1, "tmp_59_fu_422_p1");
    sc_trace(mVcdFile, tmp_60_fu_439_p1, "tmp_60_fu_439_p1");
    sc_trace(mVcdFile, tmp_86_cast_fu_457_p1, "tmp_86_cast_fu_457_p1");
    sc_trace(mVcdFile, tmp_87_cast_fu_468_p1, "tmp_87_cast_fu_468_p1");
    sc_trace(mVcdFile, tmp_61_fu_485_p1, "tmp_61_fu_485_p1");
    sc_trace(mVcdFile, tmp_3_i_fu_505_p1, "tmp_3_i_fu_505_p1");
    sc_trace(mVcdFile, tmp_88_cast_fu_515_p1, "tmp_88_cast_fu_515_p1");
    sc_trace(mVcdFile, tmp_89_cast_fu_525_p1, "tmp_89_cast_fu_525_p1");
    sc_trace(mVcdFile, tmp_94_cast_fu_609_p1, "tmp_94_cast_fu_609_p1");
    sc_trace(mVcdFile, tmp_64_fu_619_p3, "tmp_64_fu_619_p3");
    sc_trace(mVcdFile, p_0_i_cast_fu_561_p1, "p_0_i_cast_fu_561_p1");
    sc_trace(mVcdFile, tmp_fu_277_p3, "tmp_fu_277_p3");
    sc_trace(mVcdFile, tmp_cast_fu_301_p1, "tmp_cast_fu_301_p1");
    sc_trace(mVcdFile, tmp_31_fu_318_p3, "tmp_31_fu_318_p3");
    sc_trace(mVcdFile, tmp_32_fu_342_p1, "tmp_32_fu_342_p1");
    sc_trace(mVcdFile, tmp_33_fu_354_p4, "tmp_33_fu_354_p4");
    sc_trace(mVcdFile, tmp_21_fu_368_p2, "tmp_21_fu_368_p2");
    sc_trace(mVcdFile, tmp_40_fu_374_p3, "tmp_40_fu_374_p3");
    sc_trace(mVcdFile, tmp_14_fu_386_p1, "tmp_14_fu_386_p1");
    sc_trace(mVcdFile, tmp_54_fu_390_p2, "tmp_54_fu_390_p2");
    sc_trace(mVcdFile, tmp_15_fu_410_p2, "tmp_15_fu_410_p2");
    sc_trace(mVcdFile, tmp_37_fu_415_p3, "tmp_37_fu_415_p3");
    sc_trace(mVcdFile, tmp_17_fu_427_p2, "tmp_17_fu_427_p2");
    sc_trace(mVcdFile, tmp_38_fu_432_p3, "tmp_38_fu_432_p3");
    sc_trace(mVcdFile, tmp_55_fu_451_p2, "tmp_55_fu_451_p2");
    sc_trace(mVcdFile, tmp_56_fu_462_p2, "tmp_56_fu_462_p2");
    sc_trace(mVcdFile, tmp_19_fu_473_p2, "tmp_19_fu_473_p2");
    sc_trace(mVcdFile, tmp_39_fu_478_p3, "tmp_39_fu_478_p3");
    sc_trace(mVcdFile, tmp_2_i_fu_500_p2, "tmp_2_i_fu_500_p2");
    sc_trace(mVcdFile, tmp_57_fu_510_p2, "tmp_57_fu_510_p2");
    sc_trace(mVcdFile, tmp_58_fu_520_p2, "tmp_58_fu_520_p2");
    sc_trace(mVcdFile, sel_tmp1_fu_530_p2, "sel_tmp1_fu_530_p2");
    sc_trace(mVcdFile, sel_tmp2_fu_535_p2, "sel_tmp2_fu_535_p2");
    sc_trace(mVcdFile, tmp_1_fu_548_p2, "tmp_1_fu_548_p2");
    sc_trace(mVcdFile, sel_tmp_cast_fu_540_p3, "sel_tmp_cast_fu_540_p3");
    sc_trace(mVcdFile, p_0_i_fu_553_p3, "p_0_i_fu_553_p3");
    sc_trace(mVcdFile, tmp_24_fu_566_p2, "tmp_24_fu_566_p2");
    sc_trace(mVcdFile, c_cast4_fu_575_p1, "c_cast4_fu_575_p1");
    sc_trace(mVcdFile, tmp_25_fu_595_p2, "tmp_25_fu_595_p2");
    sc_trace(mVcdFile, tmp_26_cast_fu_600_p1, "tmp_26_cast_fu_600_p1");
    sc_trace(mVcdFile, tmp_63_fu_604_p2, "tmp_63_fu_604_p2");
    sc_trace(mVcdFile, tmp_27_fu_614_p2, "tmp_27_fu_614_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

decode::~decode() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete sigmoid_lut_U;
}

void decode::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_583_p2.read(), ap_const_lv1_1))) {
        b_reg_242 = b_1_reg_670.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_289_p2.read()))) {
        b_reg_242 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        c_reg_254 = c_1_reg_760.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        c_reg_254 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_330_p2.read(), ap_const_lv1_1))) {
        gx_reg_231 = gx_1_reg_643.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond3_fu_265_p2.read(), ap_const_lv1_0))) {
        gx_reg_231 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_289_p2.read(), ap_const_lv1_1))) {
        gy_reg_220 = gy_1_reg_630.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        gy_reg_220 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        b_1_reg_670 = b_1_fu_336_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buf_det_load_4_reg_713 = buf_det_q1.read();
        tmp_34_reg_693 = tmp_34_fu_395_p1.read();
        tmp_35_reg_698 = tmp_35_fu_399_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        c_1_reg_760 = c_1_fu_589_p2.read();
        c_cast_reg_752 = c_cast_fu_579_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        gx_1_reg_643 = gx_1_fu_295_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        gy_1_reg_630 = gy_1_fu_271_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_330_p2.read()))) {
        offset_reg_675 = offset_fu_346_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmp_1_i_reg_737 = tmp_1_i_fu_495_p2.read();
        tmp_85_cast_reg_720 = tmp_85_cast_fu_444_p3.read();
        tmp_i_reg_731 = tmp_i_fu_490_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        tmp_24_cast_reg_747 = tmp_24_cast_fu_571_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_289_p2.read()))) {
        tmp_52_reg_662 = tmp_52_fu_326_p1.read();
        tmp_78_cast_reg_657 = tmp_78_cast_fu_310_p3.read();
        tmp_s_reg_648 = tmp_s_fu_305_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond3_fu_265_p2.read(), ap_const_lv1_0))) {
        tmp_75_cast_reg_635 = tmp_75_cast_fu_285_p1.read();
    }
}

void decode::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void decode::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void decode::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void decode::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void decode::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void decode::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void decode::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void decode::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void decode::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void decode::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond3_fu_265_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void decode::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void decode::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_265_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void decode::thread_b_1_fu_336_p2() {
    b_1_fu_336_p2 = (!b_reg_242.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(b_reg_242.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void decode::thread_buf_det_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        buf_det_address0 =  (sc_lv<10>) (tmp_61_fu_485_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buf_det_address0 =  (sc_lv<10>) (tmp_59_fu_422_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buf_det_address0 =  (sc_lv<10>) (tmp_53_fu_363_p1.read());
    } else {
        buf_det_address0 = "XXXXXXXXXX";
    }
}

void decode::thread_buf_det_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        buf_det_address1 =  (sc_lv<10>) (tmp_94_cast_fu_609_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        buf_det_address1 =  (sc_lv<10>) (tmp_60_fu_439_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        buf_det_address1 =  (sc_lv<10>) (tmp_62_fu_381_p1.read());
    } else {
        buf_det_address1 = "XXXXXXXXXX";
    }
}

void decode::thread_buf_det_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        buf_det_ce0 = ap_const_logic_1;
    } else {
        buf_det_ce0 = ap_const_logic_0;
    }
}

void decode::thread_buf_det_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()))) {
        buf_det_ce1 = ap_const_logic_1;
    } else {
        buf_det_ce1 = ap_const_logic_0;
    }
}

void decode::thread_c_1_fu_589_p2() {
    c_1_fu_589_p2 = (!c_reg_254.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(c_reg_254.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void decode::thread_c_cast4_fu_575_p1() {
    c_cast4_fu_575_p1 = esl_zext<5,2>(c_reg_254.read());
}

void decode::thread_c_cast_fu_579_p1() {
    c_cast_fu_579_p1 = esl_zext<3,2>(c_reg_254.read());
}

void decode::thread_exitcond1_fu_330_p2() {
    exitcond1_fu_330_p2 = (!b_reg_242.read().is_01() || !ap_const_lv2_2.is_01())? sc_lv<1>(): sc_lv<1>(b_reg_242.read() == ap_const_lv2_2);
}

void decode::thread_exitcond2_fu_289_p2() {
    exitcond2_fu_289_p2 = (!gx_reg_231.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(gx_reg_231.read() == ap_const_lv4_8);
}

void decode::thread_exitcond3_fu_265_p2() {
    exitcond3_fu_265_p2 = (!gy_reg_220.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(gy_reg_220.read() == ap_const_lv4_8);
}

void decode::thread_exitcond_fu_583_p2() {
    exitcond_fu_583_p2 = (!c_reg_254.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(c_reg_254.read() == ap_const_lv2_3);
}

void decode::thread_gx_1_fu_295_p2() {
    gx_1_fu_295_p2 = (!gx_reg_231.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(gx_reg_231.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void decode::thread_gy_1_fu_271_p2() {
    gy_1_fu_271_p2 = (!gy_reg_220.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(gy_reg_220.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void decode::thread_offset_fu_346_p3() {
    offset_fu_346_p3 = esl_concat<1,3>(tmp_32_fu_342_p1.read(), ap_const_lv3_0);
}

void decode::thread_output_r_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_r_address0 =  (sc_lv<10>) (tmp_89_cast_fu_525_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_address0 =  (sc_lv<10>) (tmp_86_cast_fu_457_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_r_address0 =  (sc_lv<10>) (tmp_36_fu_403_p2.read());
    } else {
        output_r_address0 = "XXXXXXXXXX";
    }
}

void decode::thread_output_r_address1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        output_r_address1 =  (sc_lv<10>) (tmp_64_fu_619_p3.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_r_address1 =  (sc_lv<10>) (tmp_88_cast_fu_515_p1.read());
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        output_r_address1 =  (sc_lv<10>) (tmp_87_cast_fu_468_p1.read());
    } else {
        output_r_address1 = "XXXXXXXXXX";
    }
}

void decode::thread_output_r_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void decode::thread_output_r_ce1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        output_r_ce1 = ap_const_logic_1;
    } else {
        output_r_ce1 = ap_const_logic_0;
    }
}

void decode::thread_output_r_d0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_r_d0 = p_0_i_cast_fu_561_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()))) {
        output_r_d0 = buf_det_q0.read();
    } else {
        output_r_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void decode::thread_output_r_d1() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        output_r_d1 = buf_det_q0.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        output_r_d1 = buf_det_q1.read();
    } else {
        output_r_d1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void decode::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void decode::thread_output_r_we1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()))) {
        output_r_we1 = ap_const_logic_1;
    } else {
        output_r_we1 = ap_const_logic_0;
    }
}

void decode::thread_p_0_i_cast_fu_561_p1() {
    p_0_i_cast_fu_561_p1 = esl_zext<32,10>(p_0_i_fu_553_p3.read());
}

void decode::thread_p_0_i_fu_553_p3() {
    p_0_i_fu_553_p3 = (!tmp_1_fu_548_p2.read()[0].is_01())? sc_lv<10>(): ((tmp_1_fu_548_p2.read()[0].to_bool())? sel_tmp_cast_fu_540_p3.read(): sigmoid_lut_q0.read());
}

void decode::thread_sel_tmp1_fu_530_p2() {
    sel_tmp1_fu_530_p2 = (tmp_i_reg_731.read() ^ ap_const_lv1_1);
}

void decode::thread_sel_tmp2_fu_535_p2() {
    sel_tmp2_fu_535_p2 = (tmp_1_i_reg_737.read() & sel_tmp1_fu_530_p2.read());
}

void decode::thread_sel_tmp_cast_fu_540_p3() {
    sel_tmp_cast_fu_540_p3 = (!sel_tmp2_fu_535_p2.read()[0].is_01())? sc_lv<10>(): ((sel_tmp2_fu_535_p2.read()[0].to_bool())? ap_const_lv10_3E8: ap_const_lv10_0);
}

void decode::thread_sigmoid_lut_address0() {
    sigmoid_lut_address0 =  (sc_lv<5>) (tmp_3_i_fu_505_p1.read());
}

void decode::thread_sigmoid_lut_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        sigmoid_lut_ce0 = ap_const_logic_1;
    } else {
        sigmoid_lut_ce0 = ap_const_logic_0;
    }
}

void decode::thread_tmp_14_fu_386_p1() {
    tmp_14_fu_386_p1 = esl_zext<64,2>(b_reg_242.read());
}

void decode::thread_tmp_15_fu_410_p2() {
    tmp_15_fu_410_p2 = (offset_reg_675.read() | ap_const_lv4_1);
}

void decode::thread_tmp_17_fu_427_p2() {
    tmp_17_fu_427_p2 = (offset_reg_675.read() | ap_const_lv4_2);
}

void decode::thread_tmp_19_fu_473_p2() {
    tmp_19_fu_473_p2 = (offset_reg_675.read() | ap_const_lv4_3);
}

void decode::thread_tmp_1_fu_548_p2() {
    tmp_1_fu_548_p2 = (sel_tmp2_fu_535_p2.read() | tmp_i_reg_731.read());
}

void decode::thread_tmp_1_i_fu_495_p2() {
    tmp_1_i_fu_495_p2 = (!buf_det_load_4_reg_713.read().is_01() || !ap_const_lv32_8.is_01())? sc_lv<1>(): (sc_bigint<32>(buf_det_load_4_reg_713.read()) > sc_bigint<32>(ap_const_lv32_8));
}

void decode::thread_tmp_21_fu_368_p2() {
    tmp_21_fu_368_p2 = (offset_fu_346_p3.read() | ap_const_lv4_4);
}

void decode::thread_tmp_24_cast_fu_571_p1() {
    tmp_24_cast_fu_571_p1 = esl_zext<5,4>(tmp_24_fu_566_p2.read());
}

void decode::thread_tmp_24_fu_566_p2() {
    tmp_24_fu_566_p2 = (offset_reg_675.read() | ap_const_lv4_5);
}

void decode::thread_tmp_25_fu_595_p2() {
    tmp_25_fu_595_p2 = (!tmp_24_cast_reg_747.read().is_01() || !c_cast4_fu_575_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_24_cast_reg_747.read()) + sc_biguint<5>(c_cast4_fu_575_p1.read()));
}

void decode::thread_tmp_26_cast_fu_600_p1() {
    tmp_26_cast_fu_600_p1 = esl_zext<12,5>(tmp_25_fu_595_p2.read());
}

void decode::thread_tmp_27_fu_614_p2() {
    tmp_27_fu_614_p2 = (!c_cast_reg_752.read().is_01() || !ap_const_lv3_5.is_01())? sc_lv<3>(): (sc_biguint<3>(c_cast_reg_752.read()) + sc_bigint<3>(ap_const_lv3_5));
}

void decode::thread_tmp_2_i_fu_500_p2() {
    tmp_2_i_fu_500_p2 = (!ap_const_lv32_8.is_01() || !buf_det_load_4_reg_713.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_8) + sc_biguint<32>(buf_det_load_4_reg_713.read()));
}

void decode::thread_tmp_31_fu_318_p3() {
    tmp_31_fu_318_p3 = esl_concat<8,1>(tmp_s_fu_305_p2.read(), ap_const_lv1_0);
}

void decode::thread_tmp_32_fu_342_p1() {
    tmp_32_fu_342_p1 = b_reg_242.read().range(1-1, 0);
}

void decode::thread_tmp_33_fu_354_p4() {
    tmp_33_fu_354_p4 = esl_concat<9,3>(esl_concat<8,1>(tmp_s_reg_648.read(), tmp_32_fu_342_p1.read()), ap_const_lv3_0);
}

void decode::thread_tmp_34_fu_395_p1() {
    tmp_34_fu_395_p1 = tmp_54_fu_390_p2.read().range(61-1, 0);
}

void decode::thread_tmp_35_fu_399_p1() {
    tmp_35_fu_399_p1 = tmp_54_fu_390_p2.read().range(9-1, 0);
}

void decode::thread_tmp_36_fu_403_p2() {
    tmp_36_fu_403_p2 = (!ap_const_lv64_3.is_01())? sc_lv<64>(): tmp_54_fu_390_p2.read() << (unsigned short)ap_const_lv64_3.to_uint();
}

void decode::thread_tmp_37_fu_415_p3() {
    tmp_37_fu_415_p3 = esl_concat<8,4>(tmp_s_reg_648.read(), tmp_15_fu_410_p2.read());
}

void decode::thread_tmp_38_fu_432_p3() {
    tmp_38_fu_432_p3 = esl_concat<8,4>(tmp_s_reg_648.read(), tmp_17_fu_427_p2.read());
}

void decode::thread_tmp_39_fu_478_p3() {
    tmp_39_fu_478_p3 = esl_concat<8,4>(tmp_s_reg_648.read(), tmp_19_fu_473_p2.read());
}

void decode::thread_tmp_3_i_fu_505_p1() {
    tmp_3_i_fu_505_p1 = esl_zext<64,32>(tmp_2_i_fu_500_p2.read());
}

void decode::thread_tmp_40_fu_374_p3() {
    tmp_40_fu_374_p3 = esl_concat<8,4>(tmp_s_reg_648.read(), tmp_21_fu_368_p2.read());
}

void decode::thread_tmp_52_fu_326_p1() {
    tmp_52_fu_326_p1 = esl_zext<64,9>(tmp_31_fu_318_p3.read());
}

void decode::thread_tmp_53_fu_363_p1() {
    tmp_53_fu_363_p1 = esl_zext<64,12>(tmp_33_fu_354_p4.read());
}

void decode::thread_tmp_54_fu_390_p2() {
    tmp_54_fu_390_p2 = (!tmp_52_reg_662.read().is_01() || !tmp_14_fu_386_p1.read().is_01())? sc_lv<64>(): (sc_biguint<64>(tmp_52_reg_662.read()) + sc_biguint<64>(tmp_14_fu_386_p1.read()));
}

void decode::thread_tmp_55_fu_451_p2() {
    tmp_55_fu_451_p2 = (tmp_85_cast_fu_444_p3.read() | ap_const_lv12_1);
}

void decode::thread_tmp_56_fu_462_p2() {
    tmp_56_fu_462_p2 = (tmp_85_cast_fu_444_p3.read() | ap_const_lv12_2);
}

void decode::thread_tmp_57_fu_510_p2() {
    tmp_57_fu_510_p2 = (tmp_85_cast_reg_720.read() | ap_const_lv12_3);
}

void decode::thread_tmp_58_fu_520_p2() {
    tmp_58_fu_520_p2 = (tmp_85_cast_reg_720.read() | ap_const_lv12_4);
}

void decode::thread_tmp_59_fu_422_p1() {
    tmp_59_fu_422_p1 = esl_zext<64,12>(tmp_37_fu_415_p3.read());
}

void decode::thread_tmp_60_fu_439_p1() {
    tmp_60_fu_439_p1 = esl_zext<64,12>(tmp_38_fu_432_p3.read());
}

void decode::thread_tmp_61_fu_485_p1() {
    tmp_61_fu_485_p1 = esl_zext<64,12>(tmp_39_fu_478_p3.read());
}

void decode::thread_tmp_62_fu_381_p1() {
    tmp_62_fu_381_p1 = esl_zext<64,12>(tmp_40_fu_374_p3.read());
}

void decode::thread_tmp_63_fu_604_p2() {
    tmp_63_fu_604_p2 = (!tmp_26_cast_fu_600_p1.read().is_01() || !tmp_78_cast_reg_657.read().is_01())? sc_lv<12>(): (sc_biguint<12>(tmp_26_cast_fu_600_p1.read()) + sc_biguint<12>(tmp_78_cast_reg_657.read()));
}

void decode::thread_tmp_64_fu_619_p3() {
    tmp_64_fu_619_p3 = esl_concat<61,3>(tmp_34_reg_693.read(), tmp_27_fu_614_p2.read());
}

void decode::thread_tmp_75_cast_fu_285_p1() {
    tmp_75_cast_fu_285_p1 = esl_zext<8,7>(tmp_fu_277_p3.read());
}

void decode::thread_tmp_78_cast_fu_310_p3() {
    tmp_78_cast_fu_310_p3 = esl_concat<8,4>(tmp_s_fu_305_p2.read(), ap_const_lv4_0);
}

void decode::thread_tmp_85_cast_fu_444_p3() {
    tmp_85_cast_fu_444_p3 = esl_concat<9,3>(tmp_35_reg_698.read(), ap_const_lv3_0);
}

void decode::thread_tmp_86_cast_fu_457_p1() {
    tmp_86_cast_fu_457_p1 = esl_zext<64,12>(tmp_55_fu_451_p2.read());
}

void decode::thread_tmp_87_cast_fu_468_p1() {
    tmp_87_cast_fu_468_p1 = esl_zext<64,12>(tmp_56_fu_462_p2.read());
}

void decode::thread_tmp_88_cast_fu_515_p1() {
    tmp_88_cast_fu_515_p1 = esl_zext<64,12>(tmp_57_fu_510_p2.read());
}

void decode::thread_tmp_89_cast_fu_525_p1() {
    tmp_89_cast_fu_525_p1 = esl_zext<64,12>(tmp_58_fu_520_p2.read());
}

void decode::thread_tmp_94_cast_fu_609_p1() {
    tmp_94_cast_fu_609_p1 = esl_zext<64,12>(tmp_63_fu_604_p2.read());
}

void decode::thread_tmp_cast_fu_301_p1() {
    tmp_cast_fu_301_p1 = esl_zext<8,4>(gx_reg_231.read());
}

void decode::thread_tmp_fu_277_p3() {
    tmp_fu_277_p3 = esl_concat<4,3>(gy_reg_220.read(), ap_const_lv3_0);
}

void decode::thread_tmp_i_fu_490_p2() {
    tmp_i_fu_490_p2 = (!buf_det_load_4_reg_713.read().is_01() || !ap_const_lv32_FFFFFFF8.is_01())? sc_lv<1>(): (sc_bigint<32>(buf_det_load_4_reg_713.read()) < sc_bigint<32>(ap_const_lv32_FFFFFFF8));
}

void decode::thread_tmp_s_fu_305_p2() {
    tmp_s_fu_305_p2 = (!tmp_cast_fu_301_p1.read().is_01() || !tmp_75_cast_reg_635.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_cast_fu_301_p1.read()) + sc_biguint<8>(tmp_75_cast_reg_635.read()));
}

void decode::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond3_fu_265_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond2_fu_289_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond1_fu_330_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read()) && esl_seteq<1,1,1>(exitcond_fu_583_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state9;
            }
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<9>) ("XXXXXXXXX");
            break;
    }
}

}

