-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity conv_layer1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_r_address0 : OUT STD_LOGIC_VECTOR (13 downto 0);
    input_r_ce0 : OUT STD_LOGIC;
    input_r_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
    output_r_address0 : OUT STD_LOGIC_VECTOR (14 downto 0);
    output_r_ce0 : OUT STD_LOGIC;
    output_r_we0 : OUT STD_LOGIC;
    output_r_d0 : OUT STD_LOGIC_VECTOR (30 downto 0) );
end;


architecture behav of conv_layer1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (9 downto 0) := "0000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (9 downto 0) := "0000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (9 downto 0) := "0000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (9 downto 0) := "0000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (9 downto 0) := "0000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (9 downto 0) := "0001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (9 downto 0) := "0010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (9 downto 0) := "0100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (9 downto 0) := "1000000000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv6_3E : STD_LOGIC_VECTOR (5 downto 0) := "111110";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv2_3 : STD_LOGIC_VECTOR (1 downto 0) := "11";
    constant ap_const_lv2_1 : STD_LOGIC_VECTOR (1 downto 0) := "01";
    constant ap_const_lv31_0 : STD_LOGIC_VECTOR (30 downto 0) := "0000000000000000000000000000000";
    constant ap_const_lv6_2 : STD_LOGIC_VECTOR (5 downto 0) := "000010";
    constant ap_const_boolean_1 : BOOLEAN := true;

    signal ap_CS_fsm : STD_LOGIC_VECTOR (9 downto 0) := "0000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal w_conv1_address0 : STD_LOGIC_VECTOR (7 downto 0);
    signal w_conv1_ce0 : STD_LOGIC;
    signal w_conv1_q0 : STD_LOGIC_VECTOR (3 downto 0);
    signal row_3_fu_222_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal row_3_reg_522 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal tmp_90_fu_252_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_90_reg_527 : STD_LOGIC_VECTOR (12 downto 0);
    signal exitcond5_fu_216_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal col_3_fu_264_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal col_3_reg_535 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_142_cast_fu_279_p3 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_142_cast_reg_540 : STD_LOGIC_VECTOR (15 downto 0);
    signal exitcond4_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal oc_4_fu_293_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal oc_4_reg_548 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_51_cast5_fu_299_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_51_cast5_reg_553 : STD_LOGIC_VECTOR (8 downto 0);
    signal exitcond3_fu_287_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal output_addr_reg_558 : STD_LOGIC_VECTOR (14 downto 0);
    signal kr_3_fu_327_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal kr_3_reg_566 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_54_fu_333_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_54_reg_571 : STD_LOGIC_VECTOR (5 downto 0);
    signal exitcond2_fu_321_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_145_cast_fu_361_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_145_cast_reg_577 : STD_LOGIC_VECTOR (5 downto 0);
    signal kc_3_fu_394_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal kc_3_reg_585 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal tmp_97_fu_430_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_97_reg_590 : STD_LOGIC_VECTOR (14 downto 0);
    signal exitcond1_fu_388_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_99_fu_447_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_99_reg_595 : STD_LOGIC_VECTOR (5 downto 0);
    signal ic_4_fu_459_p2 : STD_LOGIC_VECTOR (1 downto 0);
    signal ic_4_reg_603 : STD_LOGIC_VECTOR (1 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal exitcond_fu_453_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal input_load_reg_618 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal w_conv1_load_reg_623 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_61_fu_509_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_61_reg_628 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal sum_6_fu_514_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal row_reg_112 : STD_LOGIC_VECTOR (5 downto 0);
    signal col_reg_124 : STD_LOGIC_VECTOR (5 downto 0);
    signal oc_reg_136 : STD_LOGIC_VECTOR (3 downto 0);
    signal kr_reg_147 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum_reg_158 : STD_LOGIC_VECTOR (31 downto 0);
    signal kc_reg_170 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum_1_reg_181 : STD_LOGIC_VECTOR (31 downto 0);
    signal ic_reg_193 : STD_LOGIC_VECTOR (1 downto 0);
    signal sum_2_reg_204 : STD_LOGIC_VECTOR (31 downto 0);
    signal tmp_143_cast_fu_312_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_156_cast_fu_491_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_157_cast_fu_501_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_228_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_s_fu_240_p3 : STD_LOGIC_VECTOR (6 downto 0);
    signal p_shl_cast_fu_236_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal p_shl1_cast_fu_248_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_cast_fu_270_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_91_fu_274_p2 : STD_LOGIC_VECTOR (12 downto 0);
    signal tmp_51_cast_fu_303_p1 : STD_LOGIC_VECTOR (15 downto 0);
    signal tmp_92_fu_307_p2 : STD_LOGIC_VECTOR (15 downto 0);
    signal kr_cast5_fu_317_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_93_fu_343_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal p_shl2_cast_fu_351_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_56_cast_fu_339_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_94_fu_355_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_52_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_48_fu_365_p1 : STD_LOGIC_VECTOR (30 downto 0);
    signal kc_cast3_fu_384_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_57_fu_400_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_95_fu_406_p3 : STD_LOGIC_VECTOR (11 downto 0);
    signal tmp_96_fu_417_p4 : STD_LOGIC_VECTOR (13 downto 0);
    signal p_shl4_cast_fu_426_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_147_cast_fu_413_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_98_fu_436_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_49_fu_441_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_60_fu_465_p1 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_100_fu_473_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_155_cast_fu_478_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_101_fu_486_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_60_cast_fu_469_p1 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_102_fu_496_p2 : STD_LOGIC_VECTOR (14 downto 0);
    signal tmp_61_fu_509_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (9 downto 0);

    component conv_layer1_w_conv1 IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (7 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;



begin
    w_conv1_U : component conv_layer1_w_conv1
    generic map (
        DataWidth => 4,
        AddressRange => 216,
        AddressWidth => 8)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => w_conv1_address0,
        ce0 => w_conv1_ce0,
        q0 => w_conv1_q0);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    col_reg_124_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond3_fu_287_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                col_reg_124 <= col_3_reg_535;
            elsif (((exitcond5_fu_216_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                col_reg_124 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    ic_reg_193_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                ic_reg_193 <= ic_4_reg_603;
            elsif (((exitcond1_fu_388_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                ic_reg_193 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    kc_reg_170_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (exitcond_fu_453_p2 = ap_const_lv1_1))) then 
                kc_reg_170 <= kc_3_reg_585;
            elsif (((exitcond2_fu_321_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                kc_reg_170 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    kr_reg_147_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (exitcond1_fu_388_p2 = ap_const_lv1_1))) then 
                kr_reg_147 <= kr_3_reg_566;
            elsif (((exitcond3_fu_287_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                kr_reg_147 <= ap_const_lv2_0;
            end if; 
        end if;
    end process;

    oc_reg_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond2_fu_321_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                oc_reg_136 <= oc_4_reg_548;
            elsif (((exitcond4_fu_258_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                oc_reg_136 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    row_reg_112_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond4_fu_258_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                row_reg_112 <= row_3_reg_522;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                row_reg_112 <= ap_const_lv6_0;
            end if; 
        end if;
    end process;

    sum_1_reg_181_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state7) and (exitcond_fu_453_p2 = ap_const_lv1_1))) then 
                sum_1_reg_181 <= sum_2_reg_204;
            elsif (((exitcond2_fu_321_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
                sum_1_reg_181 <= sum_reg_158;
            end if; 
        end if;
    end process;

    sum_2_reg_204_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                sum_2_reg_204 <= sum_6_fu_514_p2;
            elsif (((exitcond1_fu_388_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then 
                sum_2_reg_204 <= sum_1_reg_181;
            end if; 
        end if;
    end process;

    sum_reg_158_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (exitcond1_fu_388_p2 = ap_const_lv1_1))) then 
                sum_reg_158 <= sum_1_reg_181;
            elsif (((exitcond3_fu_287_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then 
                sum_reg_158 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                col_3_reg_535 <= col_3_fu_264_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state7)) then
                ic_4_reg_603 <= ic_4_fu_459_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state8)) then
                input_load_reg_618 <= input_r_q0;
                w_conv1_load_reg_623 <= w_conv1_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state6)) then
                kc_3_reg_585 <= kc_3_fu_394_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                kr_3_reg_566 <= kr_3_fu_327_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                oc_4_reg_548 <= oc_4_fu_293_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond3_fu_287_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                output_addr_reg_558 <= tmp_143_cast_fu_312_p1(15 - 1 downto 0);
                    tmp_51_cast5_reg_553(3 downto 0) <= tmp_51_cast5_fu_299_p1(3 downto 0);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                row_3_reg_522 <= row_3_fu_222_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond4_fu_258_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    tmp_142_cast_reg_540(15 downto 3) <= tmp_142_cast_fu_279_p3(15 downto 3);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond2_fu_321_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                tmp_145_cast_reg_577 <= tmp_145_cast_fu_361_p1;
                tmp_54_reg_571 <= tmp_54_fu_333_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state9)) then
                tmp_61_reg_628 <= tmp_61_fu_509_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond5_fu_216_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    tmp_90_reg_527(12 downto 1) <= tmp_90_fu_252_p2(12 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond1_fu_388_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state6))) then
                tmp_97_reg_590 <= tmp_97_fu_430_p2;
                tmp_99_reg_595 <= tmp_99_fu_447_p2;
            end if;
        end if;
    end process;
    tmp_90_reg_527(0) <= '0';
    tmp_142_cast_reg_540(2 downto 0) <= "000";
    tmp_51_cast5_reg_553(8 downto 4) <= "00000";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, exitcond5_fu_216_p2, ap_CS_fsm_state3, exitcond4_fu_258_p2, ap_CS_fsm_state4, exitcond3_fu_287_p2, ap_CS_fsm_state5, exitcond2_fu_321_p2, ap_CS_fsm_state6, exitcond1_fu_388_p2, ap_CS_fsm_state7, exitcond_fu_453_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((exitcond5_fu_216_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((exitcond4_fu_258_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                if (((exitcond3_fu_287_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state4))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state5;
                end if;
            when ap_ST_fsm_state5 => 
                if (((exitcond2_fu_321_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then
                    ap_NS_fsm <= ap_ST_fsm_state4;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (exitcond1_fu_388_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state5;
                else
                    ap_NS_fsm <= ap_ST_fsm_state7;
                end if;
            when ap_ST_fsm_state7 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state7) and (exitcond_fu_453_p2 = ap_const_lv1_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state6;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                ap_NS_fsm <= ap_ST_fsm_state9;
            when ap_ST_fsm_state9 => 
                ap_NS_fsm <= ap_ST_fsm_state10;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state7;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXX";
        end case;
    end process;
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, exitcond5_fu_216_p2)
    begin
        if ((((exitcond5_fu_216_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2)) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, exitcond5_fu_216_p2)
    begin
        if (((exitcond5_fu_216_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    col_3_fu_264_p2 <= std_logic_vector(unsigned(col_reg_124) + unsigned(ap_const_lv6_1));
    exitcond1_fu_388_p2 <= "1" when (kc_reg_170 = ap_const_lv2_3) else "0";
    exitcond2_fu_321_p2 <= "1" when (kr_reg_147 = ap_const_lv2_3) else "0";
    exitcond3_fu_287_p2 <= "1" when (oc_reg_136 = ap_const_lv4_8) else "0";
    exitcond4_fu_258_p2 <= "1" when (col_reg_124 = ap_const_lv6_3E) else "0";
    exitcond5_fu_216_p2 <= "1" when (row_reg_112 = ap_const_lv6_3E) else "0";
    exitcond_fu_453_p2 <= "1" when (ic_reg_193 = ap_const_lv2_3) else "0";
    ic_4_fu_459_p2 <= std_logic_vector(unsigned(ic_reg_193) + unsigned(ap_const_lv2_1));
    input_r_address0 <= tmp_157_cast_fu_501_p1(14 - 1 downto 0);

    input_r_ce0_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            input_r_ce0 <= ap_const_logic_1;
        else 
            input_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    kc_3_fu_394_p2 <= std_logic_vector(unsigned(kc_reg_170) + unsigned(ap_const_lv2_1));
    kc_cast3_fu_384_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kc_reg_170),6));
    kr_3_fu_327_p2 <= std_logic_vector(unsigned(kr_reg_147) + unsigned(ap_const_lv2_1));
    kr_cast5_fu_317_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kr_reg_147),6));
    oc_4_fu_293_p2 <= std_logic_vector(unsigned(oc_reg_136) + unsigned(ap_const_lv4_1));
    output_r_address0 <= output_addr_reg_558;

    output_r_ce0_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            output_r_ce0 <= ap_const_logic_1;
        else 
            output_r_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_r_d0 <= 
        tmp_48_fu_365_p1 when (tmp_52_fu_369_p2(0) = '1') else 
        ap_const_lv31_0;

    output_r_we0_assign_proc : process(ap_CS_fsm_state5, exitcond2_fu_321_p2)
    begin
        if (((exitcond2_fu_321_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state5))) then 
            output_r_we0 <= ap_const_logic_1;
        else 
            output_r_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_shl1_cast_fu_248_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_s_fu_240_p3),13));
    p_shl2_cast_fu_351_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_93_fu_343_p3),5));
    p_shl4_cast_fu_426_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_96_fu_417_p4),15));
    p_shl_cast_fu_236_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_228_p3),13));
    row_3_fu_222_p2 <= std_logic_vector(unsigned(row_reg_112) + unsigned(ap_const_lv6_1));
    sum_6_fu_514_p2 <= std_logic_vector(unsigned(tmp_61_reg_628) + unsigned(sum_2_reg_204));
    tmp_100_fu_473_p2 <= std_logic_vector(unsigned(tmp_60_fu_465_p1) + unsigned(tmp_99_reg_595));
    tmp_101_fu_486_p2 <= std_logic_vector(unsigned(tmp_51_cast5_reg_553) + unsigned(tmp_155_cast_fu_478_p3));
    tmp_102_fu_496_p2 <= std_logic_vector(unsigned(tmp_60_cast_fu_469_p1) + unsigned(tmp_97_reg_590));
    tmp_142_cast_fu_279_p3 <= (tmp_91_fu_274_p2 & ap_const_lv3_0);
    tmp_143_cast_fu_312_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_92_fu_307_p2),64));
        tmp_145_cast_fu_361_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_94_fu_355_p2),6));

    tmp_147_cast_fu_413_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_95_fu_406_p3),15));
    tmp_155_cast_fu_478_p3 <= (tmp_100_fu_473_p2 & ap_const_lv3_0);
    tmp_156_cast_fu_491_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_101_fu_486_p2),64));
        tmp_157_cast_fu_501_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_102_fu_496_p2),64));

    tmp_48_fu_365_p1 <= sum_reg_158(31 - 1 downto 0);
    tmp_49_fu_441_p2 <= std_logic_vector(shift_left(unsigned(tmp_98_fu_436_p2),to_integer(unsigned('0' & ap_const_lv6_2(6-1 downto 0)))));
    tmp_51_cast5_fu_299_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(oc_reg_136),9));
    tmp_51_cast_fu_303_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(oc_reg_136),16));
    tmp_52_fu_369_p2 <= "1" when (signed(sum_reg_158) > signed(ap_const_lv32_0)) else "0";
    tmp_54_fu_333_p2 <= std_logic_vector(unsigned(kr_cast5_fu_317_p1) + unsigned(row_reg_112));
    tmp_56_cast_fu_339_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(kr_reg_147),5));
    tmp_57_fu_400_p2 <= std_logic_vector(unsigned(col_reg_124) + unsigned(kc_cast3_fu_384_p1));
    tmp_60_cast_fu_469_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_reg_193),15));
    tmp_60_fu_465_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ic_reg_193),6));
    tmp_61_fu_509_p1 <= w_conv1_load_reg_623;
    tmp_61_fu_509_p2 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(std_logic_vector(signed(input_load_reg_618) * signed(tmp_61_fu_509_p1))), 32));
    tmp_90_fu_252_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_236_p1) - unsigned(p_shl1_cast_fu_248_p1));
    tmp_91_fu_274_p2 <= std_logic_vector(unsigned(tmp_cast_fu_270_p1) + unsigned(tmp_90_reg_527));
    tmp_92_fu_307_p2 <= std_logic_vector(unsigned(tmp_142_cast_reg_540) + unsigned(tmp_51_cast_fu_303_p1));
    tmp_93_fu_343_p3 <= (kr_reg_147 & ap_const_lv2_0);
    tmp_94_fu_355_p2 <= std_logic_vector(unsigned(p_shl2_cast_fu_351_p1) - unsigned(tmp_56_cast_fu_339_p1));
    tmp_95_fu_406_p3 <= (tmp_54_reg_571 & tmp_57_fu_400_p2);
    tmp_96_fu_417_p4 <= ((tmp_54_reg_571 & tmp_57_fu_400_p2) & ap_const_lv2_0);
    tmp_97_fu_430_p2 <= std_logic_vector(unsigned(p_shl4_cast_fu_426_p1) - unsigned(tmp_147_cast_fu_413_p1));
    tmp_98_fu_436_p2 <= std_logic_vector(unsigned(kc_cast3_fu_384_p1) + unsigned(tmp_145_cast_reg_577));
    tmp_99_fu_447_p2 <= std_logic_vector(unsigned(tmp_49_fu_441_p2) - unsigned(tmp_98_fu_436_p2));
    tmp_cast_fu_270_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(col_reg_124),13));
    tmp_fu_228_p3 <= (row_reg_112 & ap_const_lv6_0);
    tmp_s_fu_240_p3 <= (row_reg_112 & ap_const_lv1_0);
    w_conv1_address0 <= tmp_156_cast_fu_491_p1(8 - 1 downto 0);

    w_conv1_ce0_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            w_conv1_ce0 <= ap_const_logic_1;
        else 
            w_conv1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

end behav;
