-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
-- Version: 2018.3
-- Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity maxpool_layer2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    output_0_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_0_ce0 : OUT STD_LOGIC;
    output_0_we0 : OUT STD_LOGIC;
    output_0_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_1_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_1_ce0 : OUT STD_LOGIC;
    output_1_we0 : OUT STD_LOGIC;
    output_1_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_2_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_2_ce0 : OUT STD_LOGIC;
    output_2_we0 : OUT STD_LOGIC;
    output_2_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_3_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_3_ce0 : OUT STD_LOGIC;
    output_3_we0 : OUT STD_LOGIC;
    output_3_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_4_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_4_ce0 : OUT STD_LOGIC;
    output_4_we0 : OUT STD_LOGIC;
    output_4_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_5_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_5_ce0 : OUT STD_LOGIC;
    output_5_we0 : OUT STD_LOGIC;
    output_5_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_6_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_6_ce0 : OUT STD_LOGIC;
    output_6_we0 : OUT STD_LOGIC;
    output_6_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_7_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_7_ce0 : OUT STD_LOGIC;
    output_7_we0 : OUT STD_LOGIC;
    output_7_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_8_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_8_ce0 : OUT STD_LOGIC;
    output_8_we0 : OUT STD_LOGIC;
    output_8_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_9_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_9_ce0 : OUT STD_LOGIC;
    output_9_we0 : OUT STD_LOGIC;
    output_9_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_10_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_10_ce0 : OUT STD_LOGIC;
    output_10_we0 : OUT STD_LOGIC;
    output_10_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_11_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_11_ce0 : OUT STD_LOGIC;
    output_11_we0 : OUT STD_LOGIC;
    output_11_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_12_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_12_ce0 : OUT STD_LOGIC;
    output_12_we0 : OUT STD_LOGIC;
    output_12_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_13_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_13_ce0 : OUT STD_LOGIC;
    output_13_we0 : OUT STD_LOGIC;
    output_13_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_14_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_14_ce0 : OUT STD_LOGIC;
    output_14_we0 : OUT STD_LOGIC;
    output_14_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    output_15_address0 : OUT STD_LOGIC_VECTOR (7 downto 0);
    output_15_ce0 : OUT STD_LOGIC;
    output_15_we0 : OUT STD_LOGIC;
    output_15_d0 : OUT STD_LOGIC_VECTOR (30 downto 0);
    buf_conv2_0_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    buf_conv2_0_ce0 : OUT STD_LOGIC;
    buf_conv2_0_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    buf_conv2_0_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    buf_conv2_0_ce1 : OUT STD_LOGIC;
    buf_conv2_0_q1 : IN STD_LOGIC_VECTOR (30 downto 0);
    buf_conv2_1_address0 : OUT STD_LOGIC_VECTOR (12 downto 0);
    buf_conv2_1_ce0 : OUT STD_LOGIC;
    buf_conv2_1_q0 : IN STD_LOGIC_VECTOR (30 downto 0);
    buf_conv2_1_address1 : OUT STD_LOGIC_VECTOR (12 downto 0);
    buf_conv2_1_ce1 : OUT STD_LOGIC;
    buf_conv2_1_q1 : IN STD_LOGIC_VECTOR (30 downto 0) );
end;


architecture behav of maxpool_layer2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_E : STD_LOGIC_VECTOR (3 downto 0) := "1110";
    constant ap_const_lv4_D : STD_LOGIC_VECTOR (3 downto 0) := "1101";
    constant ap_const_lv4_C : STD_LOGIC_VECTOR (3 downto 0) := "1100";
    constant ap_const_lv4_B : STD_LOGIC_VECTOR (3 downto 0) := "1011";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_9 : STD_LOGIC_VECTOR (3 downto 0) := "1001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_F : STD_LOGIC_VECTOR (3 downto 0) := "1111";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv12_C40 : STD_LOGIC_VECTOR (11 downto 0) := "110001000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv8_C4 : STD_LOGIC_VECTOR (7 downto 0) := "11000100";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal indvar_flatten1_reg_380 : STD_LOGIC_VECTOR (11 downto 0);
    signal ch_reg_391 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten_reg_402 : STD_LOGIC_VECTOR (7 downto 0);
    signal out_row_reg_413 : STD_LOGIC_VECTOR (3 downto 0);
    signal out_col_reg_424 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond_flatten1_fu_449_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten1_reg_909 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_block_state2_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state3_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_state4_pp0_stage0_iter2 : BOOLEAN;
    signal ap_block_state5_pp0_stage0_iter3 : BOOLEAN;
    signal ap_block_state6_pp0_stage0_iter4 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal exitcond_flatten1_reg_909_pp0_iter1_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten1_reg_909_pp0_iter2_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal exitcond_flatten1_reg_909_pp0_iter3_reg : STD_LOGIC_VECTOR (0 downto 0);
    signal indvar_flatten_next1_fu_455_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC := '0';
    signal tmp_mid2_v_fu_481_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_mid2_v_reg_918 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_mid2_v_reg_918_pp0_iter1_reg : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_1_fu_489_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_reg_924 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_reg_924_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_reg_924_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_1_reg_924_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal out_col_mid2_fu_539_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal out_col_mid2_reg_928 : STD_LOGIC_VECTOR (3 downto 0);
    signal out_col_mid2_reg_928_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal out_col_mid2_reg_928_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal out_col_mid2_reg_928_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_5_mid2_fu_555_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_mid2_reg_937 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_7_mid2_fu_569_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_7_mid2_reg_944 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_8_mid2_fu_577_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_mid2_reg_951 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_mid2_reg_951_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_mid2_reg_951_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_8_mid2_reg_951_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal out_col_1_fu_585_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal indvar_flatten_next_fu_597_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_23_fu_672_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_23_reg_968 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_27_fu_687_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_27_reg_973 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_31_fu_702_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_31_reg_978 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_35_fu_717_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_35_reg_983 : STD_LOGIC_VECTOR (9 downto 0);
    signal v0_fu_804_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal v0_reg_1008 : STD_LOGIC_VECTOR (30 downto 0);
    signal v2_fu_818_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal v2_reg_1014 : STD_LOGIC_VECTOR (30 downto 0);
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal ap_condition_pp0_exit_iter0_state2 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_phi_mux_ch_phi_fu_395_p4 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_phi_mux_out_row_phi_fu_417_p4 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_24_cast_fu_739_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_28_cast_fu_757_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_32_cast_fu_775_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_36_cast_fu_793_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_37_cast_fu_863_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal m0_1_fu_887_p3 : STD_LOGIC_VECTOR (30 downto 0);
    signal in_row_fu_435_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal exitcond_flatten_fu_467_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ch_1_fu_461_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_6_fu_443_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal exitcond_fu_515_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal not_exitcond_flatten_fu_509_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_row_mid_fu_473_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal exitcond_mid_fu_521_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_533_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal out_row_1_fu_527_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal in_row_mid1_fu_547_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_5_mid_fu_493_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_6_mid1_fu_563_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_7_mid_fu_501_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten_op_fu_591_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_fu_605_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_8_fu_619_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_12_fu_634_p3 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_15_fu_648_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal tmp_5_fu_612_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_7_fu_616_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_22_fu_669_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_21_fu_663_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_13_fu_641_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_14_fu_645_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_26_fu_684_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_25_fu_678_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_10_fu_626_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_11_fu_630_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_30_fu_699_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_29_fu_693_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_16_fu_655_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_17_fu_659_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_34_fu_714_p1 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_33_fu_708_p2 : STD_LOGIC_VECTOR (9 downto 0);
    signal tmp_mid2_cast_fu_723_p1 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_23_cast_fu_726_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_24_fu_733_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_27_cast_fu_744_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_28_fu_751_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_31_cast_fu_762_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_32_fu_769_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_35_cast_fu_780_p3 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_36_fu_787_p2 : STD_LOGIC_VECTOR (13 downto 0);
    signal tmp_3_fu_798_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_4_fu_812_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_18_fu_826_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_19_fu_837_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal p_shl_cast_fu_833_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal p_shl1_cast_fu_844_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal out_col1_cast_fu_854_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_20_fu_848_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_37_fu_857_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_9_fu_883_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_enable_pp0 : STD_LOGIC;


begin




    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter0_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
            else
                if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_0;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter0 <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then
                    if ((ap_const_logic_1 = ap_condition_pp0_exit_iter0_state2)) then 
                        ap_enable_reg_pp0_iter1 <= (ap_const_logic_1 xor ap_condition_pp0_exit_iter0_state2);
                    elsif ((ap_const_boolean_1 = ap_const_boolean_1)) then 
                        ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
                    end if;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    ch_reg_391_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_flatten1_reg_909 = ap_const_lv1_0))) then 
                ch_reg_391 <= tmp_mid2_v_reg_918;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                ch_reg_391 <= ap_const_lv5_0;
            end if; 
        end if;
    end process;

    indvar_flatten1_reg_380_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_flatten1_fu_449_p2 = ap_const_lv1_0))) then 
                indvar_flatten1_reg_380 <= indvar_flatten_next1_fu_455_p2;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten1_reg_380 <= ap_const_lv12_0;
            end if; 
        end if;
    end process;

    indvar_flatten_reg_402_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_flatten1_fu_449_p2 = ap_const_lv1_0))) then 
                indvar_flatten_reg_402 <= indvar_flatten_next_fu_597_p3;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                indvar_flatten_reg_402 <= ap_const_lv8_0;
            end if; 
        end if;
    end process;

    out_col_reg_424_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_flatten1_fu_449_p2 = ap_const_lv1_0))) then 
                out_col_reg_424 <= out_col_1_fu_585_p2;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                out_col_reg_424 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;

    out_row_reg_413_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_flatten1_reg_909 = ap_const_lv1_0))) then 
                out_row_reg_413 <= tmp_8_mid2_reg_951;
            elsif (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                out_row_reg_413 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                exitcond_flatten1_reg_909 <= exitcond_flatten1_fu_449_p2;
                exitcond_flatten1_reg_909_pp0_iter1_reg <= exitcond_flatten1_reg_909;
                out_col_mid2_reg_928_pp0_iter1_reg <= out_col_mid2_reg_928;
                tmp_1_reg_924_pp0_iter1_reg <= tmp_1_reg_924;
                tmp_8_mid2_reg_951_pp0_iter1_reg <= tmp_8_mid2_reg_951;
                tmp_mid2_v_reg_918_pp0_iter1_reg <= tmp_mid2_v_reg_918;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                exitcond_flatten1_reg_909_pp0_iter2_reg <= exitcond_flatten1_reg_909_pp0_iter1_reg;
                exitcond_flatten1_reg_909_pp0_iter3_reg <= exitcond_flatten1_reg_909_pp0_iter2_reg;
                out_col_mid2_reg_928_pp0_iter2_reg <= out_col_mid2_reg_928_pp0_iter1_reg;
                out_col_mid2_reg_928_pp0_iter3_reg <= out_col_mid2_reg_928_pp0_iter2_reg;
                tmp_1_reg_924_pp0_iter2_reg <= tmp_1_reg_924_pp0_iter1_reg;
                tmp_1_reg_924_pp0_iter3_reg <= tmp_1_reg_924_pp0_iter2_reg;
                tmp_8_mid2_reg_951_pp0_iter2_reg <= tmp_8_mid2_reg_951_pp0_iter1_reg;
                tmp_8_mid2_reg_951_pp0_iter3_reg <= tmp_8_mid2_reg_951_pp0_iter2_reg;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_flatten1_fu_449_p2 = ap_const_lv1_0))) then
                out_col_mid2_reg_928 <= out_col_mid2_fu_539_p3;
                tmp_1_reg_924 <= tmp_1_fu_489_p1;
                    tmp_5_mid2_reg_937(4 downto 1) <= tmp_5_mid2_fu_555_p3(4 downto 1);
                    tmp_7_mid2_reg_944(4 downto 1) <= tmp_7_mid2_fu_569_p3(4 downto 1);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_flatten1_reg_909 = ap_const_lv1_0))) then
                tmp_23_reg_968 <= tmp_23_fu_672_p2;
                tmp_27_reg_973 <= tmp_27_fu_687_p2;
                tmp_31_reg_978 <= tmp_31_fu_702_p2;
                tmp_35_reg_983 <= tmp_35_fu_717_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (exitcond_flatten1_fu_449_p2 = ap_const_lv1_0))) then
                tmp_8_mid2_reg_951 <= tmp_8_mid2_fu_577_p3;
                tmp_mid2_v_reg_918 <= tmp_mid2_v_fu_481_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((exitcond_flatten1_reg_909_pp0_iter2_reg = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then
                v0_reg_1008 <= v0_fu_804_p3;
                v2_reg_1014 <= v2_fu_818_p3;
            end if;
        end if;
    end process;
    tmp_5_mid2_reg_937(0) <= '0';
    tmp_7_mid2_reg_944(0) <= '1';

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, exitcond_flatten1_fu_449_p2, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_start = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_pp0_stage0 => 
                if ((not(((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (exitcond_flatten1_fu_449_p2 = ap_const_lv1_1))) and not(((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1))))) then
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                elsif ((((ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1)) or ((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (exitcond_flatten1_fu_449_p2 = ap_const_lv1_1)))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
                end if;
            when ap_ST_fsm_state7 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(1);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state7 <= ap_CS_fsm(2);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state3_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state4_pp0_stage0_iter2 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state5_pp0_stage0_iter3 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state6_pp0_stage0_iter4 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_pp0_exit_iter0_state2_assign_proc : process(exitcond_flatten1_fu_449_p2)
    begin
        if ((exitcond_flatten1_fu_449_p2 = ap_const_lv1_1)) then 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_1;
        else 
            ap_condition_pp0_exit_iter0_state2 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state7)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state7) or ((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);

    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_ch_phi_fu_395_p4_assign_proc : process(ch_reg_391, exitcond_flatten1_reg_909, ap_CS_fsm_pp0_stage0, tmp_mid2_v_reg_918, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten1_reg_909 = ap_const_lv1_0))) then 
            ap_phi_mux_ch_phi_fu_395_p4 <= tmp_mid2_v_reg_918;
        else 
            ap_phi_mux_ch_phi_fu_395_p4 <= ch_reg_391;
        end if; 
    end process;


    ap_phi_mux_out_row_phi_fu_417_p4_assign_proc : process(out_row_reg_413, exitcond_flatten1_reg_909, ap_CS_fsm_pp0_stage0, tmp_8_mid2_reg_951, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (exitcond_flatten1_reg_909 = ap_const_lv1_0))) then 
            ap_phi_mux_out_row_phi_fu_417_p4 <= tmp_8_mid2_reg_951;
        else 
            ap_phi_mux_out_row_phi_fu_417_p4 <= out_row_reg_413;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state7)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state7)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    buf_conv2_0_address0 <= tmp_24_cast_fu_739_p1(13 - 1 downto 0);
    buf_conv2_0_address1 <= tmp_28_cast_fu_757_p1(13 - 1 downto 0);

    buf_conv2_0_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            buf_conv2_0_ce0 <= ap_const_logic_1;
        else 
            buf_conv2_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_conv2_0_ce1_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            buf_conv2_0_ce1 <= ap_const_logic_1;
        else 
            buf_conv2_0_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    buf_conv2_1_address0 <= tmp_32_cast_fu_775_p1(13 - 1 downto 0);
    buf_conv2_1_address1 <= tmp_36_cast_fu_793_p1(13 - 1 downto 0);

    buf_conv2_1_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            buf_conv2_1_ce0 <= ap_const_logic_1;
        else 
            buf_conv2_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    buf_conv2_1_ce1_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter2)
    begin
        if (((ap_enable_reg_pp0_iter2 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            buf_conv2_1_ce1 <= ap_const_logic_1;
        else 
            buf_conv2_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    ch_1_fu_461_p2 <= std_logic_vector(unsigned(ap_const_lv5_1) + unsigned(ap_phi_mux_ch_phi_fu_395_p4));
    exitcond_flatten1_fu_449_p2 <= "1" when (indvar_flatten1_reg_380 = ap_const_lv12_C40) else "0";
    exitcond_flatten_fu_467_p2 <= "1" when (indvar_flatten_reg_402 = ap_const_lv8_C4) else "0";
    exitcond_fu_515_p2 <= "1" when (out_col_reg_424 = ap_const_lv4_E) else "0";
    exitcond_mid_fu_521_p2 <= (not_exitcond_flatten_fu_509_p2 and exitcond_fu_515_p2);
    in_row_fu_435_p3 <= (ap_phi_mux_out_row_phi_fu_417_p4 & ap_const_lv1_0);
    in_row_mid1_fu_547_p3 <= (out_row_1_fu_527_p2 & ap_const_lv1_0);
    indvar_flatten_next1_fu_455_p2 <= std_logic_vector(unsigned(indvar_flatten1_reg_380) + unsigned(ap_const_lv12_1));
    indvar_flatten_next_fu_597_p3 <= 
        ap_const_lv8_1 when (exitcond_flatten_fu_467_p2(0) = '1') else 
        indvar_flatten_op_fu_591_p2;
    indvar_flatten_op_fu_591_p2 <= std_logic_vector(unsigned(indvar_flatten_reg_402) + unsigned(ap_const_lv8_1));
    m0_1_fu_887_p3 <= 
        v0_reg_1008 when (tmp_9_fu_883_p2(0) = '1') else 
        v2_reg_1014;
    not_exitcond_flatten_fu_509_p2 <= (exitcond_flatten_fu_467_p2 xor ap_const_lv1_1);
    out_col1_cast_fu_854_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_col_mid2_reg_928_pp0_iter3_reg),9));
    out_col_1_fu_585_p2 <= std_logic_vector(unsigned(out_col_mid2_fu_539_p3) + unsigned(ap_const_lv4_1));
    out_col_mid2_fu_539_p3 <= 
        ap_const_lv4_0 when (tmp_fu_533_p2(0) = '1') else 
        out_col_reg_424;
    out_row_1_fu_527_p2 <= std_logic_vector(unsigned(ap_const_lv4_1) + unsigned(out_row_mid_fu_473_p3));
    out_row_mid_fu_473_p3 <= 
        ap_const_lv4_0 when (exitcond_flatten_fu_467_p2(0) = '1') else 
        ap_phi_mux_out_row_phi_fu_417_p4;
    output_0_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_0_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_0_ce0 <= ap_const_logic_1;
        else 
            output_0_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_0_d0 <= m0_1_fu_887_p3;

    output_0_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_0_we0 <= ap_const_logic_1;
        else 
            output_0_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_10_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_10_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_10_ce0 <= ap_const_logic_1;
        else 
            output_10_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_10_d0 <= m0_1_fu_887_p3;

    output_10_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_A) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_10_we0 <= ap_const_logic_1;
        else 
            output_10_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_11_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_11_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_11_ce0 <= ap_const_logic_1;
        else 
            output_11_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_11_d0 <= m0_1_fu_887_p3;

    output_11_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_B) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_11_we0 <= ap_const_logic_1;
        else 
            output_11_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_12_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_12_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_12_ce0 <= ap_const_logic_1;
        else 
            output_12_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_12_d0 <= m0_1_fu_887_p3;

    output_12_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_C) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_12_we0 <= ap_const_logic_1;
        else 
            output_12_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_13_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_13_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_13_ce0 <= ap_const_logic_1;
        else 
            output_13_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_13_d0 <= m0_1_fu_887_p3;

    output_13_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_D) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_13_we0 <= ap_const_logic_1;
        else 
            output_13_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_14_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_14_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_14_ce0 <= ap_const_logic_1;
        else 
            output_14_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_14_d0 <= m0_1_fu_887_p3;

    output_14_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_E) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_14_we0 <= ap_const_logic_1;
        else 
            output_14_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_15_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_15_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_15_ce0 <= ap_const_logic_1;
        else 
            output_15_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_15_d0 <= m0_1_fu_887_p3;

    output_15_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_F) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_15_we0 <= ap_const_logic_1;
        else 
            output_15_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_1_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_1_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_1_ce0 <= ap_const_logic_1;
        else 
            output_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_1_d0 <= m0_1_fu_887_p3;

    output_1_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_1) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_1_we0 <= ap_const_logic_1;
        else 
            output_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_2_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_2_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_2_ce0 <= ap_const_logic_1;
        else 
            output_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_2_d0 <= m0_1_fu_887_p3;

    output_2_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_2) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_2_we0 <= ap_const_logic_1;
        else 
            output_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_3_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_3_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_3_ce0 <= ap_const_logic_1;
        else 
            output_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_3_d0 <= m0_1_fu_887_p3;

    output_3_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_3) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_3_we0 <= ap_const_logic_1;
        else 
            output_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_4_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_4_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_4_ce0 <= ap_const_logic_1;
        else 
            output_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_4_d0 <= m0_1_fu_887_p3;

    output_4_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_4) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_4_we0 <= ap_const_logic_1;
        else 
            output_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_5_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_5_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_5_ce0 <= ap_const_logic_1;
        else 
            output_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_5_d0 <= m0_1_fu_887_p3;

    output_5_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_5) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_5_we0 <= ap_const_logic_1;
        else 
            output_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_6_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_6_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_6_ce0 <= ap_const_logic_1;
        else 
            output_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_6_d0 <= m0_1_fu_887_p3;

    output_6_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_6) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_6_we0 <= ap_const_logic_1;
        else 
            output_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_7_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_7_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_7_ce0 <= ap_const_logic_1;
        else 
            output_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_7_d0 <= m0_1_fu_887_p3;

    output_7_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_7) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_7_we0 <= ap_const_logic_1;
        else 
            output_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_8_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_8_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_8_ce0 <= ap_const_logic_1;
        else 
            output_8_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_8_d0 <= m0_1_fu_887_p3;

    output_8_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_8) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_8_we0 <= ap_const_logic_1;
        else 
            output_8_we0 <= ap_const_logic_0;
        end if; 
    end process;

    output_9_address0 <= tmp_37_cast_fu_863_p1(8 - 1 downto 0);

    output_9_ce0_assign_proc : process(ap_block_pp0_stage0_11001, ap_enable_reg_pp0_iter4)
    begin
        if (((ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_9_ce0 <= ap_const_logic_1;
        else 
            output_9_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    output_9_d0 <= m0_1_fu_887_p3;

    output_9_we0_assign_proc : process(ap_block_pp0_stage0_11001, tmp_1_reg_924_pp0_iter3_reg, ap_enable_reg_pp0_iter4)
    begin
        if (((tmp_1_reg_924_pp0_iter3_reg = ap_const_lv4_9) and (ap_enable_reg_pp0_iter4 = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001))) then 
            output_9_we0 <= ap_const_logic_1;
        else 
            output_9_we0 <= ap_const_logic_0;
        end if; 
    end process;

    p_shl1_cast_fu_844_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_19_fu_837_p3),9));
    p_shl_cast_fu_833_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_18_fu_826_p3),9));
    tmp_10_fu_626_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_605_p3),10));
    tmp_11_fu_630_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_8_fu_619_p3),10));
    tmp_12_fu_634_p3 <= (tmp_7_mid2_reg_944 & ap_const_lv4_0);
    tmp_13_fu_641_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_634_p3),10));
    tmp_14_fu_645_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_7_mid2_reg_944),10));
    tmp_15_fu_648_p3 <= (tmp_7_mid2_reg_944 & ap_const_lv1_0);
    tmp_16_fu_655_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_12_fu_634_p3),10));
    tmp_17_fu_659_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_15_fu_648_p3),10));
    tmp_18_fu_826_p3 <= (tmp_8_mid2_reg_951_pp0_iter3_reg & ap_const_lv4_0);
    tmp_19_fu_837_p3 <= (tmp_8_mid2_reg_951_pp0_iter3_reg & ap_const_lv1_0);
    tmp_1_fu_489_p1 <= tmp_mid2_v_fu_481_p3(4 - 1 downto 0);
    tmp_20_fu_848_p2 <= std_logic_vector(unsigned(p_shl_cast_fu_833_p1) - unsigned(p_shl1_cast_fu_844_p1));
    tmp_21_fu_663_p2 <= std_logic_vector(unsigned(tmp_5_fu_612_p1) - unsigned(tmp_7_fu_616_p1));
    tmp_22_fu_669_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_col_mid2_reg_928),10));
    tmp_23_cast_fu_726_p3 <= (tmp_23_reg_968 & ap_const_lv4_0);
    tmp_23_fu_672_p2 <= std_logic_vector(unsigned(tmp_22_fu_669_p1) + unsigned(tmp_21_fu_663_p2));
    tmp_24_cast_fu_739_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_24_fu_733_p2),64));
    tmp_24_fu_733_p2 <= std_logic_vector(unsigned(tmp_mid2_cast_fu_723_p1) + unsigned(tmp_23_cast_fu_726_p3));
    tmp_25_fu_678_p2 <= std_logic_vector(unsigned(tmp_13_fu_641_p1) - unsigned(tmp_14_fu_645_p1));
    tmp_26_fu_684_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_col_mid2_reg_928),10));
    tmp_27_cast_fu_744_p3 <= (tmp_27_reg_973 & ap_const_lv4_0);
    tmp_27_fu_687_p2 <= std_logic_vector(unsigned(tmp_26_fu_684_p1) + unsigned(tmp_25_fu_678_p2));
    tmp_28_cast_fu_757_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_28_fu_751_p2),64));
    tmp_28_fu_751_p2 <= std_logic_vector(unsigned(tmp_mid2_cast_fu_723_p1) + unsigned(tmp_27_cast_fu_744_p3));
    tmp_29_fu_693_p2 <= std_logic_vector(unsigned(tmp_10_fu_626_p1) - unsigned(tmp_11_fu_630_p1));
    tmp_2_fu_605_p3 <= (tmp_5_mid2_reg_937 & ap_const_lv4_0);
    tmp_30_fu_699_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_col_mid2_reg_928),10));
    tmp_31_cast_fu_762_p3 <= (tmp_31_reg_978 & ap_const_lv4_0);
    tmp_31_fu_702_p2 <= std_logic_vector(unsigned(tmp_30_fu_699_p1) + unsigned(tmp_29_fu_693_p2));
    tmp_32_cast_fu_775_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_32_fu_769_p2),64));
    tmp_32_fu_769_p2 <= std_logic_vector(unsigned(tmp_mid2_cast_fu_723_p1) + unsigned(tmp_31_cast_fu_762_p3));
    tmp_33_fu_708_p2 <= std_logic_vector(unsigned(tmp_16_fu_655_p1) - unsigned(tmp_17_fu_659_p1));
    tmp_34_fu_714_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(out_col_mid2_reg_928),10));
    tmp_35_cast_fu_780_p3 <= (tmp_35_reg_983 & ap_const_lv4_0);
    tmp_35_fu_717_p2 <= std_logic_vector(unsigned(tmp_34_fu_714_p1) + unsigned(tmp_33_fu_708_p2));
    tmp_36_cast_fu_793_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_36_fu_787_p2),64));
    tmp_36_fu_787_p2 <= std_logic_vector(unsigned(tmp_mid2_cast_fu_723_p1) + unsigned(tmp_35_cast_fu_780_p3));
    tmp_37_cast_fu_863_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_37_fu_857_p2),64));
    tmp_37_fu_857_p2 <= std_logic_vector(unsigned(out_col1_cast_fu_854_p1) + unsigned(tmp_20_fu_848_p2));
    tmp_3_fu_798_p2 <= "1" when (unsigned(buf_conv2_0_q0) > unsigned(buf_conv2_1_q0)) else "0";
    tmp_4_fu_812_p2 <= "1" when (unsigned(buf_conv2_0_q1) > unsigned(buf_conv2_1_q1)) else "0";
    tmp_5_fu_612_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_fu_605_p3),10));
    tmp_5_mid2_fu_555_p3 <= 
        in_row_mid1_fu_547_p3 when (exitcond_mid_fu_521_p2(0) = '1') else 
        tmp_5_mid_fu_493_p3;
    tmp_5_mid_fu_493_p3 <= 
        ap_const_lv5_0 when (exitcond_flatten_fu_467_p2(0) = '1') else 
        in_row_fu_435_p3;
    tmp_6_fu_443_p2 <= (in_row_fu_435_p3 or ap_const_lv5_1);
    tmp_6_mid1_fu_563_p2 <= (in_row_mid1_fu_547_p3 or ap_const_lv5_1);
    tmp_7_fu_616_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_5_mid2_reg_937),10));
    tmp_7_mid2_fu_569_p3 <= 
        tmp_6_mid1_fu_563_p2 when (exitcond_mid_fu_521_p2(0) = '1') else 
        tmp_7_mid_fu_501_p3;
    tmp_7_mid_fu_501_p3 <= 
        ap_const_lv5_1 when (exitcond_flatten_fu_467_p2(0) = '1') else 
        tmp_6_fu_443_p2;
    tmp_8_fu_619_p3 <= (tmp_5_mid2_reg_937 & ap_const_lv1_0);
    tmp_8_mid2_fu_577_p3 <= 
        out_row_1_fu_527_p2 when (exitcond_mid_fu_521_p2(0) = '1') else 
        out_row_mid_fu_473_p3;
    tmp_9_fu_883_p2 <= "1" when (unsigned(v0_reg_1008) > unsigned(v2_reg_1014)) else "0";
    tmp_fu_533_p2 <= (exitcond_mid_fu_521_p2 or exitcond_flatten_fu_467_p2);
    tmp_mid2_cast_fu_723_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_mid2_v_reg_918_pp0_iter1_reg),14));
    tmp_mid2_v_fu_481_p3 <= 
        ch_1_fu_461_p2 when (exitcond_flatten_fu_467_p2(0) = '1') else 
        ap_phi_mux_ch_phi_fu_395_p4;
    v0_fu_804_p3 <= 
        buf_conv2_0_q0 when (tmp_3_fu_798_p2(0) = '1') else 
        buf_conv2_1_q0;
    v2_fu_818_p3 <= 
        buf_conv2_0_q1 when (tmp_4_fu_812_p2(0) = '1') else 
        buf_conv2_1_q1;
end behav;
