// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv_layer1.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv_layer1::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv_layer1::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<5> conv_layer1::ap_ST_fsm_state1 = "1";
const sc_lv<5> conv_layer1::ap_ST_fsm_state2 = "10";
const sc_lv<5> conv_layer1::ap_ST_fsm_state3 = "100";
const sc_lv<5> conv_layer1::ap_ST_fsm_pp0_stage0 = "1000";
const sc_lv<5> conv_layer1::ap_ST_fsm_state9 = "10000";
const bool conv_layer1::ap_const_boolean_1 = true;
const sc_lv<32> conv_layer1::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv_layer1::ap_const_lv32_1 = "1";
const sc_lv<1> conv_layer1::ap_const_lv1_0 = "0";
const sc_lv<32> conv_layer1::ap_const_lv32_2 = "10";
const sc_lv<32> conv_layer1::ap_const_lv32_3 = "11";
const bool conv_layer1::ap_const_boolean_0 = false;
const sc_lv<32> conv_layer1::ap_const_lv32_4 = "100";
const sc_lv<1> conv_layer1::ap_const_lv1_1 = "1";
const sc_lv<15> conv_layer1::ap_const_lv15_0 = "000000000000000";
const sc_lv<6> conv_layer1::ap_const_lv6_0 = "000000";
const sc_lv<10> conv_layer1::ap_const_lv10_0 = "0000000000";
const sc_lv<4> conv_layer1::ap_const_lv4_0 = "0000";
const sc_lv<2> conv_layer1::ap_const_lv2_0 = "00";
const sc_lv<32> conv_layer1::ap_const_lv32_5 = "101";
const sc_lv<15> conv_layer1::ap_const_lv15_7820 = "111100000100000";
const sc_lv<15> conv_layer1::ap_const_lv15_1 = "1";
const sc_lv<10> conv_layer1::ap_const_lv10_1F0 = "111110000";
const sc_lv<5> conv_layer1::ap_const_lv5_0 = "00000";
const sc_lv<4> conv_layer1::ap_const_lv4_8 = "1000";
const sc_lv<6> conv_layer1::ap_const_lv6_1 = "1";
const sc_lv<3> conv_layer1::ap_const_lv3_0 = "000";
const sc_lv<4> conv_layer1::ap_const_lv4_9 = "1001";
const sc_lv<4> conv_layer1::ap_const_lv4_1 = "1";
const sc_lv<2> conv_layer1::ap_const_lv2_1 = "1";
const sc_lv<2> conv_layer1::ap_const_lv2_3 = "11";
const sc_lv<31> conv_layer1::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<10> conv_layer1::ap_const_lv10_1 = "1";

conv_layer1::conv_layer1(sc_module_name name) : sc_module(name), mVcdFile(0) {
    w_conv1_0_U = new conv_layer1_w_conbkb("w_conv1_0_U");
    w_conv1_0_U->clk(ap_clk);
    w_conv1_0_U->reset(ap_rst);
    w_conv1_0_U->address0(w_conv1_0_address0);
    w_conv1_0_U->ce0(w_conv1_0_ce0);
    w_conv1_0_U->q0(w_conv1_0_q0);
    w_conv1_1_U = new conv_layer1_w_concud("w_conv1_1_U");
    w_conv1_1_U->clk(ap_clk);
    w_conv1_1_U->reset(ap_rst);
    w_conv1_1_U->address0(w_conv1_1_address0);
    w_conv1_1_U->ce0(w_conv1_1_ce0);
    w_conv1_1_U->q0(w_conv1_1_q0);
    w_conv1_2_U = new conv_layer1_w_conbkb("w_conv1_2_U");
    w_conv1_2_U->clk(ap_clk);
    w_conv1_2_U->reset(ap_rst);
    w_conv1_2_U->address0(w_conv1_2_address0);
    w_conv1_2_U->ce0(w_conv1_2_ce0);
    w_conv1_2_U->q0(w_conv1_2_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state5_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state7_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter4);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state4);
    sensitive << ( exitcond_flatten_fu_504_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten6_fu_318_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_ap_phi_mux_kr_phi_fu_274_p4);
    sensitive << ( kr_reg_270 );
    sensitive << ( exitcond_flatten_reg_764 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_50_mid2_v_v_v_reg_779 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten6_fu_318_p2 );

    SC_METHOD(thread_arrayNo_trunc_mid2_fu_400_p3);
    sensitive << ( exitcond3_mid_fu_370_p2 );
    sensitive << ( tmp_78_fu_396_p1 );
    sensitive << ( arrayNo_trunc_mid_fu_350_p2 );

    SC_METHOD(thread_arrayNo_trunc_mid_fu_350_p2);
    sensitive << ( tmp_77_fu_304_p1 );
    sensitive << ( not_exitcond_flatten_fu_344_p2 );

    SC_METHOD(thread_col_3_fu_376_p2);
    sensitive << ( col_mid_fu_336_p3 );

    SC_METHOD(thread_col_mid2_fu_426_p3);
    sensitive << ( col_mid_fu_336_p3 );
    sensitive << ( exitcond3_mid_fu_370_p2 );
    sensitive << ( col_3_fu_376_p2 );

    SC_METHOD(thread_col_mid_fu_336_p3);
    sensitive << ( exitcond_flatten4_fu_330_p2 );
    sensitive << ( col_reg_237 );

    SC_METHOD(thread_exitcond3_mid_fu_370_p2);
    sensitive << ( not_exitcond_flatten_fu_344_p2 );
    sensitive << ( exitcond_fu_364_p2 );

    SC_METHOD(thread_exitcond4_fu_522_p2);
    sensitive << ( kc_reg_281 );
    sensitive << ( exitcond_flatten_fu_504_p2 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond_flatten4_fu_330_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten6_fu_318_p2 );
    sensitive << ( indvar_flatten7_reg_225 );

    SC_METHOD(thread_exitcond_flatten6_fu_318_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( indvar_flatten6_reg_202 );

    SC_METHOD(thread_exitcond_flatten_fu_504_p2);
    sensitive << ( indvar_flatten_reg_259 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );

    SC_METHOD(thread_exitcond_fu_364_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten6_fu_318_p2 );
    sensitive << ( oc_reg_248 );

    SC_METHOD(thread_indvar_flatten7_op_fu_694_p2);
    sensitive << ( indvar_flatten7_reg_225 );

    SC_METHOD(thread_indvar_flatten_next6_fu_324_p2);
    sensitive << ( indvar_flatten6_reg_202 );

    SC_METHOD(thread_indvar_flatten_next8_fu_700_p3);
    sensitive << ( exitcond_flatten4_reg_715 );
    sensitive << ( indvar_flatten7_op_fu_694_p2 );

    SC_METHOD(thread_indvar_flatten_next_fu_510_p2);
    sensitive << ( indvar_flatten_reg_259 );

    SC_METHOD(thread_input_0_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_128_fu_594_p1 );

    SC_METHOD(thread_input_0_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_input_1_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_128_fu_594_p1 );

    SC_METHOD(thread_input_1_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_input_2_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_128_fu_594_p1 );

    SC_METHOD(thread_input_2_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_kc_3_fu_544_p2);
    sensitive << ( kc_mid2_fu_528_p3 );

    SC_METHOD(thread_kc_cast3_fu_578_p1);
    sensitive << ( kc_mid2_reg_773 );

    SC_METHOD(thread_kc_mid2_fu_528_p3);
    sensitive << ( kc_reg_281 );
    sensitive << ( exitcond4_fu_522_p2 );

    SC_METHOD(thread_kr_3_fu_516_p2);
    sensitive << ( ap_phi_mux_kr_phi_fu_274_p4 );

    SC_METHOD(thread_newIndex3_mid2_cast_fu_469_p1);
    sensitive << ( newIndex3_mid2_reg_732 );

    SC_METHOD(thread_newIndex3_mid2_fu_418_p3);
    sensitive << ( exitcond3_mid_fu_370_p2 );
    sensitive << ( newIndex_mid1_fu_408_p4 );
    sensitive << ( newIndex3_mid_fu_356_p3 );

    SC_METHOD(thread_newIndex3_mid_fu_356_p3);
    sensitive << ( exitcond_flatten4_fu_330_p2 );
    sensitive << ( newIndex_fu_308_p4 );

    SC_METHOD(thread_newIndex_fu_308_p4);
    sensitive << ( col_reg_237 );

    SC_METHOD(thread_newIndex_mid1_fu_408_p4);
    sensitive << ( col_3_fu_376_p2 );

    SC_METHOD(thread_not_exitcond_flatten_fu_344_p2);
    sensitive << ( exitcond_flatten4_fu_330_p2 );

    SC_METHOD(thread_oc_4_fu_689_p2);
    sensitive << ( oc_mid2_reg_721 );

    SC_METHOD(thread_oc_mid2_fu_388_p3);
    sensitive << ( oc_reg_248 );
    sensitive << ( tmp_122_fu_382_p2 );

    SC_METHOD(thread_output_0_address0);
    sensitive << ( output_0_addr_reg_754 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_output_0_ce0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_output_0_d0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_35_fu_679_p3 );

    SC_METHOD(thread_output_0_we0);
    sensitive << ( arrayNo_trunc_mid2_reg_728 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_output_1_address0);
    sensitive << ( output_1_addr_reg_759 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_output_1_ce0);
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_output_1_d0);
    sensitive << ( ap_CS_fsm_state9 );
    sensitive << ( tmp_35_fu_679_p3 );

    SC_METHOD(thread_output_1_we0);
    sensitive << ( arrayNo_trunc_mid2_reg_728 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_p_shl2_cast_fu_568_p1);
    sensitive << ( tmp_125_fu_561_p3 );

    SC_METHOD(thread_p_shl_cast_fu_459_p1);
    sensitive << ( tmp_fu_451_p3 );

    SC_METHOD(thread_row_3_fu_434_p2);
    sensitive << ( row_reg_213 );

    SC_METHOD(thread_sum_6_2_fu_663_p2);
    sensitive << ( sum_1_reg_292 );
    sensitive << ( tmp_40_fu_658_p2 );

    SC_METHOD(thread_tmp1_fu_654_p2);
    sensitive << ( tmp_78_1_reg_857 );
    sensitive << ( tmp_78_2_reg_862 );

    SC_METHOD(thread_tmp_122_fu_382_p2);
    sensitive << ( exitcond_flatten4_fu_330_p2 );
    sensitive << ( exitcond3_mid_fu_370_p2 );

    SC_METHOD(thread_tmp_123_fu_472_p2);
    sensitive << ( newIndex3_mid2_cast_fu_469_p1 );
    sensitive << ( tmp_s_fu_463_p2 );

    SC_METHOD(thread_tmp_124_fu_492_p2);
    sensitive << ( tmp_cast_fu_489_p1 );
    sensitive << ( tmp_183_cast_fu_478_p3 );

    SC_METHOD(thread_tmp_125_fu_561_p3);
    sensitive << ( tmp_50_mid2_v_v_v_reg_779 );

    SC_METHOD(thread_tmp_126_fu_572_p2);
    sensitive << ( p_shl2_cast_fu_568_p1 );
    sensitive << ( tmp_51_mid2_cast_fu_558_p1 );

    SC_METHOD(thread_tmp_127_fu_586_p3);
    sensitive << ( tmp_50_mid2_v_fu_553_p2 );
    sensitive << ( tmp_37_fu_581_p2 );

    SC_METHOD(thread_tmp_128_fu_594_p1);
    sensitive << ( tmp_127_fu_586_p3 );

    SC_METHOD(thread_tmp_129_fu_618_p2);
    sensitive << ( tmp_cast4_reg_749 );
    sensitive << ( tmp_192_cast_fu_610_p3 );

    SC_METHOD(thread_tmp_183_cast_fu_478_p3);
    sensitive << ( tmp_123_fu_472_p2 );

    SC_METHOD(thread_tmp_184_cast_fu_498_p1);
    sensitive << ( tmp_124_fu_492_p2 );

    SC_METHOD(thread_tmp_192_cast_fu_610_p3);
    sensitive << ( tmp_81_fu_604_p2 );

    SC_METHOD(thread_tmp_193_cast_fu_623_p1);
    sensitive << ( tmp_129_fu_618_p2 );

    SC_METHOD(thread_tmp_34_fu_673_p2);
    sensitive << ( sum_1_reg_292 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_tmp_35_fu_679_p3);
    sensitive << ( tmp_34_fu_673_p2 );
    sensitive << ( tmp_79_fu_669_p1 );

    SC_METHOD(thread_tmp_37_fu_581_p2);
    sensitive << ( col_mid2_reg_737 );
    sensitive << ( kc_cast3_fu_578_p1 );

    SC_METHOD(thread_tmp_39_fu_633_p0);
    sensitive << ( w_conv1_0_load_reg_827 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_tmp_39_fu_633_p2);
    sensitive << ( input_0_load_reg_822 );
    sensitive << ( tmp_39_fu_633_p0 );

    SC_METHOD(thread_tmp_40_fu_658_p2);
    sensitive << ( tmp_39_reg_852 );
    sensitive << ( tmp1_fu_654_p2 );

    SC_METHOD(thread_tmp_50_mid2_v_fu_553_p2);
    sensitive << ( tmp_mid2_v_reg_743 );
    sensitive << ( tmp_50_mid2_v_v_fu_550_p1 );

    SC_METHOD(thread_tmp_50_mid2_v_v_fu_550_p1);
    sensitive << ( tmp_50_mid2_v_v_v_reg_779 );

    SC_METHOD(thread_tmp_50_mid2_v_v_v_fu_536_p3);
    sensitive << ( ap_phi_mux_kr_phi_fu_274_p4 );
    sensitive << ( exitcond4_fu_522_p2 );
    sensitive << ( kr_3_fu_516_p2 );

    SC_METHOD(thread_tmp_51_mid2_cast_fu_558_p1);
    sensitive << ( tmp_50_mid2_v_v_v_reg_779 );

    SC_METHOD(thread_tmp_77_fu_304_p1);
    sensitive << ( col_reg_237 );

    SC_METHOD(thread_tmp_78_1_fu_641_p0);
    sensitive << ( w_conv1_1_load_reg_837 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_tmp_78_1_fu_641_p2);
    sensitive << ( input_1_load_reg_832 );
    sensitive << ( tmp_78_1_fu_641_p0 );

    SC_METHOD(thread_tmp_78_2_fu_649_p0);
    sensitive << ( w_conv1_2_load_reg_847 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_tmp_78_2_fu_649_p2);
    sensitive << ( input_2_load_reg_842 );
    sensitive << ( tmp_78_2_fu_649_p0 );

    SC_METHOD(thread_tmp_78_fu_396_p1);
    sensitive << ( col_3_fu_376_p2 );

    SC_METHOD(thread_tmp_79_fu_669_p1);
    sensitive << ( sum_1_reg_292 );

    SC_METHOD(thread_tmp_80_fu_601_p1);
    sensitive << ( kc_mid2_reg_773 );

    SC_METHOD(thread_tmp_81_fu_604_p2);
    sensitive << ( tmp_126_fu_572_p2 );
    sensitive << ( tmp_80_fu_601_p1 );

    SC_METHOD(thread_tmp_cast4_fu_486_p1);
    sensitive << ( oc_mid2_reg_721 );

    SC_METHOD(thread_tmp_cast_fu_489_p1);
    sensitive << ( oc_mid2_reg_721 );

    SC_METHOD(thread_tmp_fu_451_p3);
    sensitive << ( tmp_mid2_v_fu_440_p3 );

    SC_METHOD(thread_tmp_mid2_cast_fu_447_p1);
    sensitive << ( tmp_mid2_v_fu_440_p3 );

    SC_METHOD(thread_tmp_mid2_v_fu_440_p3);
    sensitive << ( exitcond_flatten4_reg_715 );
    sensitive << ( row_reg_213 );
    sensitive << ( row_3_fu_434_p2 );

    SC_METHOD(thread_tmp_s_fu_463_p2);
    sensitive << ( p_shl_cast_fu_459_p1 );
    sensitive << ( tmp_mid2_cast_fu_447_p1 );

    SC_METHOD(thread_w_conv1_0_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_193_cast_fu_623_p1 );

    SC_METHOD(thread_w_conv1_0_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_w_conv1_1_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_193_cast_fu_623_p1 );

    SC_METHOD(thread_w_conv1_1_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_w_conv1_2_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_193_cast_fu_623_p1 );

    SC_METHOD(thread_w_conv1_2_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond_flatten6_fu_318_p2 );
    sensitive << ( exitcond_flatten_fu_504_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    ap_CS_fsm = "00001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv_layer1_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, input_0_address0, "(port)input_0_address0");
    sc_trace(mVcdFile, input_0_ce0, "(port)input_0_ce0");
    sc_trace(mVcdFile, input_0_q0, "(port)input_0_q0");
    sc_trace(mVcdFile, input_1_address0, "(port)input_1_address0");
    sc_trace(mVcdFile, input_1_ce0, "(port)input_1_ce0");
    sc_trace(mVcdFile, input_1_q0, "(port)input_1_q0");
    sc_trace(mVcdFile, input_2_address0, "(port)input_2_address0");
    sc_trace(mVcdFile, input_2_ce0, "(port)input_2_ce0");
    sc_trace(mVcdFile, input_2_q0, "(port)input_2_q0");
    sc_trace(mVcdFile, output_0_address0, "(port)output_0_address0");
    sc_trace(mVcdFile, output_0_ce0, "(port)output_0_ce0");
    sc_trace(mVcdFile, output_0_we0, "(port)output_0_we0");
    sc_trace(mVcdFile, output_0_d0, "(port)output_0_d0");
    sc_trace(mVcdFile, output_1_address0, "(port)output_1_address0");
    sc_trace(mVcdFile, output_1_ce0, "(port)output_1_ce0");
    sc_trace(mVcdFile, output_1_we0, "(port)output_1_we0");
    sc_trace(mVcdFile, output_1_d0, "(port)output_1_d0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, w_conv1_0_address0, "w_conv1_0_address0");
    sc_trace(mVcdFile, w_conv1_0_ce0, "w_conv1_0_ce0");
    sc_trace(mVcdFile, w_conv1_0_q0, "w_conv1_0_q0");
    sc_trace(mVcdFile, w_conv1_1_address0, "w_conv1_1_address0");
    sc_trace(mVcdFile, w_conv1_1_ce0, "w_conv1_1_ce0");
    sc_trace(mVcdFile, w_conv1_1_q0, "w_conv1_1_q0");
    sc_trace(mVcdFile, w_conv1_2_address0, "w_conv1_2_address0");
    sc_trace(mVcdFile, w_conv1_2_ce0, "w_conv1_2_ce0");
    sc_trace(mVcdFile, w_conv1_2_q0, "w_conv1_2_q0");
    sc_trace(mVcdFile, indvar_flatten_reg_259, "indvar_flatten_reg_259");
    sc_trace(mVcdFile, kr_reg_270, "kr_reg_270");
    sc_trace(mVcdFile, kc_reg_281, "kc_reg_281");
    sc_trace(mVcdFile, sum_1_reg_292, "sum_1_reg_292");
    sc_trace(mVcdFile, indvar_flatten_next6_fu_324_p2, "indvar_flatten_next6_fu_324_p2");
    sc_trace(mVcdFile, indvar_flatten_next6_reg_710, "indvar_flatten_next6_reg_710");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, exitcond_flatten4_fu_330_p2, "exitcond_flatten4_fu_330_p2");
    sc_trace(mVcdFile, exitcond_flatten4_reg_715, "exitcond_flatten4_reg_715");
    sc_trace(mVcdFile, exitcond_flatten6_fu_318_p2, "exitcond_flatten6_fu_318_p2");
    sc_trace(mVcdFile, oc_mid2_fu_388_p3, "oc_mid2_fu_388_p3");
    sc_trace(mVcdFile, oc_mid2_reg_721, "oc_mid2_reg_721");
    sc_trace(mVcdFile, arrayNo_trunc_mid2_fu_400_p3, "arrayNo_trunc_mid2_fu_400_p3");
    sc_trace(mVcdFile, arrayNo_trunc_mid2_reg_728, "arrayNo_trunc_mid2_reg_728");
    sc_trace(mVcdFile, newIndex3_mid2_fu_418_p3, "newIndex3_mid2_fu_418_p3");
    sc_trace(mVcdFile, newIndex3_mid2_reg_732, "newIndex3_mid2_reg_732");
    sc_trace(mVcdFile, col_mid2_fu_426_p3, "col_mid2_fu_426_p3");
    sc_trace(mVcdFile, col_mid2_reg_737, "col_mid2_reg_737");
    sc_trace(mVcdFile, tmp_mid2_v_fu_440_p3, "tmp_mid2_v_fu_440_p3");
    sc_trace(mVcdFile, tmp_mid2_v_reg_743, "tmp_mid2_v_reg_743");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_cast4_fu_486_p1, "tmp_cast4_fu_486_p1");
    sc_trace(mVcdFile, tmp_cast4_reg_749, "tmp_cast4_reg_749");
    sc_trace(mVcdFile, output_0_addr_reg_754, "output_0_addr_reg_754");
    sc_trace(mVcdFile, output_1_addr_reg_759, "output_1_addr_reg_759");
    sc_trace(mVcdFile, exitcond_flatten_fu_504_p2, "exitcond_flatten_fu_504_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_764, "exitcond_flatten_reg_764");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter0, "ap_block_state4_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage0_iter1, "ap_block_state5_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter2, "ap_block_state6_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage0_iter3, "ap_block_state7_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter4, "ap_block_state8_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond_flatten_reg_764_pp0_iter1_reg, "exitcond_flatten_reg_764_pp0_iter1_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_764_pp0_iter2_reg, "exitcond_flatten_reg_764_pp0_iter2_reg");
    sc_trace(mVcdFile, exitcond_flatten_reg_764_pp0_iter3_reg, "exitcond_flatten_reg_764_pp0_iter3_reg");
    sc_trace(mVcdFile, indvar_flatten_next_fu_510_p2, "indvar_flatten_next_fu_510_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, kc_mid2_fu_528_p3, "kc_mid2_fu_528_p3");
    sc_trace(mVcdFile, kc_mid2_reg_773, "kc_mid2_reg_773");
    sc_trace(mVcdFile, tmp_50_mid2_v_v_v_fu_536_p3, "tmp_50_mid2_v_v_v_fu_536_p3");
    sc_trace(mVcdFile, tmp_50_mid2_v_v_v_reg_779, "tmp_50_mid2_v_v_v_reg_779");
    sc_trace(mVcdFile, kc_3_fu_544_p2, "kc_3_fu_544_p2");
    sc_trace(mVcdFile, input_0_load_reg_822, "input_0_load_reg_822");
    sc_trace(mVcdFile, w_conv1_0_load_reg_827, "w_conv1_0_load_reg_827");
    sc_trace(mVcdFile, input_1_load_reg_832, "input_1_load_reg_832");
    sc_trace(mVcdFile, w_conv1_1_load_reg_837, "w_conv1_1_load_reg_837");
    sc_trace(mVcdFile, input_2_load_reg_842, "input_2_load_reg_842");
    sc_trace(mVcdFile, w_conv1_2_load_reg_847, "w_conv1_2_load_reg_847");
    sc_trace(mVcdFile, tmp_39_fu_633_p2, "tmp_39_fu_633_p2");
    sc_trace(mVcdFile, tmp_39_reg_852, "tmp_39_reg_852");
    sc_trace(mVcdFile, tmp_78_1_fu_641_p2, "tmp_78_1_fu_641_p2");
    sc_trace(mVcdFile, tmp_78_1_reg_857, "tmp_78_1_reg_857");
    sc_trace(mVcdFile, tmp_78_2_fu_649_p2, "tmp_78_2_fu_649_p2");
    sc_trace(mVcdFile, tmp_78_2_reg_862, "tmp_78_2_reg_862");
    sc_trace(mVcdFile, sum_6_2_fu_663_p2, "sum_6_2_fu_663_p2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, oc_4_fu_689_p2, "oc_4_fu_689_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, indvar_flatten_next8_fu_700_p3, "indvar_flatten_next8_fu_700_p3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state4, "ap_condition_pp0_exit_iter0_state4");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, indvar_flatten6_reg_202, "indvar_flatten6_reg_202");
    sc_trace(mVcdFile, row_reg_213, "row_reg_213");
    sc_trace(mVcdFile, indvar_flatten7_reg_225, "indvar_flatten7_reg_225");
    sc_trace(mVcdFile, col_reg_237, "col_reg_237");
    sc_trace(mVcdFile, oc_reg_248, "oc_reg_248");
    sc_trace(mVcdFile, ap_phi_mux_kr_phi_fu_274_p4, "ap_phi_mux_kr_phi_fu_274_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, tmp_184_cast_fu_498_p1, "tmp_184_cast_fu_498_p1");
    sc_trace(mVcdFile, tmp_128_fu_594_p1, "tmp_128_fu_594_p1");
    sc_trace(mVcdFile, tmp_193_cast_fu_623_p1, "tmp_193_cast_fu_623_p1");
    sc_trace(mVcdFile, tmp_35_fu_679_p3, "tmp_35_fu_679_p3");
    sc_trace(mVcdFile, tmp_77_fu_304_p1, "tmp_77_fu_304_p1");
    sc_trace(mVcdFile, not_exitcond_flatten_fu_344_p2, "not_exitcond_flatten_fu_344_p2");
    sc_trace(mVcdFile, newIndex_fu_308_p4, "newIndex_fu_308_p4");
    sc_trace(mVcdFile, exitcond_fu_364_p2, "exitcond_fu_364_p2");
    sc_trace(mVcdFile, col_mid_fu_336_p3, "col_mid_fu_336_p3");
    sc_trace(mVcdFile, exitcond3_mid_fu_370_p2, "exitcond3_mid_fu_370_p2");
    sc_trace(mVcdFile, tmp_122_fu_382_p2, "tmp_122_fu_382_p2");
    sc_trace(mVcdFile, col_3_fu_376_p2, "col_3_fu_376_p2");
    sc_trace(mVcdFile, tmp_78_fu_396_p1, "tmp_78_fu_396_p1");
    sc_trace(mVcdFile, arrayNo_trunc_mid_fu_350_p2, "arrayNo_trunc_mid_fu_350_p2");
    sc_trace(mVcdFile, newIndex_mid1_fu_408_p4, "newIndex_mid1_fu_408_p4");
    sc_trace(mVcdFile, newIndex3_mid_fu_356_p3, "newIndex3_mid_fu_356_p3");
    sc_trace(mVcdFile, row_3_fu_434_p2, "row_3_fu_434_p2");
    sc_trace(mVcdFile, tmp_fu_451_p3, "tmp_fu_451_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_459_p1, "p_shl_cast_fu_459_p1");
    sc_trace(mVcdFile, tmp_mid2_cast_fu_447_p1, "tmp_mid2_cast_fu_447_p1");
    sc_trace(mVcdFile, newIndex3_mid2_cast_fu_469_p1, "newIndex3_mid2_cast_fu_469_p1");
    sc_trace(mVcdFile, tmp_s_fu_463_p2, "tmp_s_fu_463_p2");
    sc_trace(mVcdFile, tmp_123_fu_472_p2, "tmp_123_fu_472_p2");
    sc_trace(mVcdFile, tmp_cast_fu_489_p1, "tmp_cast_fu_489_p1");
    sc_trace(mVcdFile, tmp_183_cast_fu_478_p3, "tmp_183_cast_fu_478_p3");
    sc_trace(mVcdFile, tmp_124_fu_492_p2, "tmp_124_fu_492_p2");
    sc_trace(mVcdFile, exitcond4_fu_522_p2, "exitcond4_fu_522_p2");
    sc_trace(mVcdFile, kr_3_fu_516_p2, "kr_3_fu_516_p2");
    sc_trace(mVcdFile, tmp_50_mid2_v_v_fu_550_p1, "tmp_50_mid2_v_v_fu_550_p1");
    sc_trace(mVcdFile, tmp_125_fu_561_p3, "tmp_125_fu_561_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_568_p1, "p_shl2_cast_fu_568_p1");
    sc_trace(mVcdFile, tmp_51_mid2_cast_fu_558_p1, "tmp_51_mid2_cast_fu_558_p1");
    sc_trace(mVcdFile, kc_cast3_fu_578_p1, "kc_cast3_fu_578_p1");
    sc_trace(mVcdFile, tmp_50_mid2_v_fu_553_p2, "tmp_50_mid2_v_fu_553_p2");
    sc_trace(mVcdFile, tmp_37_fu_581_p2, "tmp_37_fu_581_p2");
    sc_trace(mVcdFile, tmp_127_fu_586_p3, "tmp_127_fu_586_p3");
    sc_trace(mVcdFile, tmp_126_fu_572_p2, "tmp_126_fu_572_p2");
    sc_trace(mVcdFile, tmp_80_fu_601_p1, "tmp_80_fu_601_p1");
    sc_trace(mVcdFile, tmp_81_fu_604_p2, "tmp_81_fu_604_p2");
    sc_trace(mVcdFile, tmp_192_cast_fu_610_p3, "tmp_192_cast_fu_610_p3");
    sc_trace(mVcdFile, tmp_129_fu_618_p2, "tmp_129_fu_618_p2");
    sc_trace(mVcdFile, tmp_39_fu_633_p0, "tmp_39_fu_633_p0");
    sc_trace(mVcdFile, tmp_78_1_fu_641_p0, "tmp_78_1_fu_641_p0");
    sc_trace(mVcdFile, tmp_78_2_fu_649_p0, "tmp_78_2_fu_649_p0");
    sc_trace(mVcdFile, tmp1_fu_654_p2, "tmp1_fu_654_p2");
    sc_trace(mVcdFile, tmp_40_fu_658_p2, "tmp_40_fu_658_p2");
    sc_trace(mVcdFile, tmp_34_fu_673_p2, "tmp_34_fu_673_p2");
    sc_trace(mVcdFile, tmp_79_fu_669_p1, "tmp_79_fu_669_p1");
    sc_trace(mVcdFile, indvar_flatten7_op_fu_694_p2, "indvar_flatten7_op_fu_694_p2");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
#endif

    }
}

conv_layer1::~conv_layer1() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete w_conv1_0_U;
    delete w_conv1_1_U;
    delete w_conv1_2_U;
}

void conv_layer1::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            if (esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state4.read())) {
                ap_enable_reg_pp0_iter1 = (ap_condition_pp0_exit_iter0_state4.read() ^ ap_const_logic_1);
            } else if (esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1)) {
                ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
            }
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0)) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
            ap_enable_reg_pp0_iter4 = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        col_reg_237 = col_mid2_reg_737.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        col_reg_237 = ap_const_lv6_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        indvar_flatten6_reg_202 = indvar_flatten_next6_reg_710.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten6_reg_202 = ap_const_lv15_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        indvar_flatten7_reg_225 = indvar_flatten_next8_fu_700_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten7_reg_225 = ap_const_lv10_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_504_p2.read()))) {
        indvar_flatten_reg_259 = indvar_flatten_next_fu_510_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        indvar_flatten_reg_259 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_504_p2.read()))) {
        kc_reg_281 = kc_3_fu_544_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        kc_reg_281 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_764.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        kr_reg_270 = tmp_50_mid2_v_v_v_reg_779.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        kr_reg_270 = ap_const_lv2_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        oc_reg_248 = oc_4_fu_689_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        oc_reg_248 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        row_reg_213 = tmp_mid2_v_reg_743.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        row_reg_213 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_764_pp0_iter3_reg.read()))) {
        sum_1_reg_292 = sum_6_2_fu_663_p2.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        sum_1_reg_292 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_flatten6_fu_318_p2.read(), ap_const_lv1_0))) {
        arrayNo_trunc_mid2_reg_728 = arrayNo_trunc_mid2_fu_400_p3.read();
        col_mid2_reg_737 = col_mid2_fu_426_p3.read();
        exitcond_flatten4_reg_715 = exitcond_flatten4_fu_330_p2.read();
        newIndex3_mid2_reg_732 = newIndex3_mid2_fu_418_p3.read();
        oc_mid2_reg_721 = oc_mid2_fu_388_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_flatten_reg_764 = exitcond_flatten_fu_504_p2.read();
        exitcond_flatten_reg_764_pp0_iter1_reg = exitcond_flatten_reg_764.read();
    }
    if (esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) {
        exitcond_flatten_reg_764_pp0_iter2_reg = exitcond_flatten_reg_764_pp0_iter1_reg.read();
        exitcond_flatten_reg_764_pp0_iter3_reg = exitcond_flatten_reg_764_pp0_iter2_reg.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        indvar_flatten_next6_reg_710 = indvar_flatten_next6_fu_324_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_764_pp0_iter1_reg.read()))) {
        input_0_load_reg_822 = input_0_q0.read();
        input_1_load_reg_832 = input_1_q0.read();
        input_2_load_reg_842 = input_2_q0.read();
        w_conv1_0_load_reg_827 = w_conv1_0_q0.read();
        w_conv1_1_load_reg_837 = w_conv1_1_q0.read();
        w_conv1_2_load_reg_847 = w_conv1_2_q0.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_504_p2.read()))) {
        kc_mid2_reg_773 = kc_mid2_fu_528_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        output_0_addr_reg_754 =  (sc_lv<14>) (tmp_184_cast_fu_498_p1.read());
        output_1_addr_reg_759 =  (sc_lv<14>) (tmp_184_cast_fu_498_p1.read());
        tmp_cast4_reg_749 = tmp_cast4_fu_486_p1.read();
        tmp_mid2_v_reg_743 = tmp_mid2_v_fu_440_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_764_pp0_iter2_reg.read()))) {
        tmp_39_reg_852 = tmp_39_fu_633_p2.read();
        tmp_78_1_reg_857 = tmp_78_1_fu_641_p2.read();
        tmp_78_2_reg_862 = tmp_78_2_fu_649_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_504_p2.read()))) {
        tmp_50_mid2_v_v_v_reg_779 = tmp_50_mid2_v_v_v_fu_536_p3.read();
    }
}

void conv_layer1::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[3];
}

void conv_layer1::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv_layer1::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv_layer1::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv_layer1::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[4];
}

void conv_layer1::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_layer1::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_layer1::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_layer1::thread_ap_block_state4_pp0_stage0_iter0() {
    ap_block_state4_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_layer1::thread_ap_block_state5_pp0_stage0_iter1() {
    ap_block_state5_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_layer1::thread_ap_block_state6_pp0_stage0_iter2() {
    ap_block_state6_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_layer1::thread_ap_block_state7_pp0_stage0_iter3() {
    ap_block_state7_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_layer1::thread_ap_block_state8_pp0_stage0_iter4() {
    ap_block_state8_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void conv_layer1::thread_ap_condition_pp0_exit_iter0_state4() {
    if (esl_seteq<1,1,1>(exitcond_flatten_fu_504_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state4 = ap_const_logic_0;
    }
}

void conv_layer1::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond_flatten6_fu_318_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv_layer1::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void conv_layer1::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv_layer1::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void conv_layer1::thread_ap_phi_mux_kr_phi_fu_274_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_764.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_kr_phi_fu_274_p4 = tmp_50_mid2_v_v_v_reg_779.read();
    } else {
        ap_phi_mux_kr_phi_fu_274_p4 = kr_reg_270.read();
    }
}

void conv_layer1::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten6_fu_318_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv_layer1::thread_arrayNo_trunc_mid2_fu_400_p3() {
    arrayNo_trunc_mid2_fu_400_p3 = (!exitcond3_mid_fu_370_p2.read()[0].is_01())? sc_lv<1>(): ((exitcond3_mid_fu_370_p2.read()[0].to_bool())? tmp_78_fu_396_p1.read(): arrayNo_trunc_mid_fu_350_p2.read());
}

void conv_layer1::thread_arrayNo_trunc_mid_fu_350_p2() {
    arrayNo_trunc_mid_fu_350_p2 = (tmp_77_fu_304_p1.read() & not_exitcond_flatten_fu_344_p2.read());
}

void conv_layer1::thread_col_3_fu_376_p2() {
    col_3_fu_376_p2 = (!ap_const_lv6_1.is_01() || !col_mid_fu_336_p3.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1) + sc_biguint<6>(col_mid_fu_336_p3.read()));
}

void conv_layer1::thread_col_mid2_fu_426_p3() {
    col_mid2_fu_426_p3 = (!exitcond3_mid_fu_370_p2.read()[0].is_01())? sc_lv<6>(): ((exitcond3_mid_fu_370_p2.read()[0].to_bool())? col_3_fu_376_p2.read(): col_mid_fu_336_p3.read());
}

void conv_layer1::thread_col_mid_fu_336_p3() {
    col_mid_fu_336_p3 = (!exitcond_flatten4_fu_330_p2.read()[0].is_01())? sc_lv<6>(): ((exitcond_flatten4_fu_330_p2.read()[0].to_bool())? ap_const_lv6_0: col_reg_237.read());
}

void conv_layer1::thread_exitcond3_mid_fu_370_p2() {
    exitcond3_mid_fu_370_p2 = (exitcond_fu_364_p2.read() & not_exitcond_flatten_fu_344_p2.read());
}

void conv_layer1::thread_exitcond4_fu_522_p2() {
    exitcond4_fu_522_p2 = (!kc_reg_281.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(kc_reg_281.read() == ap_const_lv2_3);
}

void conv_layer1::thread_exitcond_flatten4_fu_330_p2() {
    exitcond_flatten4_fu_330_p2 = (!indvar_flatten7_reg_225.read().is_01() || !ap_const_lv10_1F0.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten7_reg_225.read() == ap_const_lv10_1F0);
}

void conv_layer1::thread_exitcond_flatten6_fu_318_p2() {
    exitcond_flatten6_fu_318_p2 = (!indvar_flatten6_reg_202.read().is_01() || !ap_const_lv15_7820.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten6_reg_202.read() == ap_const_lv15_7820);
}

void conv_layer1::thread_exitcond_flatten_fu_504_p2() {
    exitcond_flatten_fu_504_p2 = (!indvar_flatten_reg_259.read().is_01() || !ap_const_lv4_9.is_01())? sc_lv<1>(): sc_lv<1>(indvar_flatten_reg_259.read() == ap_const_lv4_9);
}

void conv_layer1::thread_exitcond_fu_364_p2() {
    exitcond_fu_364_p2 = (!oc_reg_248.read().is_01() || !ap_const_lv4_8.is_01())? sc_lv<1>(): sc_lv<1>(oc_reg_248.read() == ap_const_lv4_8);
}

void conv_layer1::thread_indvar_flatten7_op_fu_694_p2() {
    indvar_flatten7_op_fu_694_p2 = (!indvar_flatten7_reg_225.read().is_01() || !ap_const_lv10_1.is_01())? sc_lv<10>(): (sc_biguint<10>(indvar_flatten7_reg_225.read()) + sc_biguint<10>(ap_const_lv10_1));
}

void conv_layer1::thread_indvar_flatten_next6_fu_324_p2() {
    indvar_flatten_next6_fu_324_p2 = (!ap_const_lv15_1.is_01() || !indvar_flatten6_reg_202.read().is_01())? sc_lv<15>(): (sc_biguint<15>(ap_const_lv15_1) + sc_biguint<15>(indvar_flatten6_reg_202.read()));
}

void conv_layer1::thread_indvar_flatten_next8_fu_700_p3() {
    indvar_flatten_next8_fu_700_p3 = (!exitcond_flatten4_reg_715.read()[0].is_01())? sc_lv<10>(): ((exitcond_flatten4_reg_715.read()[0].to_bool())? ap_const_lv10_1: indvar_flatten7_op_fu_694_p2.read());
}

void conv_layer1::thread_indvar_flatten_next_fu_510_p2() {
    indvar_flatten_next_fu_510_p2 = (!indvar_flatten_reg_259.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(indvar_flatten_reg_259.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv_layer1::thread_input_0_address0() {
    input_0_address0 =  (sc_lv<12>) (tmp_128_fu_594_p1.read());
}

void conv_layer1::thread_input_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        input_0_ce0 = ap_const_logic_1;
    } else {
        input_0_ce0 = ap_const_logic_0;
    }
}

void conv_layer1::thread_input_1_address0() {
    input_1_address0 =  (sc_lv<12>) (tmp_128_fu_594_p1.read());
}

void conv_layer1::thread_input_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        input_1_ce0 = ap_const_logic_1;
    } else {
        input_1_ce0 = ap_const_logic_0;
    }
}

void conv_layer1::thread_input_2_address0() {
    input_2_address0 =  (sc_lv<12>) (tmp_128_fu_594_p1.read());
}

void conv_layer1::thread_input_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        input_2_ce0 = ap_const_logic_1;
    } else {
        input_2_ce0 = ap_const_logic_0;
    }
}

void conv_layer1::thread_kc_3_fu_544_p2() {
    kc_3_fu_544_p2 = (!kc_mid2_fu_528_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(kc_mid2_fu_528_p3.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_layer1::thread_kc_cast3_fu_578_p1() {
    kc_cast3_fu_578_p1 = esl_zext<6,2>(kc_mid2_reg_773.read());
}

void conv_layer1::thread_kc_mid2_fu_528_p3() {
    kc_mid2_fu_528_p3 = (!exitcond4_fu_522_p2.read()[0].is_01())? sc_lv<2>(): ((exitcond4_fu_522_p2.read()[0].to_bool())? ap_const_lv2_0: kc_reg_281.read());
}

void conv_layer1::thread_kr_3_fu_516_p2() {
    kr_3_fu_516_p2 = (!ap_phi_mux_kr_phi_fu_274_p4.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(ap_phi_mux_kr_phi_fu_274_p4.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_layer1::thread_newIndex3_mid2_cast_fu_469_p1() {
    newIndex3_mid2_cast_fu_469_p1 = esl_zext<12,5>(newIndex3_mid2_reg_732.read());
}

void conv_layer1::thread_newIndex3_mid2_fu_418_p3() {
    newIndex3_mid2_fu_418_p3 = (!exitcond3_mid_fu_370_p2.read()[0].is_01())? sc_lv<5>(): ((exitcond3_mid_fu_370_p2.read()[0].to_bool())? newIndex_mid1_fu_408_p4.read(): newIndex3_mid_fu_356_p3.read());
}

void conv_layer1::thread_newIndex3_mid_fu_356_p3() {
    newIndex3_mid_fu_356_p3 = (!exitcond_flatten4_fu_330_p2.read()[0].is_01())? sc_lv<5>(): ((exitcond_flatten4_fu_330_p2.read()[0].to_bool())? ap_const_lv5_0: newIndex_fu_308_p4.read());
}

void conv_layer1::thread_newIndex_fu_308_p4() {
    newIndex_fu_308_p4 = col_reg_237.read().range(5, 1);
}

void conv_layer1::thread_newIndex_mid1_fu_408_p4() {
    newIndex_mid1_fu_408_p4 = col_3_fu_376_p2.read().range(5, 1);
}

void conv_layer1::thread_not_exitcond_flatten_fu_344_p2() {
    not_exitcond_flatten_fu_344_p2 = (exitcond_flatten4_fu_330_p2.read() ^ ap_const_lv1_1);
}

void conv_layer1::thread_oc_4_fu_689_p2() {
    oc_4_fu_689_p2 = (!oc_mid2_reg_721.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(oc_mid2_reg_721.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv_layer1::thread_oc_mid2_fu_388_p3() {
    oc_mid2_fu_388_p3 = (!tmp_122_fu_382_p2.read()[0].is_01())? sc_lv<4>(): ((tmp_122_fu_382_p2.read()[0].to_bool())? ap_const_lv4_0: oc_reg_248.read());
}

void conv_layer1::thread_output_0_address0() {
    output_0_address0 = output_0_addr_reg_754.read();
}

void conv_layer1::thread_output_0_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        output_0_ce0 = ap_const_logic_1;
    } else {
        output_0_ce0 = ap_const_logic_0;
    }
}

void conv_layer1::thread_output_0_d0() {
    output_0_d0 = tmp_35_fu_679_p3.read();
}

void conv_layer1::thread_output_0_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, arrayNo_trunc_mid2_reg_728.read()))) {
        output_0_we0 = ap_const_logic_1;
    } else {
        output_0_we0 = ap_const_logic_0;
    }
}

void conv_layer1::thread_output_1_address0() {
    output_1_address0 = output_1_addr_reg_759.read();
}

void conv_layer1::thread_output_1_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        output_1_ce0 = ap_const_logic_1;
    } else {
        output_1_ce0 = ap_const_logic_0;
    }
}

void conv_layer1::thread_output_1_d0() {
    output_1_d0 = tmp_35_fu_679_p3.read();
}

void conv_layer1::thread_output_1_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read()) && 
         esl_seteq<1,1,1>(arrayNo_trunc_mid2_reg_728.read(), ap_const_lv1_1))) {
        output_1_we0 = ap_const_logic_1;
    } else {
        output_1_we0 = ap_const_logic_0;
    }
}

void conv_layer1::thread_p_shl2_cast_fu_568_p1() {
    p_shl2_cast_fu_568_p1 = esl_zext<5,4>(tmp_125_fu_561_p3.read());
}

void conv_layer1::thread_p_shl_cast_fu_459_p1() {
    p_shl_cast_fu_459_p1 = esl_zext<12,11>(tmp_fu_451_p3.read());
}

void conv_layer1::thread_row_3_fu_434_p2() {
    row_3_fu_434_p2 = (!ap_const_lv6_1.is_01() || !row_reg_213.read().is_01())? sc_lv<6>(): (sc_biguint<6>(ap_const_lv6_1) + sc_biguint<6>(row_reg_213.read()));
}

void conv_layer1::thread_sum_6_2_fu_663_p2() {
    sum_6_2_fu_663_p2 = (!tmp_40_fu_658_p2.read().is_01() || !sum_1_reg_292.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_40_fu_658_p2.read()) + sc_biguint<32>(sum_1_reg_292.read()));
}

void conv_layer1::thread_tmp1_fu_654_p2() {
    tmp1_fu_654_p2 = (!tmp_78_2_reg_862.read().is_01() || !tmp_78_1_reg_857.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_78_2_reg_862.read()) + sc_biguint<32>(tmp_78_1_reg_857.read()));
}

void conv_layer1::thread_tmp_122_fu_382_p2() {
    tmp_122_fu_382_p2 = (exitcond3_mid_fu_370_p2.read() | exitcond_flatten4_fu_330_p2.read());
}

void conv_layer1::thread_tmp_123_fu_472_p2() {
    tmp_123_fu_472_p2 = (!newIndex3_mid2_cast_fu_469_p1.read().is_01() || !tmp_s_fu_463_p2.read().is_01())? sc_lv<12>(): (sc_biguint<12>(newIndex3_mid2_cast_fu_469_p1.read()) + sc_biguint<12>(tmp_s_fu_463_p2.read()));
}

void conv_layer1::thread_tmp_124_fu_492_p2() {
    tmp_124_fu_492_p2 = (!tmp_cast_fu_489_p1.read().is_01() || !tmp_183_cast_fu_478_p3.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_cast_fu_489_p1.read()) + sc_biguint<15>(tmp_183_cast_fu_478_p3.read()));
}

void conv_layer1::thread_tmp_125_fu_561_p3() {
    tmp_125_fu_561_p3 = esl_concat<2,2>(tmp_50_mid2_v_v_v_reg_779.read(), ap_const_lv2_0);
}

void conv_layer1::thread_tmp_126_fu_572_p2() {
    tmp_126_fu_572_p2 = (!p_shl2_cast_fu_568_p1.read().is_01() || !tmp_51_mid2_cast_fu_558_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl2_cast_fu_568_p1.read()) - sc_biguint<5>(tmp_51_mid2_cast_fu_558_p1.read()));
}

void conv_layer1::thread_tmp_127_fu_586_p3() {
    tmp_127_fu_586_p3 = esl_concat<6,6>(tmp_50_mid2_v_fu_553_p2.read(), tmp_37_fu_581_p2.read());
}

void conv_layer1::thread_tmp_128_fu_594_p1() {
    tmp_128_fu_594_p1 = esl_zext<64,12>(tmp_127_fu_586_p3.read());
}

void conv_layer1::thread_tmp_129_fu_618_p2() {
    tmp_129_fu_618_p2 = (!tmp_192_cast_fu_610_p3.read().is_01() || !tmp_cast4_reg_749.read().is_01())? sc_lv<8>(): (sc_biguint<8>(tmp_192_cast_fu_610_p3.read()) + sc_biguint<8>(tmp_cast4_reg_749.read()));
}

void conv_layer1::thread_tmp_183_cast_fu_478_p3() {
    tmp_183_cast_fu_478_p3 = esl_concat<12,3>(tmp_123_fu_472_p2.read(), ap_const_lv3_0);
}

void conv_layer1::thread_tmp_184_cast_fu_498_p1() {
    tmp_184_cast_fu_498_p1 = esl_zext<64,15>(tmp_124_fu_492_p2.read());
}

void conv_layer1::thread_tmp_192_cast_fu_610_p3() {
    tmp_192_cast_fu_610_p3 = esl_concat<5,3>(tmp_81_fu_604_p2.read(), ap_const_lv3_0);
}

void conv_layer1::thread_tmp_193_cast_fu_623_p1() {
    tmp_193_cast_fu_623_p1 = esl_zext<64,8>(tmp_129_fu_618_p2.read());
}

void conv_layer1::thread_tmp_34_fu_673_p2() {
    tmp_34_fu_673_p2 = (!sum_1_reg_292.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(sum_1_reg_292.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void conv_layer1::thread_tmp_35_fu_679_p3() {
    tmp_35_fu_679_p3 = (!tmp_34_fu_673_p2.read()[0].is_01())? sc_lv<31>(): ((tmp_34_fu_673_p2.read()[0].to_bool())? tmp_79_fu_669_p1.read(): ap_const_lv31_0);
}

void conv_layer1::thread_tmp_37_fu_581_p2() {
    tmp_37_fu_581_p2 = (!kc_cast3_fu_578_p1.read().is_01() || !col_mid2_reg_737.read().is_01())? sc_lv<6>(): (sc_biguint<6>(kc_cast3_fu_578_p1.read()) + sc_biguint<6>(col_mid2_reg_737.read()));
}

void conv_layer1::thread_tmp_39_fu_633_p0() {
    tmp_39_fu_633_p0 = w_conv1_0_load_reg_827.read();
}

void conv_layer1::thread_tmp_39_fu_633_p2() {
    tmp_39_fu_633_p2 = (!tmp_39_fu_633_p0.read().is_01() || !input_0_load_reg_822.read().is_01())? sc_lv<32>(): sc_bigint<4>(tmp_39_fu_633_p0.read()) * sc_bigint<32>(input_0_load_reg_822.read());
}

void conv_layer1::thread_tmp_40_fu_658_p2() {
    tmp_40_fu_658_p2 = (!tmp_39_reg_852.read().is_01() || !tmp1_fu_654_p2.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_39_reg_852.read()) + sc_biguint<32>(tmp1_fu_654_p2.read()));
}

void conv_layer1::thread_tmp_50_mid2_v_fu_553_p2() {
    tmp_50_mid2_v_fu_553_p2 = (!tmp_50_mid2_v_v_fu_550_p1.read().is_01() || !tmp_mid2_v_reg_743.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_50_mid2_v_v_fu_550_p1.read()) + sc_biguint<6>(tmp_mid2_v_reg_743.read()));
}

void conv_layer1::thread_tmp_50_mid2_v_v_fu_550_p1() {
    tmp_50_mid2_v_v_fu_550_p1 = esl_zext<6,2>(tmp_50_mid2_v_v_v_reg_779.read());
}

void conv_layer1::thread_tmp_50_mid2_v_v_v_fu_536_p3() {
    tmp_50_mid2_v_v_v_fu_536_p3 = (!exitcond4_fu_522_p2.read()[0].is_01())? sc_lv<2>(): ((exitcond4_fu_522_p2.read()[0].to_bool())? kr_3_fu_516_p2.read(): ap_phi_mux_kr_phi_fu_274_p4.read());
}

void conv_layer1::thread_tmp_51_mid2_cast_fu_558_p1() {
    tmp_51_mid2_cast_fu_558_p1 = esl_zext<5,2>(tmp_50_mid2_v_v_v_reg_779.read());
}

void conv_layer1::thread_tmp_77_fu_304_p1() {
    tmp_77_fu_304_p1 = col_reg_237.read().range(1-1, 0);
}

void conv_layer1::thread_tmp_78_1_fu_641_p0() {
    tmp_78_1_fu_641_p0 = w_conv1_1_load_reg_837.read();
}

void conv_layer1::thread_tmp_78_1_fu_641_p2() {
    tmp_78_1_fu_641_p2 = (!tmp_78_1_fu_641_p0.read().is_01() || !input_1_load_reg_832.read().is_01())? sc_lv<32>(): sc_bigint<4>(tmp_78_1_fu_641_p0.read()) * sc_bigint<32>(input_1_load_reg_832.read());
}

void conv_layer1::thread_tmp_78_2_fu_649_p0() {
    tmp_78_2_fu_649_p0 = w_conv1_2_load_reg_847.read();
}

void conv_layer1::thread_tmp_78_2_fu_649_p2() {
    tmp_78_2_fu_649_p2 = (!tmp_78_2_fu_649_p0.read().is_01() || !input_2_load_reg_842.read().is_01())? sc_lv<32>(): sc_bigint<4>(tmp_78_2_fu_649_p0.read()) * sc_bigint<32>(input_2_load_reg_842.read());
}

void conv_layer1::thread_tmp_78_fu_396_p1() {
    tmp_78_fu_396_p1 = col_3_fu_376_p2.read().range(1-1, 0);
}

void conv_layer1::thread_tmp_79_fu_669_p1() {
    tmp_79_fu_669_p1 = sum_1_reg_292.read().range(31-1, 0);
}

void conv_layer1::thread_tmp_80_fu_601_p1() {
    tmp_80_fu_601_p1 = esl_zext<5,2>(kc_mid2_reg_773.read());
}

void conv_layer1::thread_tmp_81_fu_604_p2() {
    tmp_81_fu_604_p2 = (!tmp_126_fu_572_p2.read().is_01() || !tmp_80_fu_601_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(tmp_126_fu_572_p2.read()) + sc_biguint<5>(tmp_80_fu_601_p1.read()));
}

void conv_layer1::thread_tmp_cast4_fu_486_p1() {
    tmp_cast4_fu_486_p1 = esl_zext<8,4>(oc_mid2_reg_721.read());
}

void conv_layer1::thread_tmp_cast_fu_489_p1() {
    tmp_cast_fu_489_p1 = esl_zext<15,4>(oc_mid2_reg_721.read());
}

void conv_layer1::thread_tmp_fu_451_p3() {
    tmp_fu_451_p3 = esl_concat<6,5>(tmp_mid2_v_fu_440_p3.read(), ap_const_lv5_0);
}

void conv_layer1::thread_tmp_mid2_cast_fu_447_p1() {
    tmp_mid2_cast_fu_447_p1 = esl_zext<12,6>(tmp_mid2_v_fu_440_p3.read());
}

void conv_layer1::thread_tmp_mid2_v_fu_440_p3() {
    tmp_mid2_v_fu_440_p3 = (!exitcond_flatten4_reg_715.read()[0].is_01())? sc_lv<6>(): ((exitcond_flatten4_reg_715.read()[0].to_bool())? row_3_fu_434_p2.read(): row_reg_213.read());
}

void conv_layer1::thread_tmp_s_fu_463_p2() {
    tmp_s_fu_463_p2 = (!p_shl_cast_fu_459_p1.read().is_01() || !tmp_mid2_cast_fu_447_p1.read().is_01())? sc_lv<12>(): (sc_biguint<12>(p_shl_cast_fu_459_p1.read()) - sc_biguint<12>(tmp_mid2_cast_fu_447_p1.read()));
}

void conv_layer1::thread_w_conv1_0_address0() {
    w_conv1_0_address0 =  (sc_lv<7>) (tmp_193_cast_fu_623_p1.read());
}

void conv_layer1::thread_w_conv1_0_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        w_conv1_0_ce0 = ap_const_logic_1;
    } else {
        w_conv1_0_ce0 = ap_const_logic_0;
    }
}

void conv_layer1::thread_w_conv1_1_address0() {
    w_conv1_1_address0 =  (sc_lv<7>) (tmp_193_cast_fu_623_p1.read());
}

void conv_layer1::thread_w_conv1_1_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        w_conv1_1_ce0 = ap_const_logic_1;
    } else {
        w_conv1_1_ce0 = ap_const_logic_0;
    }
}

void conv_layer1::thread_w_conv1_2_address0() {
    w_conv1_2_address0 =  (sc_lv<7>) (tmp_193_cast_fu_623_p1.read());
}

void conv_layer1::thread_w_conv1_2_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        w_conv1_2_ce0 = ap_const_logic_1;
    } else {
        w_conv1_2_ce0 = ap_const_logic_0;
    }
}

void conv_layer1::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond_flatten6_fu_318_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 8 : 
            if ((!(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0)) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_fu_504_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter3.read(), ap_const_logic_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(exitcond_flatten_fu_504_p2.read(), ap_const_lv1_1) && 
  esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_state9;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXXXX";
            break;
    }
}

}

