// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_layer1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_address0,
        input_0_ce0,
        input_0_q0,
        input_1_address0,
        input_1_ce0,
        input_1_q0,
        input_2_address0,
        input_2_ce0,
        input_2_q0,
        output_0_address0,
        output_0_ce0,
        output_0_we0,
        output_0_d0,
        output_1_address0,
        output_1_ce0,
        output_1_we0,
        output_1_d0
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_pp0_stage0 = 5'd8;
parameter    ap_ST_fsm_state9 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [11:0] input_0_address0;
output   input_0_ce0;
input  [31:0] input_0_q0;
output  [11:0] input_1_address0;
output   input_1_ce0;
input  [31:0] input_1_q0;
output  [11:0] input_2_address0;
output   input_2_ce0;
input  [31:0] input_2_q0;
output  [13:0] output_0_address0;
output   output_0_ce0;
output   output_0_we0;
output  [30:0] output_0_d0;
output  [13:0] output_1_address0;
output   output_1_ce0;
output   output_1_we0;
output  [30:0] output_1_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_0_ce0;
reg input_1_ce0;
reg input_2_ce0;
reg output_0_ce0;
reg output_0_we0;
reg output_1_ce0;
reg output_1_we0;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [6:0] w_conv1_0_address0;
reg    w_conv1_0_ce0;
wire   [3:0] w_conv1_0_q0;
wire   [6:0] w_conv1_1_address0;
reg    w_conv1_1_ce0;
wire   [3:0] w_conv1_1_q0;
wire   [6:0] w_conv1_2_address0;
reg    w_conv1_2_ce0;
wire   [3:0] w_conv1_2_q0;
reg   [3:0] indvar_flatten_reg_259;
reg   [1:0] kr_reg_270;
reg   [1:0] kc_reg_281;
reg   [31:0] sum_1_reg_292;
wire   [14:0] indvar_flatten_next6_fu_324_p2;
reg   [14:0] indvar_flatten_next6_reg_710;
wire    ap_CS_fsm_state2;
wire   [0:0] exitcond_flatten4_fu_330_p2;
reg   [0:0] exitcond_flatten4_reg_715;
wire   [0:0] exitcond_flatten6_fu_318_p2;
wire   [3:0] oc_mid2_fu_388_p3;
reg   [3:0] oc_mid2_reg_721;
wire   [0:0] arrayNo_trunc_mid2_fu_400_p3;
reg   [0:0] arrayNo_trunc_mid2_reg_728;
wire   [4:0] newIndex3_mid2_fu_418_p3;
reg   [4:0] newIndex3_mid2_reg_732;
wire   [5:0] col_mid2_fu_426_p3;
reg   [5:0] col_mid2_reg_737;
wire   [5:0] tmp_mid2_v_fu_440_p3;
reg   [5:0] tmp_mid2_v_reg_743;
wire    ap_CS_fsm_state3;
wire   [7:0] tmp_cast4_fu_486_p1;
reg   [7:0] tmp_cast4_reg_749;
reg   [13:0] output_0_addr_reg_754;
reg   [13:0] output_1_addr_reg_759;
wire   [0:0] exitcond_flatten_fu_504_p2;
reg   [0:0] exitcond_flatten_reg_764;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_block_state4_pp0_stage0_iter0;
wire    ap_block_state5_pp0_stage0_iter1;
wire    ap_block_state6_pp0_stage0_iter2;
wire    ap_block_state7_pp0_stage0_iter3;
wire    ap_block_state8_pp0_stage0_iter4;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] exitcond_flatten_reg_764_pp0_iter1_reg;
reg   [0:0] exitcond_flatten_reg_764_pp0_iter2_reg;
reg   [0:0] exitcond_flatten_reg_764_pp0_iter3_reg;
wire   [3:0] indvar_flatten_next_fu_510_p2;
reg    ap_enable_reg_pp0_iter0;
wire   [1:0] kc_mid2_fu_528_p3;
reg   [1:0] kc_mid2_reg_773;
wire   [1:0] tmp_50_mid2_v_v_v_fu_536_p3;
reg   [1:0] tmp_50_mid2_v_v_v_reg_779;
wire   [1:0] kc_3_fu_544_p2;
reg  signed [31:0] input_0_load_reg_822;
reg   [3:0] w_conv1_0_load_reg_827;
reg  signed [31:0] input_1_load_reg_832;
reg   [3:0] w_conv1_1_load_reg_837;
reg  signed [31:0] input_2_load_reg_842;
reg   [3:0] w_conv1_2_load_reg_847;
wire   [31:0] tmp_39_fu_633_p2;
reg   [31:0] tmp_39_reg_852;
wire   [31:0] tmp_78_1_fu_641_p2;
reg   [31:0] tmp_78_1_reg_857;
wire   [31:0] tmp_78_2_fu_649_p2;
reg   [31:0] tmp_78_2_reg_862;
wire   [31:0] sum_6_2_fu_663_p2;
reg    ap_enable_reg_pp0_iter4;
wire   [3:0] oc_4_fu_689_p2;
wire    ap_CS_fsm_state9;
wire   [9:0] indvar_flatten_next8_fu_700_p3;
wire    ap_block_pp0_stage0_subdone;
reg    ap_condition_pp0_exit_iter0_state4;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg   [14:0] indvar_flatten6_reg_202;
reg   [5:0] row_reg_213;
reg   [9:0] indvar_flatten7_reg_225;
reg   [5:0] col_reg_237;
reg   [3:0] oc_reg_248;
reg   [1:0] ap_phi_mux_kr_phi_fu_274_p4;
wire    ap_block_pp0_stage0;
wire   [63:0] tmp_184_cast_fu_498_p1;
wire   [63:0] tmp_128_fu_594_p1;
wire   [63:0] tmp_193_cast_fu_623_p1;
wire   [30:0] tmp_35_fu_679_p3;
wire   [0:0] tmp_77_fu_304_p1;
wire   [0:0] not_exitcond_flatten_fu_344_p2;
wire   [4:0] newIndex_fu_308_p4;
wire   [0:0] exitcond_fu_364_p2;
wire   [5:0] col_mid_fu_336_p3;
wire   [0:0] exitcond3_mid_fu_370_p2;
wire   [0:0] tmp_122_fu_382_p2;
wire   [5:0] col_3_fu_376_p2;
wire   [0:0] tmp_78_fu_396_p1;
wire   [0:0] arrayNo_trunc_mid_fu_350_p2;
wire   [4:0] newIndex_mid1_fu_408_p4;
wire   [4:0] newIndex3_mid_fu_356_p3;
wire   [5:0] row_3_fu_434_p2;
wire   [10:0] tmp_fu_451_p3;
wire   [11:0] p_shl_cast_fu_459_p1;
wire   [11:0] tmp_mid2_cast_fu_447_p1;
wire   [11:0] newIndex3_mid2_cast_fu_469_p1;
wire   [11:0] tmp_s_fu_463_p2;
wire   [11:0] tmp_123_fu_472_p2;
wire   [14:0] tmp_cast_fu_489_p1;
wire   [14:0] tmp_183_cast_fu_478_p3;
wire   [14:0] tmp_124_fu_492_p2;
wire   [0:0] exitcond4_fu_522_p2;
wire   [1:0] kr_3_fu_516_p2;
wire   [5:0] tmp_50_mid2_v_v_fu_550_p1;
wire   [3:0] tmp_125_fu_561_p3;
wire   [4:0] p_shl2_cast_fu_568_p1;
wire   [4:0] tmp_51_mid2_cast_fu_558_p1;
wire   [5:0] kc_cast3_fu_578_p1;
wire   [5:0] tmp_50_mid2_v_fu_553_p2;
wire   [5:0] tmp_37_fu_581_p2;
wire   [11:0] tmp_127_fu_586_p3;
wire   [4:0] tmp_126_fu_572_p2;
wire   [4:0] tmp_80_fu_601_p1;
wire   [4:0] tmp_81_fu_604_p2;
wire   [7:0] tmp_192_cast_fu_610_p3;
wire   [7:0] tmp_129_fu_618_p2;
wire  signed [3:0] tmp_39_fu_633_p0;
wire  signed [3:0] tmp_78_1_fu_641_p0;
wire  signed [3:0] tmp_78_2_fu_649_p0;
wire   [31:0] tmp1_fu_654_p2;
wire   [31:0] tmp_40_fu_658_p2;
wire   [0:0] tmp_34_fu_673_p2;
wire   [30:0] tmp_79_fu_669_p1;
wire   [9:0] indvar_flatten7_op_fu_694_p2;
reg   [4:0] ap_NS_fsm;
reg    ap_idle_pp0;
wire    ap_enable_pp0;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter0 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
end

conv_layer1_w_conbkb #(
    .DataWidth( 4 ),
    .AddressRange( 72 ),
    .AddressWidth( 7 ))
w_conv1_0_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_conv1_0_address0),
    .ce0(w_conv1_0_ce0),
    .q0(w_conv1_0_q0)
);

conv_layer1_w_concud #(
    .DataWidth( 4 ),
    .AddressRange( 72 ),
    .AddressWidth( 7 ))
w_conv1_1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_conv1_1_address0),
    .ce0(w_conv1_1_ce0),
    .q0(w_conv1_1_q0)
);

conv_layer1_w_conbkb #(
    .DataWidth( 4 ),
    .AddressRange( 72 ),
    .AddressWidth( 7 ))
w_conv1_2_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_conv1_2_address0),
    .ce0(w_conv1_2_ce0),
    .q0(w_conv1_2_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_condition_pp0_exit_iter0_state4) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter0 <= 1'b0;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter0 <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            if ((1'b1 == ap_condition_pp0_exit_iter0_state4)) begin
                ap_enable_reg_pp0_iter1 <= (1'b1 ^ ap_condition_pp0_exit_iter0_state4);
            end else if ((1'b1 == 1'b1)) begin
                ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
            end
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end else if ((1'b1 == ap_CS_fsm_state3)) begin
            ap_enable_reg_pp0_iter4 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        col_reg_237 <= col_mid2_reg_737;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        col_reg_237 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        indvar_flatten6_reg_202 <= indvar_flatten_next6_reg_710;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten6_reg_202 <= 15'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        indvar_flatten7_reg_225 <= indvar_flatten_next8_fu_700_p3;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        indvar_flatten7_reg_225 <= 10'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_504_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        indvar_flatten_reg_259 <= indvar_flatten_next_fu_510_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        indvar_flatten_reg_259 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_504_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kc_reg_281 <= kc_3_fu_544_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        kc_reg_281 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_764 == 1'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kr_reg_270 <= tmp_50_mid2_v_v_v_reg_779;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        kr_reg_270 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        oc_reg_248 <= oc_4_fu_689_p2;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        oc_reg_248 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        row_reg_213 <= tmp_mid2_v_reg_743;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_reg_213 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_764_pp0_iter3_reg == 1'd0) & (ap_enable_reg_pp0_iter4 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        sum_1_reg_292 <= sum_6_2_fu_663_p2;
    end else if ((1'b1 == ap_CS_fsm_state3)) begin
        sum_1_reg_292 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten6_fu_318_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        arrayNo_trunc_mid2_reg_728 <= arrayNo_trunc_mid2_fu_400_p3;
        col_mid2_reg_737 <= col_mid2_fu_426_p3;
        exitcond_flatten4_reg_715 <= exitcond_flatten4_fu_330_p2;
        newIndex3_mid2_reg_732 <= newIndex3_mid2_fu_418_p3;
        oc_mid2_reg_721 <= oc_mid2_fu_388_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        exitcond_flatten_reg_764 <= exitcond_flatten_fu_504_p2;
        exitcond_flatten_reg_764_pp0_iter1_reg <= exitcond_flatten_reg_764;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        exitcond_flatten_reg_764_pp0_iter2_reg <= exitcond_flatten_reg_764_pp0_iter1_reg;
        exitcond_flatten_reg_764_pp0_iter3_reg <= exitcond_flatten_reg_764_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        indvar_flatten_next6_reg_710 <= indvar_flatten_next6_fu_324_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_764_pp0_iter1_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_0_load_reg_822 <= input_0_q0;
        input_1_load_reg_832 <= input_1_q0;
        input_2_load_reg_842 <= input_2_q0;
        w_conv1_0_load_reg_827 <= w_conv1_0_q0;
        w_conv1_1_load_reg_837 <= w_conv1_1_q0;
        w_conv1_2_load_reg_847 <= w_conv1_2_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_504_p2 == 1'd0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        kc_mid2_reg_773 <= kc_mid2_fu_528_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        output_0_addr_reg_754 <= tmp_184_cast_fu_498_p1;
        output_1_addr_reg_759 <= tmp_184_cast_fu_498_p1;
        tmp_cast4_reg_749[3 : 0] <= tmp_cast4_fu_486_p1[3 : 0];
        tmp_mid2_v_reg_743 <= tmp_mid2_v_fu_440_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_reg_764_pp0_iter2_reg == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_39_reg_852 <= tmp_39_fu_633_p2;
        tmp_78_1_reg_857 <= tmp_78_1_fu_641_p2;
        tmp_78_2_reg_862 <= tmp_78_2_fu_649_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond_flatten_fu_504_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        tmp_50_mid2_v_v_v_reg_779 <= tmp_50_mid2_v_v_v_fu_536_p3;
    end
end

always @ (*) begin
    if ((exitcond_flatten_fu_504_p2 == 1'd1)) begin
        ap_condition_pp0_exit_iter0_state4 = 1'b1;
    end else begin
        ap_condition_pp0_exit_iter0_state4 = 1'b0;
    end
end

always @ (*) begin
    if ((((exitcond_flatten6_fu_318_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond_flatten_reg_764 == 1'd0) & (1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_phi_mux_kr_phi_fu_274_p4 = tmp_50_mid2_v_v_v_reg_779;
    end else begin
        ap_phi_mux_kr_phi_fu_274_p4 = kr_reg_270;
    end
end

always @ (*) begin
    if (((exitcond_flatten6_fu_318_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_0_ce0 = 1'b1;
    end else begin
        input_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_1_ce0 = 1'b1;
    end else begin
        input_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        input_2_ce0 = 1'b1;
    end else begin
        input_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        output_0_ce0 = 1'b1;
    end else begin
        output_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((arrayNo_trunc_mid2_reg_728 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        output_0_we0 = 1'b1;
    end else begin
        output_0_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        output_1_ce0 = 1'b1;
    end else begin
        output_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) & (arrayNo_trunc_mid2_reg_728 == 1'd1))) begin
        output_1_we0 = 1'b1;
    end else begin
        output_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w_conv1_0_ce0 = 1'b1;
    end else begin
        w_conv1_0_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w_conv1_1_ce0 = 1'b1;
    end else begin
        w_conv1_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (1'b0 == ap_block_pp0_stage0_11001))) begin
        w_conv1_2_ce0 = 1'b1;
    end else begin
        w_conv1_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond_flatten6_fu_318_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_fu_504_p2 == 1'd1)) & ~((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else if ((((ap_enable_reg_pp0_iter3 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter4 == 1'b1)) | ((ap_enable_reg_pp0_iter1 == 1'b0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (exitcond_flatten_fu_504_p2 == 1'd1)))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign arrayNo_trunc_mid2_fu_400_p3 = ((exitcond3_mid_fu_370_p2[0:0] === 1'b1) ? tmp_78_fu_396_p1 : arrayNo_trunc_mid_fu_350_p2);

assign arrayNo_trunc_mid_fu_350_p2 = (tmp_77_fu_304_p1 & not_exitcond_flatten_fu_344_p2);

assign col_3_fu_376_p2 = (6'd1 + col_mid_fu_336_p3);

assign col_mid2_fu_426_p3 = ((exitcond3_mid_fu_370_p2[0:0] === 1'b1) ? col_3_fu_376_p2 : col_mid_fu_336_p3);

assign col_mid_fu_336_p3 = ((exitcond_flatten4_fu_330_p2[0:0] === 1'b1) ? 6'd0 : col_reg_237);

assign exitcond3_mid_fu_370_p2 = (not_exitcond_flatten_fu_344_p2 & exitcond_fu_364_p2);

assign exitcond4_fu_522_p2 = ((kc_reg_281 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond_flatten4_fu_330_p2 = ((indvar_flatten7_reg_225 == 10'd496) ? 1'b1 : 1'b0);

assign exitcond_flatten6_fu_318_p2 = ((indvar_flatten6_reg_202 == 15'd30752) ? 1'b1 : 1'b0);

assign exitcond_flatten_fu_504_p2 = ((indvar_flatten_reg_259 == 4'd9) ? 1'b1 : 1'b0);

assign exitcond_fu_364_p2 = ((oc_reg_248 == 4'd8) ? 1'b1 : 1'b0);

assign indvar_flatten7_op_fu_694_p2 = (indvar_flatten7_reg_225 + 10'd1);

assign indvar_flatten_next6_fu_324_p2 = (15'd1 + indvar_flatten6_reg_202);

assign indvar_flatten_next8_fu_700_p3 = ((exitcond_flatten4_reg_715[0:0] === 1'b1) ? 10'd1 : indvar_flatten7_op_fu_694_p2);

assign indvar_flatten_next_fu_510_p2 = (indvar_flatten_reg_259 + 4'd1);

assign input_0_address0 = tmp_128_fu_594_p1;

assign input_1_address0 = tmp_128_fu_594_p1;

assign input_2_address0 = tmp_128_fu_594_p1;

assign kc_3_fu_544_p2 = (kc_mid2_fu_528_p3 + 2'd1);

assign kc_cast3_fu_578_p1 = kc_mid2_reg_773;

assign kc_mid2_fu_528_p3 = ((exitcond4_fu_522_p2[0:0] === 1'b1) ? 2'd0 : kc_reg_281);

assign kr_3_fu_516_p2 = (ap_phi_mux_kr_phi_fu_274_p4 + 2'd1);

assign newIndex3_mid2_cast_fu_469_p1 = newIndex3_mid2_reg_732;

assign newIndex3_mid2_fu_418_p3 = ((exitcond3_mid_fu_370_p2[0:0] === 1'b1) ? newIndex_mid1_fu_408_p4 : newIndex3_mid_fu_356_p3);

assign newIndex3_mid_fu_356_p3 = ((exitcond_flatten4_fu_330_p2[0:0] === 1'b1) ? 5'd0 : newIndex_fu_308_p4);

assign newIndex_fu_308_p4 = {{col_reg_237[5:1]}};

assign newIndex_mid1_fu_408_p4 = {{col_3_fu_376_p2[5:1]}};

assign not_exitcond_flatten_fu_344_p2 = (exitcond_flatten4_fu_330_p2 ^ 1'd1);

assign oc_4_fu_689_p2 = (oc_mid2_reg_721 + 4'd1);

assign oc_mid2_fu_388_p3 = ((tmp_122_fu_382_p2[0:0] === 1'b1) ? 4'd0 : oc_reg_248);

assign output_0_address0 = output_0_addr_reg_754;

assign output_0_d0 = tmp_35_fu_679_p3;

assign output_1_address0 = output_1_addr_reg_759;

assign output_1_d0 = tmp_35_fu_679_p3;

assign p_shl2_cast_fu_568_p1 = tmp_125_fu_561_p3;

assign p_shl_cast_fu_459_p1 = tmp_fu_451_p3;

assign row_3_fu_434_p2 = (6'd1 + row_reg_213);

assign sum_6_2_fu_663_p2 = (tmp_40_fu_658_p2 + sum_1_reg_292);

assign tmp1_fu_654_p2 = (tmp_78_2_reg_862 + tmp_78_1_reg_857);

assign tmp_122_fu_382_p2 = (exitcond_flatten4_fu_330_p2 | exitcond3_mid_fu_370_p2);

assign tmp_123_fu_472_p2 = (newIndex3_mid2_cast_fu_469_p1 + tmp_s_fu_463_p2);

assign tmp_124_fu_492_p2 = (tmp_cast_fu_489_p1 + tmp_183_cast_fu_478_p3);

assign tmp_125_fu_561_p3 = {{tmp_50_mid2_v_v_v_reg_779}, {2'd0}};

assign tmp_126_fu_572_p2 = (p_shl2_cast_fu_568_p1 - tmp_51_mid2_cast_fu_558_p1);

assign tmp_127_fu_586_p3 = {{tmp_50_mid2_v_fu_553_p2}, {tmp_37_fu_581_p2}};

assign tmp_128_fu_594_p1 = tmp_127_fu_586_p3;

assign tmp_129_fu_618_p2 = (tmp_192_cast_fu_610_p3 + tmp_cast4_reg_749);

assign tmp_183_cast_fu_478_p3 = {{tmp_123_fu_472_p2}, {3'd0}};

assign tmp_184_cast_fu_498_p1 = tmp_124_fu_492_p2;

assign tmp_192_cast_fu_610_p3 = {{tmp_81_fu_604_p2}, {3'd0}};

assign tmp_193_cast_fu_623_p1 = tmp_129_fu_618_p2;

assign tmp_34_fu_673_p2 = (($signed(sum_1_reg_292) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_35_fu_679_p3 = ((tmp_34_fu_673_p2[0:0] === 1'b1) ? tmp_79_fu_669_p1 : 31'd0);

assign tmp_37_fu_581_p2 = (kc_cast3_fu_578_p1 + col_mid2_reg_737);

assign tmp_39_fu_633_p0 = w_conv1_0_load_reg_827;

assign tmp_39_fu_633_p2 = ($signed(tmp_39_fu_633_p0) * $signed(input_0_load_reg_822));

assign tmp_40_fu_658_p2 = (tmp_39_reg_852 + tmp1_fu_654_p2);

assign tmp_50_mid2_v_fu_553_p2 = (tmp_50_mid2_v_v_fu_550_p1 + tmp_mid2_v_reg_743);

assign tmp_50_mid2_v_v_fu_550_p1 = tmp_50_mid2_v_v_v_reg_779;

assign tmp_50_mid2_v_v_v_fu_536_p3 = ((exitcond4_fu_522_p2[0:0] === 1'b1) ? kr_3_fu_516_p2 : ap_phi_mux_kr_phi_fu_274_p4);

assign tmp_51_mid2_cast_fu_558_p1 = tmp_50_mid2_v_v_v_reg_779;

assign tmp_77_fu_304_p1 = col_reg_237[0:0];

assign tmp_78_1_fu_641_p0 = w_conv1_1_load_reg_837;

assign tmp_78_1_fu_641_p2 = ($signed(tmp_78_1_fu_641_p0) * $signed(input_1_load_reg_832));

assign tmp_78_2_fu_649_p0 = w_conv1_2_load_reg_847;

assign tmp_78_2_fu_649_p2 = ($signed(tmp_78_2_fu_649_p0) * $signed(input_2_load_reg_842));

assign tmp_78_fu_396_p1 = col_3_fu_376_p2[0:0];

assign tmp_79_fu_669_p1 = sum_1_reg_292[30:0];

assign tmp_80_fu_601_p1 = kc_mid2_reg_773;

assign tmp_81_fu_604_p2 = (tmp_126_fu_572_p2 + tmp_80_fu_601_p1);

assign tmp_cast4_fu_486_p1 = oc_mid2_reg_721;

assign tmp_cast_fu_489_p1 = oc_mid2_reg_721;

assign tmp_fu_451_p3 = {{tmp_mid2_v_fu_440_p3}, {5'd0}};

assign tmp_mid2_cast_fu_447_p1 = tmp_mid2_v_fu_440_p3;

assign tmp_mid2_v_fu_440_p3 = ((exitcond_flatten4_reg_715[0:0] === 1'b1) ? row_3_fu_434_p2 : row_reg_213);

assign tmp_s_fu_463_p2 = (p_shl_cast_fu_459_p1 - tmp_mid2_cast_fu_447_p1);

assign w_conv1_0_address0 = tmp_193_cast_fu_623_p1;

assign w_conv1_1_address0 = tmp_193_cast_fu_623_p1;

assign w_conv1_2_address0 = tmp_193_cast_fu_623_p1;

always @ (posedge ap_clk) begin
    tmp_cast4_reg_749[7:4] <= 4'b0000;
end

endmodule //conv_layer1
