// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module conv_layer1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0
);

parameter    ap_ST_fsm_state1 = 10'd1;
parameter    ap_ST_fsm_state2 = 10'd2;
parameter    ap_ST_fsm_state3 = 10'd4;
parameter    ap_ST_fsm_state4 = 10'd8;
parameter    ap_ST_fsm_state5 = 10'd16;
parameter    ap_ST_fsm_state6 = 10'd32;
parameter    ap_ST_fsm_state7 = 10'd64;
parameter    ap_ST_fsm_state8 = 10'd128;
parameter    ap_ST_fsm_state9 = 10'd256;
parameter    ap_ST_fsm_state10 = 10'd512;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [13:0] input_r_address0;
output   input_r_ce0;
input  [31:0] input_r_q0;
output  [14:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [30:0] output_r_d0;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg input_r_ce0;
reg output_r_ce0;
reg output_r_we0;

(* fsm_encoding = "none" *) reg   [9:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [7:0] w_conv1_address0;
reg    w_conv1_ce0;
wire   [3:0] w_conv1_q0;
wire   [5:0] row_3_fu_222_p2;
reg   [5:0] row_3_reg_522;
wire    ap_CS_fsm_state2;
wire   [12:0] tmp_90_fu_252_p2;
reg   [12:0] tmp_90_reg_527;
wire   [0:0] exitcond5_fu_216_p2;
wire   [5:0] col_3_fu_264_p2;
reg   [5:0] col_3_reg_535;
wire    ap_CS_fsm_state3;
wire   [15:0] tmp_142_cast_fu_279_p3;
reg   [15:0] tmp_142_cast_reg_540;
wire   [0:0] exitcond4_fu_258_p2;
wire   [3:0] oc_4_fu_293_p2;
reg   [3:0] oc_4_reg_548;
wire    ap_CS_fsm_state4;
wire   [8:0] tmp_51_cast5_fu_299_p1;
reg   [8:0] tmp_51_cast5_reg_553;
wire   [0:0] exitcond3_fu_287_p2;
reg   [14:0] output_addr_reg_558;
wire   [1:0] kr_3_fu_327_p2;
reg   [1:0] kr_3_reg_566;
wire    ap_CS_fsm_state5;
wire   [5:0] tmp_54_fu_333_p2;
reg   [5:0] tmp_54_reg_571;
wire   [0:0] exitcond2_fu_321_p2;
wire  signed [5:0] tmp_145_cast_fu_361_p1;
reg  signed [5:0] tmp_145_cast_reg_577;
wire   [1:0] kc_3_fu_394_p2;
reg   [1:0] kc_3_reg_585;
wire    ap_CS_fsm_state6;
wire   [14:0] tmp_97_fu_430_p2;
reg   [14:0] tmp_97_reg_590;
wire   [0:0] exitcond1_fu_388_p2;
wire   [5:0] tmp_99_fu_447_p2;
reg   [5:0] tmp_99_reg_595;
wire   [1:0] ic_4_fu_459_p2;
reg   [1:0] ic_4_reg_603;
wire    ap_CS_fsm_state7;
wire   [0:0] exitcond_fu_453_p2;
reg  signed [31:0] input_load_reg_618;
wire    ap_CS_fsm_state8;
reg   [3:0] w_conv1_load_reg_623;
wire   [31:0] tmp_61_fu_509_p2;
reg   [31:0] tmp_61_reg_628;
wire    ap_CS_fsm_state9;
wire   [31:0] sum_6_fu_514_p2;
wire    ap_CS_fsm_state10;
reg   [5:0] row_reg_112;
reg   [5:0] col_reg_124;
reg   [3:0] oc_reg_136;
reg   [1:0] kr_reg_147;
reg   [31:0] sum_reg_158;
reg   [1:0] kc_reg_170;
reg   [31:0] sum_1_reg_181;
reg   [1:0] ic_reg_193;
reg   [31:0] sum_2_reg_204;
wire   [63:0] tmp_143_cast_fu_312_p1;
wire   [63:0] tmp_156_cast_fu_491_p1;
wire  signed [63:0] tmp_157_cast_fu_501_p1;
wire   [11:0] tmp_fu_228_p3;
wire   [6:0] tmp_s_fu_240_p3;
wire   [12:0] p_shl_cast_fu_236_p1;
wire   [12:0] p_shl1_cast_fu_248_p1;
wire   [12:0] tmp_cast_fu_270_p1;
wire   [12:0] tmp_91_fu_274_p2;
wire   [15:0] tmp_51_cast_fu_303_p1;
wire   [15:0] tmp_92_fu_307_p2;
wire   [5:0] kr_cast5_fu_317_p1;
wire   [3:0] tmp_93_fu_343_p3;
wire   [4:0] p_shl2_cast_fu_351_p1;
wire   [4:0] tmp_56_cast_fu_339_p1;
wire   [4:0] tmp_94_fu_355_p2;
wire   [0:0] tmp_52_fu_369_p2;
wire   [30:0] tmp_48_fu_365_p1;
wire   [5:0] kc_cast3_fu_384_p1;
wire   [5:0] tmp_57_fu_400_p2;
wire   [11:0] tmp_95_fu_406_p3;
wire   [13:0] tmp_96_fu_417_p4;
wire   [14:0] p_shl4_cast_fu_426_p1;
wire   [14:0] tmp_147_cast_fu_413_p1;
wire   [5:0] tmp_98_fu_436_p2;
wire   [5:0] tmp_49_fu_441_p2;
wire   [5:0] tmp_60_fu_465_p1;
wire   [5:0] tmp_100_fu_473_p2;
wire   [8:0] tmp_155_cast_fu_478_p3;
wire   [8:0] tmp_101_fu_486_p2;
wire   [14:0] tmp_60_cast_fu_469_p1;
wire   [14:0] tmp_102_fu_496_p2;
wire  signed [3:0] tmp_61_fu_509_p1;
reg   [9:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 10'd1;
end

conv_layer1_w_conv1 #(
    .DataWidth( 4 ),
    .AddressRange( 216 ),
    .AddressWidth( 8 ))
w_conv1_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(w_conv1_address0),
    .ce0(w_conv1_ce0),
    .q0(w_conv1_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_287_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        col_reg_124 <= col_3_reg_535;
    end else if (((exitcond5_fu_216_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        col_reg_124 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        ic_reg_193 <= ic_4_reg_603;
    end else if (((exitcond1_fu_388_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        ic_reg_193 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond_fu_453_p2 == 1'd1))) begin
        kc_reg_170 <= kc_3_reg_585;
    end else if (((exitcond2_fu_321_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        kc_reg_170 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (exitcond1_fu_388_p2 == 1'd1))) begin
        kr_reg_147 <= kr_3_reg_566;
    end else if (((exitcond3_fu_287_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        kr_reg_147 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_321_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        oc_reg_136 <= oc_4_reg_548;
    end else if (((exitcond4_fu_258_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        oc_reg_136 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_258_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        row_reg_112 <= row_3_reg_522;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        row_reg_112 <= 6'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state7) & (exitcond_fu_453_p2 == 1'd1))) begin
        sum_1_reg_181 <= sum_2_reg_204;
    end else if (((exitcond2_fu_321_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        sum_1_reg_181 <= sum_reg_158;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        sum_2_reg_204 <= sum_6_fu_514_p2;
    end else if (((exitcond1_fu_388_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        sum_2_reg_204 <= sum_1_reg_181;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (exitcond1_fu_388_p2 == 1'd1))) begin
        sum_reg_158 <= sum_1_reg_181;
    end else if (((exitcond3_fu_287_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        sum_reg_158 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        col_3_reg_535 <= col_3_fu_264_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        ic_4_reg_603 <= ic_4_fu_459_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        input_load_reg_618 <= input_r_q0;
        w_conv1_load_reg_623 <= w_conv1_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        kc_3_reg_585 <= kc_3_fu_394_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        kr_3_reg_566 <= kr_3_fu_327_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        oc_4_reg_548 <= oc_4_fu_293_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_287_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        output_addr_reg_558 <= tmp_143_cast_fu_312_p1;
        tmp_51_cast5_reg_553[3 : 0] <= tmp_51_cast5_fu_299_p1[3 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        row_3_reg_522 <= row_3_fu_222_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond4_fu_258_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_142_cast_reg_540[15 : 3] <= tmp_142_cast_fu_279_p3[15 : 3];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_321_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state5))) begin
        tmp_145_cast_reg_577 <= tmp_145_cast_fu_361_p1;
        tmp_54_reg_571 <= tmp_54_fu_333_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        tmp_61_reg_628 <= tmp_61_fu_509_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond5_fu_216_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_90_reg_527[12 : 1] <= tmp_90_fu_252_p2[12 : 1];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_388_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        tmp_97_reg_590 <= tmp_97_fu_430_p2;
        tmp_99_reg_595 <= tmp_99_fu_447_p2;
    end
end

always @ (*) begin
    if ((((exitcond5_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond5_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        input_r_ce0 = 1'b1;
    end else begin
        input_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond2_fu_321_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        w_conv1_ce0 = 1'b1;
    end else begin
        w_conv1_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond5_fu_216_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond4_fu_258_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond3_fu_287_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            if (((exitcond2_fu_321_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state5))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (exitcond1_fu_388_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((1'b1 == ap_CS_fsm_state7) & (exitcond_fu_453_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            ap_NS_fsm = ap_ST_fsm_state9;
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state10;
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign col_3_fu_264_p2 = (col_reg_124 + 6'd1);

assign exitcond1_fu_388_p2 = ((kc_reg_170 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond2_fu_321_p2 = ((kr_reg_147 == 2'd3) ? 1'b1 : 1'b0);

assign exitcond3_fu_287_p2 = ((oc_reg_136 == 4'd8) ? 1'b1 : 1'b0);

assign exitcond4_fu_258_p2 = ((col_reg_124 == 6'd62) ? 1'b1 : 1'b0);

assign exitcond5_fu_216_p2 = ((row_reg_112 == 6'd62) ? 1'b1 : 1'b0);

assign exitcond_fu_453_p2 = ((ic_reg_193 == 2'd3) ? 1'b1 : 1'b0);

assign ic_4_fu_459_p2 = (ic_reg_193 + 2'd1);

assign input_r_address0 = tmp_157_cast_fu_501_p1;

assign kc_3_fu_394_p2 = (kc_reg_170 + 2'd1);

assign kc_cast3_fu_384_p1 = kc_reg_170;

assign kr_3_fu_327_p2 = (kr_reg_147 + 2'd1);

assign kr_cast5_fu_317_p1 = kr_reg_147;

assign oc_4_fu_293_p2 = (oc_reg_136 + 4'd1);

assign output_r_address0 = output_addr_reg_558;

assign output_r_d0 = ((tmp_52_fu_369_p2[0:0] === 1'b1) ? tmp_48_fu_365_p1 : 31'd0);

assign p_shl1_cast_fu_248_p1 = tmp_s_fu_240_p3;

assign p_shl2_cast_fu_351_p1 = tmp_93_fu_343_p3;

assign p_shl4_cast_fu_426_p1 = tmp_96_fu_417_p4;

assign p_shl_cast_fu_236_p1 = tmp_fu_228_p3;

assign row_3_fu_222_p2 = (row_reg_112 + 6'd1);

assign sum_6_fu_514_p2 = (tmp_61_reg_628 + sum_2_reg_204);

assign tmp_100_fu_473_p2 = (tmp_60_fu_465_p1 + tmp_99_reg_595);

assign tmp_101_fu_486_p2 = (tmp_51_cast5_reg_553 + tmp_155_cast_fu_478_p3);

assign tmp_102_fu_496_p2 = (tmp_60_cast_fu_469_p1 + tmp_97_reg_590);

assign tmp_142_cast_fu_279_p3 = {{tmp_91_fu_274_p2}, {3'd0}};

assign tmp_143_cast_fu_312_p1 = tmp_92_fu_307_p2;

assign tmp_145_cast_fu_361_p1 = $signed(tmp_94_fu_355_p2);

assign tmp_147_cast_fu_413_p1 = tmp_95_fu_406_p3;

assign tmp_155_cast_fu_478_p3 = {{tmp_100_fu_473_p2}, {3'd0}};

assign tmp_156_cast_fu_491_p1 = tmp_101_fu_486_p2;

assign tmp_157_cast_fu_501_p1 = $signed(tmp_102_fu_496_p2);

assign tmp_48_fu_365_p1 = sum_reg_158[30:0];

assign tmp_49_fu_441_p2 = tmp_98_fu_436_p2 << 6'd2;

assign tmp_51_cast5_fu_299_p1 = oc_reg_136;

assign tmp_51_cast_fu_303_p1 = oc_reg_136;

assign tmp_52_fu_369_p2 = (($signed(sum_reg_158) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign tmp_54_fu_333_p2 = (kr_cast5_fu_317_p1 + row_reg_112);

assign tmp_56_cast_fu_339_p1 = kr_reg_147;

assign tmp_57_fu_400_p2 = (col_reg_124 + kc_cast3_fu_384_p1);

assign tmp_60_cast_fu_469_p1 = ic_reg_193;

assign tmp_60_fu_465_p1 = ic_reg_193;

assign tmp_61_fu_509_p1 = w_conv1_load_reg_623;

assign tmp_61_fu_509_p2 = ($signed(input_load_reg_618) * $signed(tmp_61_fu_509_p1));

assign tmp_90_fu_252_p2 = (p_shl_cast_fu_236_p1 - p_shl1_cast_fu_248_p1);

assign tmp_91_fu_274_p2 = (tmp_cast_fu_270_p1 + tmp_90_reg_527);

assign tmp_92_fu_307_p2 = (tmp_142_cast_reg_540 + tmp_51_cast_fu_303_p1);

assign tmp_93_fu_343_p3 = {{kr_reg_147}, {2'd0}};

assign tmp_94_fu_355_p2 = (p_shl2_cast_fu_351_p1 - tmp_56_cast_fu_339_p1);

assign tmp_95_fu_406_p3 = {{tmp_54_reg_571}, {tmp_57_fu_400_p2}};

assign tmp_96_fu_417_p4 = {{{tmp_54_reg_571}, {tmp_57_fu_400_p2}}, {2'd0}};

assign tmp_97_fu_430_p2 = (p_shl4_cast_fu_426_p1 - tmp_147_cast_fu_413_p1);

assign tmp_98_fu_436_p2 = ($signed(kc_cast3_fu_384_p1) + $signed(tmp_145_cast_reg_577));

assign tmp_99_fu_447_p2 = (tmp_49_fu_441_p2 - tmp_98_fu_436_p2);

assign tmp_cast_fu_270_p1 = col_reg_124;

assign tmp_fu_228_p3 = {{row_reg_112}, {6'd0}};

assign tmp_s_fu_240_p3 = {{row_reg_112}, {1'd0}};

assign w_conv1_address0 = tmp_156_cast_fu_491_p1;

always @ (posedge ap_clk) begin
    tmp_90_reg_527[0] <= 1'b0;
    tmp_142_cast_reg_540[2:0] <= 3'b000;
    tmp_51_cast5_reg_553[8:4] <= 5'b00000;
end

endmodule //conv_layer1
