// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "conv_layer3.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic conv_layer3::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic conv_layer3::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<10> conv_layer3::ap_ST_fsm_state1 = "1";
const sc_lv<10> conv_layer3::ap_ST_fsm_state2 = "10";
const sc_lv<10> conv_layer3::ap_ST_fsm_state3 = "100";
const sc_lv<10> conv_layer3::ap_ST_fsm_state4 = "1000";
const sc_lv<10> conv_layer3::ap_ST_fsm_state5 = "10000";
const sc_lv<10> conv_layer3::ap_ST_fsm_state6 = "100000";
const sc_lv<10> conv_layer3::ap_ST_fsm_state7 = "1000000";
const sc_lv<10> conv_layer3::ap_ST_fsm_state8 = "10000000";
const sc_lv<10> conv_layer3::ap_ST_fsm_state9 = "100000000";
const sc_lv<10> conv_layer3::ap_ST_fsm_state10 = "1000000000";
const sc_lv<32> conv_layer3::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> conv_layer3::ap_const_lv32_1 = "1";
const sc_lv<1> conv_layer3::ap_const_lv1_0 = "0";
const sc_lv<32> conv_layer3::ap_const_lv32_2 = "10";
const sc_lv<32> conv_layer3::ap_const_lv32_3 = "11";
const sc_lv<32> conv_layer3::ap_const_lv32_4 = "100";
const sc_lv<32> conv_layer3::ap_const_lv32_5 = "101";
const sc_lv<32> conv_layer3::ap_const_lv32_6 = "110";
const sc_lv<32> conv_layer3::ap_const_lv32_7 = "111";
const sc_lv<32> conv_layer3::ap_const_lv32_8 = "1000";
const sc_lv<32> conv_layer3::ap_const_lv32_9 = "1001";
const sc_lv<4> conv_layer3::ap_const_lv4_0 = "0000";
const sc_lv<1> conv_layer3::ap_const_lv1_1 = "1";
const sc_lv<6> conv_layer3::ap_const_lv6_0 = "000000";
const sc_lv<2> conv_layer3::ap_const_lv2_0 = "00";
const sc_lv<5> conv_layer3::ap_const_lv5_0 = "00000";
const sc_lv<4> conv_layer3::ap_const_lv4_C = "1100";
const sc_lv<4> conv_layer3::ap_const_lv4_1 = "1";
const sc_lv<6> conv_layer3::ap_const_lv6_20 = "100000";
const sc_lv<6> conv_layer3::ap_const_lv6_1 = "1";
const sc_lv<2> conv_layer3::ap_const_lv2_3 = "11";
const sc_lv<2> conv_layer3::ap_const_lv2_1 = "1";
const sc_lv<31> conv_layer3::ap_const_lv31_0 = "0000000000000000000000000000000";
const sc_lv<5> conv_layer3::ap_const_lv5_10 = "10000";
const sc_lv<5> conv_layer3::ap_const_lv5_1 = "1";
const bool conv_layer3::ap_const_boolean_1 = true;

conv_layer3::conv_layer3(sc_module_name name) : sc_module(name), mVcdFile(0) {
    w_conv3_U = new conv_layer3_w_conv3("w_conv3_U");
    w_conv3_U->clk(ap_clk);
    w_conv3_U->reset(ap_rst);
    w_conv3_U->address0(w_conv3_address0);
    w_conv3_U->ce0(w_conv3_ce0);
    w_conv3_U->q0(w_conv3_q0);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state5);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state8);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state9);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_222_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_222_p2 );

    SC_METHOD(thread_buf_pool2_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_113_cast_fu_501_p1 );

    SC_METHOD(thread_buf_pool2_ce0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_col_1_fu_270_p2);
    sensitive << ( col_reg_130 );

    SC_METHOD(thread_exitcond1_fu_420_p2);
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( kc_reg_176 );

    SC_METHOD(thread_exitcond2_fu_323_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( kr_reg_153 );

    SC_METHOD(thread_exitcond3_fu_293_p2);
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( oc_reg_142 );

    SC_METHOD(thread_exitcond4_fu_264_p2);
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( col_reg_130 );

    SC_METHOD(thread_exitcond5_fu_222_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( row_reg_118 );

    SC_METHOD(thread_exitcond_fu_476_p2);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( ic_reg_199 );

    SC_METHOD(thread_ic_2_fu_482_p2);
    sensitive << ( ic_reg_199 );

    SC_METHOD(thread_kc_1_fu_426_p2);
    sensitive << ( kc_reg_176 );

    SC_METHOD(thread_kc_cast3_fu_416_p1);
    sensitive << ( kc_reg_176 );

    SC_METHOD(thread_kr_1_fu_329_p2);
    sensitive << ( kr_reg_153 );

    SC_METHOD(thread_kr_cast5_fu_319_p1);
    sensitive << ( kr_reg_153 );

    SC_METHOD(thread_oc_2_fu_299_p2);
    sensitive << ( oc_reg_142 );

    SC_METHOD(thread_output_r_address0);
    sensitive << ( output_addr_reg_581 );
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_output_r_ce0);
    sensitive << ( ap_CS_fsm_state5 );

    SC_METHOD(thread_output_r_d0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( tmp_30_fu_401_p2 );
    sensitive << ( tmp_43_fu_397_p1 );

    SC_METHOD(thread_output_r_we0);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond2_fu_323_p2 );

    SC_METHOD(thread_p_shl1_cast_fu_254_p1);
    sensitive << ( tmp_s_fu_246_p3 );

    SC_METHOD(thread_p_shl2_cast_fu_383_p1);
    sensitive << ( tmp_71_fu_375_p3 );

    SC_METHOD(thread_p_shl3_cast_fu_349_p1);
    sensitive << ( tmp_68_fu_341_p3 );

    SC_METHOD(thread_p_shl4_cast_fu_361_p1);
    sensitive << ( tmp_69_fu_353_p3 );

    SC_METHOD(thread_p_shl_cast_fu_242_p1);
    sensitive << ( tmp_fu_234_p3 );

    SC_METHOD(thread_row_1_fu_228_p2);
    sensitive << ( row_reg_118 );

    SC_METHOD(thread_sum_4_fu_537_p2);
    sensitive << ( tmp_39_reg_650 );
    sensitive << ( sum_2_reg_210 );

    SC_METHOD(thread_tmp_100_cast_fu_285_p3);
    sensitive << ( tmp_66_fu_280_p2 );

    SC_METHOD(thread_tmp_101_cast_fu_314_p1);
    sensitive << ( tmp_67_fu_309_p2 );

    SC_METHOD(thread_tmp_106_cast_fu_393_p1);
    sensitive << ( tmp_72_fu_387_p2 );

    SC_METHOD(thread_tmp_109_cast_fu_447_p3);
    sensitive << ( tmp_73_fu_442_p2 );

    SC_METHOD(thread_tmp_113_cast_fu_501_p1);
    sensitive << ( tmp_76_fu_496_p2 );

    SC_METHOD(thread_tmp_116_cast_fu_511_p3);
    sensitive << ( tmp_77_fu_506_p2 );

    SC_METHOD(thread_tmp_117_cast_fu_524_p1);
    sensitive << ( tmp_78_fu_519_p2 );

    SC_METHOD(thread_tmp_29_cast_fu_305_p1);
    sensitive << ( oc_reg_142 );

    SC_METHOD(thread_tmp_30_fu_401_p2);
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond2_fu_323_p2 );
    sensitive << ( sum_reg_164 );

    SC_METHOD(thread_tmp_32_fu_335_p2);
    sensitive << ( row_reg_118 );
    sensitive << ( kr_cast5_fu_319_p1 );

    SC_METHOD(thread_tmp_34_cast_fu_371_p1);
    sensitive << ( kr_reg_153 );

    SC_METHOD(thread_tmp_35_fu_432_p2);
    sensitive << ( col_reg_130 );
    sensitive << ( kc_cast3_fu_416_p1 );

    SC_METHOD(thread_tmp_36_cast_fu_438_p1);
    sensitive << ( tmp_35_fu_432_p2 );

    SC_METHOD(thread_tmp_37_cast_fu_455_p1);
    sensitive << ( kc_reg_176 );

    SC_METHOD(thread_tmp_38_cast_fu_492_p1);
    sensitive << ( ic_reg_199 );

    SC_METHOD(thread_tmp_38_fu_488_p1);
    sensitive << ( ic_reg_199 );

    SC_METHOD(thread_tmp_39_fu_532_p1);
    sensitive << ( w_conv3_load_reg_645 );
    sensitive << ( ap_CS_fsm_state9 );

    SC_METHOD(thread_tmp_39_fu_532_p2);
    sensitive << ( buf_pool2_load_reg_640 );
    sensitive << ( tmp_39_fu_532_p1 );

    SC_METHOD(thread_tmp_43_fu_397_p1);
    sensitive << ( sum_reg_164 );

    SC_METHOD(thread_tmp_44_fu_464_p1);
    sensitive << ( tmp_74_fu_459_p2 );

    SC_METHOD(thread_tmp_65_fu_258_p2);
    sensitive << ( p_shl_cast_fu_242_p1 );
    sensitive << ( p_shl1_cast_fu_254_p1 );

    SC_METHOD(thread_tmp_66_fu_280_p2);
    sensitive << ( tmp_65_reg_550 );
    sensitive << ( tmp_cast_fu_276_p1 );

    SC_METHOD(thread_tmp_67_fu_309_p2);
    sensitive << ( tmp_100_cast_reg_563 );
    sensitive << ( tmp_29_cast_fu_305_p1 );

    SC_METHOD(thread_tmp_68_fu_341_p3);
    sensitive << ( tmp_32_fu_335_p2 );

    SC_METHOD(thread_tmp_69_fu_353_p3);
    sensitive << ( tmp_32_fu_335_p2 );

    SC_METHOD(thread_tmp_70_fu_365_p2);
    sensitive << ( p_shl3_cast_fu_349_p1 );
    sensitive << ( p_shl4_cast_fu_361_p1 );

    SC_METHOD(thread_tmp_71_fu_375_p3);
    sensitive << ( kr_reg_153 );

    SC_METHOD(thread_tmp_72_fu_387_p2);
    sensitive << ( p_shl2_cast_fu_383_p1 );
    sensitive << ( tmp_34_cast_fu_371_p1 );

    SC_METHOD(thread_tmp_73_fu_442_p2);
    sensitive << ( tmp_70_reg_594 );
    sensitive << ( tmp_36_cast_fu_438_p1 );

    SC_METHOD(thread_tmp_74_fu_459_p2);
    sensitive << ( tmp_106_cast_reg_599 );
    sensitive << ( tmp_37_cast_fu_455_p1 );

    SC_METHOD(thread_tmp_75_fu_468_p3);
    sensitive << ( tmp_44_fu_464_p1 );

    SC_METHOD(thread_tmp_76_fu_496_p2);
    sensitive << ( tmp_109_cast_reg_612 );
    sensitive << ( tmp_38_cast_fu_492_p1 );

    SC_METHOD(thread_tmp_77_fu_506_p2);
    sensitive << ( tmp_75_reg_617 );
    sensitive << ( tmp_38_fu_488_p1 );

    SC_METHOD(thread_tmp_78_fu_519_p2);
    sensitive << ( tmp_29_cast_reg_576 );
    sensitive << ( tmp_116_cast_fu_511_p3 );

    SC_METHOD(thread_tmp_cast_fu_276_p1);
    sensitive << ( col_reg_130 );

    SC_METHOD(thread_tmp_fu_234_p3);
    sensitive << ( row_reg_118 );

    SC_METHOD(thread_tmp_s_fu_246_p3);
    sensitive << ( row_reg_118 );

    SC_METHOD(thread_w_conv3_address0);
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( tmp_117_cast_fu_524_p1 );

    SC_METHOD(thread_w_conv3_ce0);
    sensitive << ( ap_CS_fsm_state7 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( exitcond5_fu_222_p2 );
    sensitive << ( ap_CS_fsm_state3 );
    sensitive << ( exitcond4_fu_264_p2 );
    sensitive << ( ap_CS_fsm_state4 );
    sensitive << ( exitcond3_fu_293_p2 );
    sensitive << ( ap_CS_fsm_state5 );
    sensitive << ( exitcond2_fu_323_p2 );
    sensitive << ( ap_CS_fsm_state6 );
    sensitive << ( exitcond1_fu_420_p2 );
    sensitive << ( ap_CS_fsm_state7 );
    sensitive << ( exitcond_fu_476_p2 );

    ap_CS_fsm = "0000000001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "conv_layer3_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, output_r_address0, "(port)output_r_address0");
    sc_trace(mVcdFile, output_r_ce0, "(port)output_r_ce0");
    sc_trace(mVcdFile, output_r_we0, "(port)output_r_we0");
    sc_trace(mVcdFile, output_r_d0, "(port)output_r_d0");
    sc_trace(mVcdFile, buf_pool2_address0, "(port)buf_pool2_address0");
    sc_trace(mVcdFile, buf_pool2_ce0, "(port)buf_pool2_ce0");
    sc_trace(mVcdFile, buf_pool2_q0, "(port)buf_pool2_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, w_conv3_address0, "w_conv3_address0");
    sc_trace(mVcdFile, w_conv3_ce0, "w_conv3_ce0");
    sc_trace(mVcdFile, w_conv3_q0, "w_conv3_q0");
    sc_trace(mVcdFile, row_1_fu_228_p2, "row_1_fu_228_p2");
    sc_trace(mVcdFile, row_1_reg_545, "row_1_reg_545");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, tmp_65_fu_258_p2, "tmp_65_fu_258_p2");
    sc_trace(mVcdFile, tmp_65_reg_550, "tmp_65_reg_550");
    sc_trace(mVcdFile, exitcond5_fu_222_p2, "exitcond5_fu_222_p2");
    sc_trace(mVcdFile, col_1_fu_270_p2, "col_1_fu_270_p2");
    sc_trace(mVcdFile, col_1_reg_558, "col_1_reg_558");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, tmp_100_cast_fu_285_p3, "tmp_100_cast_fu_285_p3");
    sc_trace(mVcdFile, tmp_100_cast_reg_563, "tmp_100_cast_reg_563");
    sc_trace(mVcdFile, exitcond4_fu_264_p2, "exitcond4_fu_264_p2");
    sc_trace(mVcdFile, oc_2_fu_299_p2, "oc_2_fu_299_p2");
    sc_trace(mVcdFile, oc_2_reg_571, "oc_2_reg_571");
    sc_trace(mVcdFile, ap_CS_fsm_state4, "ap_CS_fsm_state4");
    sc_trace(mVcdFile, tmp_29_cast_fu_305_p1, "tmp_29_cast_fu_305_p1");
    sc_trace(mVcdFile, tmp_29_cast_reg_576, "tmp_29_cast_reg_576");
    sc_trace(mVcdFile, exitcond3_fu_293_p2, "exitcond3_fu_293_p2");
    sc_trace(mVcdFile, output_addr_reg_581, "output_addr_reg_581");
    sc_trace(mVcdFile, kr_1_fu_329_p2, "kr_1_fu_329_p2");
    sc_trace(mVcdFile, kr_1_reg_589, "kr_1_reg_589");
    sc_trace(mVcdFile, ap_CS_fsm_state5, "ap_CS_fsm_state5");
    sc_trace(mVcdFile, tmp_70_fu_365_p2, "tmp_70_fu_365_p2");
    sc_trace(mVcdFile, tmp_70_reg_594, "tmp_70_reg_594");
    sc_trace(mVcdFile, exitcond2_fu_323_p2, "exitcond2_fu_323_p2");
    sc_trace(mVcdFile, tmp_106_cast_fu_393_p1, "tmp_106_cast_fu_393_p1");
    sc_trace(mVcdFile, tmp_106_cast_reg_599, "tmp_106_cast_reg_599");
    sc_trace(mVcdFile, kc_1_fu_426_p2, "kc_1_fu_426_p2");
    sc_trace(mVcdFile, kc_1_reg_607, "kc_1_reg_607");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, tmp_109_cast_fu_447_p3, "tmp_109_cast_fu_447_p3");
    sc_trace(mVcdFile, tmp_109_cast_reg_612, "tmp_109_cast_reg_612");
    sc_trace(mVcdFile, exitcond1_fu_420_p2, "exitcond1_fu_420_p2");
    sc_trace(mVcdFile, tmp_75_fu_468_p3, "tmp_75_fu_468_p3");
    sc_trace(mVcdFile, tmp_75_reg_617, "tmp_75_reg_617");
    sc_trace(mVcdFile, ic_2_fu_482_p2, "ic_2_fu_482_p2");
    sc_trace(mVcdFile, ic_2_reg_625, "ic_2_reg_625");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, exitcond_fu_476_p2, "exitcond_fu_476_p2");
    sc_trace(mVcdFile, buf_pool2_load_reg_640, "buf_pool2_load_reg_640");
    sc_trace(mVcdFile, ap_CS_fsm_state8, "ap_CS_fsm_state8");
    sc_trace(mVcdFile, w_conv3_load_reg_645, "w_conv3_load_reg_645");
    sc_trace(mVcdFile, tmp_39_fu_532_p2, "tmp_39_fu_532_p2");
    sc_trace(mVcdFile, tmp_39_reg_650, "tmp_39_reg_650");
    sc_trace(mVcdFile, ap_CS_fsm_state9, "ap_CS_fsm_state9");
    sc_trace(mVcdFile, sum_4_fu_537_p2, "sum_4_fu_537_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, row_reg_118, "row_reg_118");
    sc_trace(mVcdFile, col_reg_130, "col_reg_130");
    sc_trace(mVcdFile, oc_reg_142, "oc_reg_142");
    sc_trace(mVcdFile, kr_reg_153, "kr_reg_153");
    sc_trace(mVcdFile, sum_reg_164, "sum_reg_164");
    sc_trace(mVcdFile, kc_reg_176, "kc_reg_176");
    sc_trace(mVcdFile, sum_1_reg_187, "sum_1_reg_187");
    sc_trace(mVcdFile, ic_reg_199, "ic_reg_199");
    sc_trace(mVcdFile, sum_2_reg_210, "sum_2_reg_210");
    sc_trace(mVcdFile, tmp_101_cast_fu_314_p1, "tmp_101_cast_fu_314_p1");
    sc_trace(mVcdFile, tmp_113_cast_fu_501_p1, "tmp_113_cast_fu_501_p1");
    sc_trace(mVcdFile, tmp_117_cast_fu_524_p1, "tmp_117_cast_fu_524_p1");
    sc_trace(mVcdFile, tmp_fu_234_p3, "tmp_fu_234_p3");
    sc_trace(mVcdFile, tmp_s_fu_246_p3, "tmp_s_fu_246_p3");
    sc_trace(mVcdFile, p_shl_cast_fu_242_p1, "p_shl_cast_fu_242_p1");
    sc_trace(mVcdFile, p_shl1_cast_fu_254_p1, "p_shl1_cast_fu_254_p1");
    sc_trace(mVcdFile, tmp_cast_fu_276_p1, "tmp_cast_fu_276_p1");
    sc_trace(mVcdFile, tmp_66_fu_280_p2, "tmp_66_fu_280_p2");
    sc_trace(mVcdFile, tmp_67_fu_309_p2, "tmp_67_fu_309_p2");
    sc_trace(mVcdFile, kr_cast5_fu_319_p1, "kr_cast5_fu_319_p1");
    sc_trace(mVcdFile, tmp_32_fu_335_p2, "tmp_32_fu_335_p2");
    sc_trace(mVcdFile, tmp_68_fu_341_p3, "tmp_68_fu_341_p3");
    sc_trace(mVcdFile, tmp_69_fu_353_p3, "tmp_69_fu_353_p3");
    sc_trace(mVcdFile, p_shl3_cast_fu_349_p1, "p_shl3_cast_fu_349_p1");
    sc_trace(mVcdFile, p_shl4_cast_fu_361_p1, "p_shl4_cast_fu_361_p1");
    sc_trace(mVcdFile, tmp_71_fu_375_p3, "tmp_71_fu_375_p3");
    sc_trace(mVcdFile, p_shl2_cast_fu_383_p1, "p_shl2_cast_fu_383_p1");
    sc_trace(mVcdFile, tmp_34_cast_fu_371_p1, "tmp_34_cast_fu_371_p1");
    sc_trace(mVcdFile, tmp_72_fu_387_p2, "tmp_72_fu_387_p2");
    sc_trace(mVcdFile, tmp_30_fu_401_p2, "tmp_30_fu_401_p2");
    sc_trace(mVcdFile, tmp_43_fu_397_p1, "tmp_43_fu_397_p1");
    sc_trace(mVcdFile, kc_cast3_fu_416_p1, "kc_cast3_fu_416_p1");
    sc_trace(mVcdFile, tmp_35_fu_432_p2, "tmp_35_fu_432_p2");
    sc_trace(mVcdFile, tmp_36_cast_fu_438_p1, "tmp_36_cast_fu_438_p1");
    sc_trace(mVcdFile, tmp_73_fu_442_p2, "tmp_73_fu_442_p2");
    sc_trace(mVcdFile, tmp_37_cast_fu_455_p1, "tmp_37_cast_fu_455_p1");
    sc_trace(mVcdFile, tmp_74_fu_459_p2, "tmp_74_fu_459_p2");
    sc_trace(mVcdFile, tmp_44_fu_464_p1, "tmp_44_fu_464_p1");
    sc_trace(mVcdFile, tmp_38_cast_fu_492_p1, "tmp_38_cast_fu_492_p1");
    sc_trace(mVcdFile, tmp_76_fu_496_p2, "tmp_76_fu_496_p2");
    sc_trace(mVcdFile, tmp_38_fu_488_p1, "tmp_38_fu_488_p1");
    sc_trace(mVcdFile, tmp_77_fu_506_p2, "tmp_77_fu_506_p2");
    sc_trace(mVcdFile, tmp_116_cast_fu_511_p3, "tmp_116_cast_fu_511_p3");
    sc_trace(mVcdFile, tmp_78_fu_519_p2, "tmp_78_fu_519_p2");
    sc_trace(mVcdFile, tmp_39_fu_532_p1, "tmp_39_fu_532_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
}

conv_layer3::~conv_layer3() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete w_conv3_U;
}

void conv_layer3::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
         esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_1))) {
        col_reg_130 = col_1_reg_558.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
                esl_seteq<1,1,1>(exitcond5_fu_222_p2.read(), ap_const_lv1_0))) {
        col_reg_130 = ap_const_lv4_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        ic_reg_199 = ic_2_reg_625.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_420_p2.read()))) {
        ic_reg_199 = ap_const_lv5_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_476_p2.read(), ap_const_lv1_1))) {
        kc_reg_176 = kc_1_reg_607.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_323_p2.read()))) {
        kc_reg_176 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_420_p2.read(), ap_const_lv1_1))) {
        kr_reg_153 = kr_1_reg_589.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_293_p2.read()))) {
        kr_reg_153 = ap_const_lv2_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_323_p2.read(), ap_const_lv1_1))) {
        oc_reg_142 = oc_2_reg_571.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_264_p2.read()))) {
        oc_reg_142 = ap_const_lv6_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && 
         esl_seteq<1,1,1>(exitcond4_fu_264_p2.read(), ap_const_lv1_1))) {
        row_reg_118 = row_1_reg_545.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        row_reg_118 = ap_const_lv4_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && 
         esl_seteq<1,1,1>(exitcond_fu_476_p2.read(), ap_const_lv1_1))) {
        sum_1_reg_187 = sum_2_reg_210.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_323_p2.read()))) {
        sum_1_reg_187 = sum_reg_164.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        sum_2_reg_210 = sum_4_fu_537_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_420_p2.read()))) {
        sum_2_reg_210 = sum_1_reg_187.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && 
         esl_seteq<1,1,1>(exitcond1_fu_420_p2.read(), ap_const_lv1_1))) {
        sum_reg_164 = sum_1_reg_187.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && 
                esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_293_p2.read()))) {
        sum_reg_164 = ap_const_lv32_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state8.read())) {
        buf_pool2_load_reg_640 = buf_pool2_q0.read();
        w_conv3_load_reg_645 = w_conv3_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        col_1_reg_558 = col_1_fu_270_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        ic_2_reg_625 = ic_2_fu_482_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        kc_1_reg_607 = kc_1_fu_426_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        kr_1_reg_589 = kr_1_fu_329_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read())) {
        oc_2_reg_571 = oc_2_fu_299_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond3_fu_293_p2.read()))) {
        output_addr_reg_581 =  (sc_lv<13>) (tmp_101_cast_fu_314_p1.read());
        tmp_29_cast_reg_576 = tmp_29_cast_fu_305_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        row_1_reg_545 = row_1_fu_228_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond4_fu_264_p2.read()))) {
        tmp_100_cast_reg_563 = tmp_100_cast_fu_285_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond2_fu_323_p2.read()))) {
        tmp_106_cast_reg_599 = tmp_106_cast_fu_393_p1.read();
        tmp_70_reg_594 = tmp_70_fu_365_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond1_fu_420_p2.read()))) {
        tmp_109_cast_reg_612 = tmp_109_cast_fu_447_p3.read();
        tmp_75_reg_617 = tmp_75_fu_468_p3.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state9.read())) {
        tmp_39_reg_650 = tmp_39_fu_532_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond5_fu_222_p2.read(), ap_const_lv1_0))) {
        tmp_65_reg_550 = tmp_65_fu_258_p2.read();
    }
}

void conv_layer3::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void conv_layer3::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[9];
}

void conv_layer3::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void conv_layer3::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void conv_layer3::thread_ap_CS_fsm_state4() {
    ap_CS_fsm_state4 = ap_CS_fsm.read()[3];
}

void conv_layer3::thread_ap_CS_fsm_state5() {
    ap_CS_fsm_state5 = ap_CS_fsm.read()[4];
}

void conv_layer3::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void conv_layer3::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void conv_layer3::thread_ap_CS_fsm_state8() {
    ap_CS_fsm_state8 = ap_CS_fsm.read()[7];
}

void conv_layer3::thread_ap_CS_fsm_state9() {
    ap_CS_fsm_state9 = ap_CS_fsm.read()[8];
}

void conv_layer3::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
          esl_seteq<1,1,1>(exitcond5_fu_222_p2.read(), ap_const_lv1_1)))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void conv_layer3::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void conv_layer3::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(exitcond5_fu_222_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void conv_layer3::thread_buf_pool2_address0() {
    buf_pool2_address0 =  (sc_lv<12>) (tmp_113_cast_fu_501_p1.read());
}

void conv_layer3::thread_buf_pool2_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        buf_pool2_ce0 = ap_const_logic_1;
    } else {
        buf_pool2_ce0 = ap_const_logic_0;
    }
}

void conv_layer3::thread_col_1_fu_270_p2() {
    col_1_fu_270_p2 = (!col_reg_130.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(col_reg_130.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv_layer3::thread_exitcond1_fu_420_p2() {
    exitcond1_fu_420_p2 = (!kc_reg_176.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(kc_reg_176.read() == ap_const_lv2_3);
}

void conv_layer3::thread_exitcond2_fu_323_p2() {
    exitcond2_fu_323_p2 = (!kr_reg_153.read().is_01() || !ap_const_lv2_3.is_01())? sc_lv<1>(): sc_lv<1>(kr_reg_153.read() == ap_const_lv2_3);
}

void conv_layer3::thread_exitcond3_fu_293_p2() {
    exitcond3_fu_293_p2 = (!oc_reg_142.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(oc_reg_142.read() == ap_const_lv6_20);
}

void conv_layer3::thread_exitcond4_fu_264_p2() {
    exitcond4_fu_264_p2 = (!col_reg_130.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(col_reg_130.read() == ap_const_lv4_C);
}

void conv_layer3::thread_exitcond5_fu_222_p2() {
    exitcond5_fu_222_p2 = (!row_reg_118.read().is_01() || !ap_const_lv4_C.is_01())? sc_lv<1>(): sc_lv<1>(row_reg_118.read() == ap_const_lv4_C);
}

void conv_layer3::thread_exitcond_fu_476_p2() {
    exitcond_fu_476_p2 = (!ic_reg_199.read().is_01() || !ap_const_lv5_10.is_01())? sc_lv<1>(): sc_lv<1>(ic_reg_199.read() == ap_const_lv5_10);
}

void conv_layer3::thread_ic_2_fu_482_p2() {
    ic_2_fu_482_p2 = (!ic_reg_199.read().is_01() || !ap_const_lv5_1.is_01())? sc_lv<5>(): (sc_biguint<5>(ic_reg_199.read()) + sc_biguint<5>(ap_const_lv5_1));
}

void conv_layer3::thread_kc_1_fu_426_p2() {
    kc_1_fu_426_p2 = (!kc_reg_176.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(kc_reg_176.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_layer3::thread_kc_cast3_fu_416_p1() {
    kc_cast3_fu_416_p1 = esl_zext<4,2>(kc_reg_176.read());
}

void conv_layer3::thread_kr_1_fu_329_p2() {
    kr_1_fu_329_p2 = (!kr_reg_153.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(kr_reg_153.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void conv_layer3::thread_kr_cast5_fu_319_p1() {
    kr_cast5_fu_319_p1 = esl_zext<4,2>(kr_reg_153.read());
}

void conv_layer3::thread_oc_2_fu_299_p2() {
    oc_2_fu_299_p2 = (!oc_reg_142.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(oc_reg_142.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void conv_layer3::thread_output_r_address0() {
    output_r_address0 = output_addr_reg_581.read();
}

void conv_layer3::thread_output_r_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read())) {
        output_r_ce0 = ap_const_logic_1;
    } else {
        output_r_ce0 = ap_const_logic_0;
    }
}

void conv_layer3::thread_output_r_d0() {
    output_r_d0 = (!tmp_30_fu_401_p2.read()[0].is_01())? sc_lv<31>(): ((tmp_30_fu_401_p2.read()[0].to_bool())? tmp_43_fu_397_p1.read(): ap_const_lv31_0);
}

void conv_layer3::thread_output_r_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && 
         esl_seteq<1,1,1>(exitcond2_fu_323_p2.read(), ap_const_lv1_1))) {
        output_r_we0 = ap_const_logic_1;
    } else {
        output_r_we0 = ap_const_logic_0;
    }
}

void conv_layer3::thread_p_shl1_cast_fu_254_p1() {
    p_shl1_cast_fu_254_p1 = esl_zext<9,6>(tmp_s_fu_246_p3.read());
}

void conv_layer3::thread_p_shl2_cast_fu_383_p1() {
    p_shl2_cast_fu_383_p1 = esl_zext<5,4>(tmp_71_fu_375_p3.read());
}

void conv_layer3::thread_p_shl3_cast_fu_349_p1() {
    p_shl3_cast_fu_349_p1 = esl_zext<9,8>(tmp_68_fu_341_p3.read());
}

void conv_layer3::thread_p_shl4_cast_fu_361_p1() {
    p_shl4_cast_fu_361_p1 = esl_zext<9,5>(tmp_69_fu_353_p3.read());
}

void conv_layer3::thread_p_shl_cast_fu_242_p1() {
    p_shl_cast_fu_242_p1 = esl_zext<9,8>(tmp_fu_234_p3.read());
}

void conv_layer3::thread_row_1_fu_228_p2() {
    row_1_fu_228_p2 = (!row_reg_118.read().is_01() || !ap_const_lv4_1.is_01())? sc_lv<4>(): (sc_biguint<4>(row_reg_118.read()) + sc_biguint<4>(ap_const_lv4_1));
}

void conv_layer3::thread_sum_4_fu_537_p2() {
    sum_4_fu_537_p2 = (!tmp_39_reg_650.read().is_01() || !sum_2_reg_210.read().is_01())? sc_lv<32>(): (sc_biguint<32>(tmp_39_reg_650.read()) + sc_biguint<32>(sum_2_reg_210.read()));
}

void conv_layer3::thread_tmp_100_cast_fu_285_p3() {
    tmp_100_cast_fu_285_p3 = esl_concat<9,5>(tmp_66_fu_280_p2.read(), ap_const_lv5_0);
}

void conv_layer3::thread_tmp_101_cast_fu_314_p1() {
    tmp_101_cast_fu_314_p1 = esl_zext<64,14>(tmp_67_fu_309_p2.read());
}

void conv_layer3::thread_tmp_106_cast_fu_393_p1() {
    tmp_106_cast_fu_393_p1 = esl_sext<6,5>(tmp_72_fu_387_p2.read());
}

void conv_layer3::thread_tmp_109_cast_fu_447_p3() {
    tmp_109_cast_fu_447_p3 = esl_concat<9,4>(tmp_73_fu_442_p2.read(), ap_const_lv4_0);
}

void conv_layer3::thread_tmp_113_cast_fu_501_p1() {
    tmp_113_cast_fu_501_p1 = esl_zext<64,13>(tmp_76_fu_496_p2.read());
}

void conv_layer3::thread_tmp_116_cast_fu_511_p3() {
    tmp_116_cast_fu_511_p3 = esl_concat<9,5>(tmp_77_fu_506_p2.read(), ap_const_lv5_0);
}

void conv_layer3::thread_tmp_117_cast_fu_524_p1() {
    tmp_117_cast_fu_524_p1 = esl_zext<64,14>(tmp_78_fu_519_p2.read());
}

void conv_layer3::thread_tmp_29_cast_fu_305_p1() {
    tmp_29_cast_fu_305_p1 = esl_zext<14,6>(oc_reg_142.read());
}

void conv_layer3::thread_tmp_30_fu_401_p2() {
    tmp_30_fu_401_p2 = (!sum_reg_164.read().is_01() || !ap_const_lv32_0.is_01())? sc_lv<1>(): (sc_bigint<32>(sum_reg_164.read()) > sc_bigint<32>(ap_const_lv32_0));
}

void conv_layer3::thread_tmp_32_fu_335_p2() {
    tmp_32_fu_335_p2 = (!kr_cast5_fu_319_p1.read().is_01() || !row_reg_118.read().is_01())? sc_lv<4>(): (sc_biguint<4>(kr_cast5_fu_319_p1.read()) + sc_biguint<4>(row_reg_118.read()));
}

void conv_layer3::thread_tmp_34_cast_fu_371_p1() {
    tmp_34_cast_fu_371_p1 = esl_zext<5,2>(kr_reg_153.read());
}

void conv_layer3::thread_tmp_35_fu_432_p2() {
    tmp_35_fu_432_p2 = (!col_reg_130.read().is_01() || !kc_cast3_fu_416_p1.read().is_01())? sc_lv<4>(): (sc_biguint<4>(col_reg_130.read()) + sc_biguint<4>(kc_cast3_fu_416_p1.read()));
}

void conv_layer3::thread_tmp_36_cast_fu_438_p1() {
    tmp_36_cast_fu_438_p1 = esl_zext<9,4>(tmp_35_fu_432_p2.read());
}

void conv_layer3::thread_tmp_37_cast_fu_455_p1() {
    tmp_37_cast_fu_455_p1 = esl_zext<6,2>(kc_reg_176.read());
}

void conv_layer3::thread_tmp_38_cast_fu_492_p1() {
    tmp_38_cast_fu_492_p1 = esl_zext<13,5>(ic_reg_199.read());
}

void conv_layer3::thread_tmp_38_fu_488_p1() {
    tmp_38_fu_488_p1 = esl_zext<9,5>(ic_reg_199.read());
}

void conv_layer3::thread_tmp_39_fu_532_p1() {
    tmp_39_fu_532_p1 = w_conv3_load_reg_645.read();
}

void conv_layer3::thread_tmp_39_fu_532_p2() {
    tmp_39_fu_532_p2 = (!buf_pool2_load_reg_640.read().is_01() || !tmp_39_fu_532_p1.read().is_01())? sc_lv<32>(): sc_bigint<32>(buf_pool2_load_reg_640.read()) * sc_bigint<5>(tmp_39_fu_532_p1.read());
}

void conv_layer3::thread_tmp_43_fu_397_p1() {
    tmp_43_fu_397_p1 = sum_reg_164.read().range(31-1, 0);
}

void conv_layer3::thread_tmp_44_fu_464_p1() {
    tmp_44_fu_464_p1 = tmp_74_fu_459_p2.read().range(5-1, 0);
}

void conv_layer3::thread_tmp_65_fu_258_p2() {
    tmp_65_fu_258_p2 = (!p_shl_cast_fu_242_p1.read().is_01() || !p_shl1_cast_fu_254_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl_cast_fu_242_p1.read()) - sc_biguint<9>(p_shl1_cast_fu_254_p1.read()));
}

void conv_layer3::thread_tmp_66_fu_280_p2() {
    tmp_66_fu_280_p2 = (!tmp_cast_fu_276_p1.read().is_01() || !tmp_65_reg_550.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_cast_fu_276_p1.read()) + sc_biguint<9>(tmp_65_reg_550.read()));
}

void conv_layer3::thread_tmp_67_fu_309_p2() {
    tmp_67_fu_309_p2 = (!tmp_100_cast_reg_563.read().is_01() || !tmp_29_cast_fu_305_p1.read().is_01())? sc_lv<14>(): (sc_biguint<14>(tmp_100_cast_reg_563.read()) + sc_biguint<14>(tmp_29_cast_fu_305_p1.read()));
}

void conv_layer3::thread_tmp_68_fu_341_p3() {
    tmp_68_fu_341_p3 = esl_concat<4,4>(tmp_32_fu_335_p2.read(), ap_const_lv4_0);
}

void conv_layer3::thread_tmp_69_fu_353_p3() {
    tmp_69_fu_353_p3 = esl_concat<4,1>(tmp_32_fu_335_p2.read(), ap_const_lv1_0);
}

void conv_layer3::thread_tmp_70_fu_365_p2() {
    tmp_70_fu_365_p2 = (!p_shl3_cast_fu_349_p1.read().is_01() || !p_shl4_cast_fu_361_p1.read().is_01())? sc_lv<9>(): (sc_biguint<9>(p_shl3_cast_fu_349_p1.read()) - sc_biguint<9>(p_shl4_cast_fu_361_p1.read()));
}

void conv_layer3::thread_tmp_71_fu_375_p3() {
    tmp_71_fu_375_p3 = esl_concat<2,2>(kr_reg_153.read(), ap_const_lv2_0);
}

void conv_layer3::thread_tmp_72_fu_387_p2() {
    tmp_72_fu_387_p2 = (!p_shl2_cast_fu_383_p1.read().is_01() || !tmp_34_cast_fu_371_p1.read().is_01())? sc_lv<5>(): (sc_biguint<5>(p_shl2_cast_fu_383_p1.read()) - sc_biguint<5>(tmp_34_cast_fu_371_p1.read()));
}

void conv_layer3::thread_tmp_73_fu_442_p2() {
    tmp_73_fu_442_p2 = (!tmp_36_cast_fu_438_p1.read().is_01() || !tmp_70_reg_594.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_36_cast_fu_438_p1.read()) + sc_biguint<9>(tmp_70_reg_594.read()));
}

void conv_layer3::thread_tmp_74_fu_459_p2() {
    tmp_74_fu_459_p2 = (!tmp_37_cast_fu_455_p1.read().is_01() || !tmp_106_cast_reg_599.read().is_01())? sc_lv<6>(): (sc_biguint<6>(tmp_37_cast_fu_455_p1.read()) + sc_bigint<6>(tmp_106_cast_reg_599.read()));
}

void conv_layer3::thread_tmp_75_fu_468_p3() {
    tmp_75_fu_468_p3 = esl_concat<5,4>(tmp_44_fu_464_p1.read(), ap_const_lv4_0);
}

void conv_layer3::thread_tmp_76_fu_496_p2() {
    tmp_76_fu_496_p2 = (!tmp_38_cast_fu_492_p1.read().is_01() || !tmp_109_cast_reg_612.read().is_01())? sc_lv<13>(): (sc_biguint<13>(tmp_38_cast_fu_492_p1.read()) + sc_biguint<13>(tmp_109_cast_reg_612.read()));
}

void conv_layer3::thread_tmp_77_fu_506_p2() {
    tmp_77_fu_506_p2 = (!tmp_38_fu_488_p1.read().is_01() || !tmp_75_reg_617.read().is_01())? sc_lv<9>(): (sc_biguint<9>(tmp_38_fu_488_p1.read()) + sc_biguint<9>(tmp_75_reg_617.read()));
}

void conv_layer3::thread_tmp_78_fu_519_p2() {
    tmp_78_fu_519_p2 = (!tmp_29_cast_reg_576.read().is_01() || !tmp_116_cast_fu_511_p3.read().is_01())? sc_lv<14>(): (sc_biguint<14>(tmp_29_cast_reg_576.read()) + sc_biguint<14>(tmp_116_cast_fu_511_p3.read()));
}

void conv_layer3::thread_tmp_cast_fu_276_p1() {
    tmp_cast_fu_276_p1 = esl_zext<9,4>(col_reg_130.read());
}

void conv_layer3::thread_tmp_fu_234_p3() {
    tmp_fu_234_p3 = esl_concat<4,4>(row_reg_118.read(), ap_const_lv4_0);
}

void conv_layer3::thread_tmp_s_fu_246_p3() {
    tmp_s_fu_246_p3 = esl_concat<4,2>(row_reg_118.read(), ap_const_lv2_0);
}

void conv_layer3::thread_w_conv3_address0() {
    w_conv3_address0 =  (sc_lv<13>) (tmp_117_cast_fu_524_p1.read());
}

void conv_layer3::thread_w_conv3_ce0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read())) {
        w_conv3_ce0 = ap_const_logic_1;
    } else {
        w_conv3_ce0 = ap_const_logic_0;
    }
}

void conv_layer3::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(exitcond5_fu_222_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read()) && esl_seteq<1,1,1>(exitcond4_fu_264_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state4;
            }
            break;
        case 8 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state4.read()) && esl_seteq<1,1,1>(exitcond3_fu_293_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state3;
            } else {
                ap_NS_fsm = ap_ST_fsm_state5;
            }
            break;
        case 16 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state5.read()) && esl_seteq<1,1,1>(exitcond2_fu_323_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state4;
            } else {
                ap_NS_fsm = ap_ST_fsm_state6;
            }
            break;
        case 32 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read()) && esl_seteq<1,1,1>(exitcond1_fu_420_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state5;
            } else {
                ap_NS_fsm = ap_ST_fsm_state7;
            }
            break;
        case 64 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state7.read()) && esl_seteq<1,1,1>(exitcond_fu_476_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state6;
            } else {
                ap_NS_fsm = ap_ST_fsm_state8;
            }
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        default : 
            ap_NS_fsm = "XXXXXXXXXX";
            break;
    }
}

}

