// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _maxpool_layer1_HH_
#define _maxpool_layer1_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct maxpool_layer1 : public sc_module {
    // Port declarations 13
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<13> > output_r_address0;
    sc_out< sc_logic > output_r_ce0;
    sc_out< sc_logic > output_r_we0;
    sc_out< sc_lv<32> > output_r_d0;
    sc_out< sc_lv<15> > buf_conv1_address0;
    sc_out< sc_logic > buf_conv1_ce0;
    sc_in< sc_lv<31> > buf_conv1_q0;


    // Module declarations
    maxpool_layer1(sc_module_name name);
    SC_HAS_PROCESS(maxpool_layer1);

    ~maxpool_layer1();

    sc_trace_file* mVcdFile;

    sc_signal< sc_lv<9> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<4> > ch_2_fu_202_p2;
    sc_signal< sc_lv<4> > ch_2_reg_512;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<16> > tmp_cast5_fu_208_p1;
    sc_signal< sc_lv<16> > tmp_cast5_reg_517;
    sc_signal< sc_lv<1> > exitcond4_fu_196_p2;
    sc_signal< sc_lv<14> > tmp_cast_fu_212_p1;
    sc_signal< sc_lv<14> > tmp_cast_reg_522;
    sc_signal< sc_lv<5> > out_row_2_fu_222_p2;
    sc_signal< sc_lv<5> > out_row_2_reg_530;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<6> > in_row_fu_228_p3;
    sc_signal< sc_lv<6> > in_row_reg_535;
    sc_signal< sc_lv<1> > exitcond3_fu_216_p2;
    sc_signal< sc_lv<14> > tmp_33_cast_fu_266_p1;
    sc_signal< sc_lv<14> > tmp_33_cast_reg_540;
    sc_signal< sc_lv<11> > tmp_26_fu_286_p2;
    sc_signal< sc_lv<11> > tmp_26_reg_545;
    sc_signal< sc_lv<5> > out_col_2_fu_298_p2;
    sc_signal< sc_lv<5> > out_col_2_reg_553;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<6> > in_col_fu_304_p3;
    sc_signal< sc_lv<6> > in_col_reg_558;
    sc_signal< sc_lv<1> > exitcond2_fu_292_p2;
    sc_signal< sc_lv<32> > maxvalue_fu_362_p1;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<2> > pool_row_2_fu_376_p2;
    sc_signal< sc_lv<2> > pool_row_2_reg_576;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<13> > tmp_36_fu_411_p2;
    sc_signal< sc_lv<13> > tmp_36_reg_581;
    sc_signal< sc_lv<1> > exitcond1_fu_370_p2;
    sc_signal< sc_lv<2> > pool_col_2_fu_454_p2;
    sc_signal< sc_lv<2> > pool_col_2_reg_589;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<16> > tmp_38_fu_482_p2;
    sc_signal< sc_lv<16> > tmp_38_reg_594;
    sc_signal< sc_lv<1> > exitcond_fu_448_p2;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<32> > value_0_maxvalue_1_fu_501_p3;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<4> > ch_reg_116;
    sc_signal< sc_lv<5> > out_row_reg_128;
    sc_signal< sc_lv<5> > out_col_reg_139;
    sc_signal< sc_lv<32> > maxvalue4_reg_151;
    sc_signal< sc_lv<2> > pool_row_reg_162;
    sc_signal< sc_lv<32> > maxvalue_1_reg_173;
    sc_signal< sc_lv<2> > pool_col_reg_185;
    sc_signal< sc_lv<64> > tmp_31_fu_357_p1;
    sc_signal< sc_lv<64> > tmp_45_cast_fu_439_p1;
    sc_signal< sc_lv<64> > tmp_52_cast_fu_487_p1;
    sc_signal< sc_lv<12> > tmp_22_fu_236_p3;
    sc_signal< sc_lv<7> > tmp_23_fu_248_p3;
    sc_signal< sc_lv<13> > p_shl1_cast_fu_244_p1;
    sc_signal< sc_lv<13> > p_shl2_cast_fu_256_p1;
    sc_signal< sc_lv<13> > tmp_24_fu_260_p2;
    sc_signal< sc_lv<10> > tmp_25_fu_274_p3;
    sc_signal< sc_lv<11> > p_shl_cast_fu_282_p1;
    sc_signal< sc_lv<11> > tmp_5_cast_fu_270_p1;
    sc_signal< sc_lv<14> > tmp_6_cast_fu_312_p1;
    sc_signal< sc_lv<14> > tmp_27_fu_316_p2;
    sc_signal< sc_lv<1> > tmp_fu_321_p1;
    sc_signal< sc_lv<4> > tmp_28_fu_325_p3;
    sc_signal< sc_lv<13> > tmp_21_fu_339_p4;
    sc_signal< sc_lv<4> > tmp_29_fu_333_p2;
    sc_signal< sc_lv<17> > tmp_30_fu_349_p3;
    sc_signal< sc_lv<6> > pool_row_cast2_fu_366_p1;
    sc_signal< sc_lv<6> > tmp_8_fu_382_p2;
    sc_signal< sc_lv<12> > tmp_34_fu_387_p3;
    sc_signal< sc_lv<7> > tmp_35_fu_399_p3;
    sc_signal< sc_lv<13> > p_shl3_cast_fu_395_p1;
    sc_signal< sc_lv<13> > p_shl4_cast_fu_407_p1;
    sc_signal< sc_lv<11> > tmp_7_cast_fu_417_p1;
    sc_signal< sc_lv<11> > tmp_32_fu_421_p2;
    sc_signal< sc_lv<14> > tmp_44_cast_fu_426_p3;
    sc_signal< sc_lv<14> > tmp_33_fu_434_p2;
    sc_signal< sc_lv<6> > pool_col_cast1_fu_444_p1;
    sc_signal< sc_lv<6> > tmp_1_fu_460_p2;
    sc_signal< sc_lv<13> > tmp_2_cast_fu_465_p1;
    sc_signal< sc_lv<13> > tmp_37_fu_469_p2;
    sc_signal< sc_lv<16> > tmp_51_cast_fu_474_p3;
    sc_signal< sc_lv<32> > maxvalue_5_fu_491_p1;
    sc_signal< sc_lv<1> > tmp_3_fu_495_p2;
    sc_signal< sc_lv<9> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<9> ap_ST_fsm_state1;
    static const sc_lv<9> ap_ST_fsm_state2;
    static const sc_lv<9> ap_ST_fsm_state3;
    static const sc_lv<9> ap_ST_fsm_state4;
    static const sc_lv<9> ap_ST_fsm_state5;
    static const sc_lv<9> ap_ST_fsm_state6;
    static const sc_lv<9> ap_ST_fsm_state7;
    static const sc_lv<9> ap_ST_fsm_state8;
    static const sc_lv<9> ap_ST_fsm_state9;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<1> ap_const_lv1_0;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<5> ap_const_lv5_0;
    static const sc_lv<2> ap_const_lv2_0;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<5> ap_const_lv5_1F;
    static const sc_lv<5> ap_const_lv5_1;
    static const sc_lv<7> ap_const_lv7_0;
    static const sc_lv<3> ap_const_lv3_0;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<2> ap_const_lv2_2;
    static const sc_lv<2> ap_const_lv2_1;
    static const sc_lv<6> ap_const_lv6_0;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_buf_conv1_address0();
    void thread_buf_conv1_ce0();
    void thread_ch_2_fu_202_p2();
    void thread_exitcond1_fu_370_p2();
    void thread_exitcond2_fu_292_p2();
    void thread_exitcond3_fu_216_p2();
    void thread_exitcond4_fu_196_p2();
    void thread_exitcond_fu_448_p2();
    void thread_in_col_fu_304_p3();
    void thread_in_row_fu_228_p3();
    void thread_maxvalue_5_fu_491_p1();
    void thread_maxvalue_fu_362_p1();
    void thread_out_col_2_fu_298_p2();
    void thread_out_row_2_fu_222_p2();
    void thread_output_r_address0();
    void thread_output_r_ce0();
    void thread_output_r_d0();
    void thread_output_r_we0();
    void thread_p_shl1_cast_fu_244_p1();
    void thread_p_shl2_cast_fu_256_p1();
    void thread_p_shl3_cast_fu_395_p1();
    void thread_p_shl4_cast_fu_407_p1();
    void thread_p_shl_cast_fu_282_p1();
    void thread_pool_col_2_fu_454_p2();
    void thread_pool_col_cast1_fu_444_p1();
    void thread_pool_row_2_fu_376_p2();
    void thread_pool_row_cast2_fu_366_p1();
    void thread_tmp_1_fu_460_p2();
    void thread_tmp_21_fu_339_p4();
    void thread_tmp_22_fu_236_p3();
    void thread_tmp_23_fu_248_p3();
    void thread_tmp_24_fu_260_p2();
    void thread_tmp_25_fu_274_p3();
    void thread_tmp_26_fu_286_p2();
    void thread_tmp_27_fu_316_p2();
    void thread_tmp_28_fu_325_p3();
    void thread_tmp_29_fu_333_p2();
    void thread_tmp_2_cast_fu_465_p1();
    void thread_tmp_30_fu_349_p3();
    void thread_tmp_31_fu_357_p1();
    void thread_tmp_32_fu_421_p2();
    void thread_tmp_33_cast_fu_266_p1();
    void thread_tmp_33_fu_434_p2();
    void thread_tmp_34_fu_387_p3();
    void thread_tmp_35_fu_399_p3();
    void thread_tmp_36_fu_411_p2();
    void thread_tmp_37_fu_469_p2();
    void thread_tmp_38_fu_482_p2();
    void thread_tmp_3_fu_495_p2();
    void thread_tmp_44_cast_fu_426_p3();
    void thread_tmp_45_cast_fu_439_p1();
    void thread_tmp_51_cast_fu_474_p3();
    void thread_tmp_52_cast_fu_487_p1();
    void thread_tmp_5_cast_fu_270_p1();
    void thread_tmp_6_cast_fu_312_p1();
    void thread_tmp_7_cast_fu_417_p1();
    void thread_tmp_8_fu_382_p2();
    void thread_tmp_cast5_fu_208_p1();
    void thread_tmp_cast_fu_212_p1();
    void thread_tmp_fu_321_p1();
    void thread_value_0_maxvalue_1_fu_501_p3();
    void thread_ap_NS_fsm();
};

}

using namespace ap_rtl;

#endif
