// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module decode (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        output_r_address0,
        output_r_ce0,
        output_r_we0,
        output_r_d0,
        output_r_address1,
        output_r_ce1,
        output_r_we1,
        output_r_d1,
        buf_det_address0,
        buf_det_ce0,
        buf_det_q0,
        buf_det_address1,
        buf_det_ce1,
        buf_det_q1
);

parameter    ap_ST_fsm_state1 = 9'd1;
parameter    ap_ST_fsm_state2 = 9'd2;
parameter    ap_ST_fsm_state3 = 9'd4;
parameter    ap_ST_fsm_state4 = 9'd8;
parameter    ap_ST_fsm_state5 = 9'd16;
parameter    ap_ST_fsm_state6 = 9'd32;
parameter    ap_ST_fsm_state7 = 9'd64;
parameter    ap_ST_fsm_state8 = 9'd128;
parameter    ap_ST_fsm_state9 = 9'd256;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] output_r_address0;
output   output_r_ce0;
output   output_r_we0;
output  [31:0] output_r_d0;
output  [9:0] output_r_address1;
output   output_r_ce1;
output   output_r_we1;
output  [31:0] output_r_d1;
output  [9:0] buf_det_address0;
output   buf_det_ce0;
input  [31:0] buf_det_q0;
output  [9:0] buf_det_address1;
output   buf_det_ce1;
input  [31:0] buf_det_q1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[9:0] output_r_address0;
reg output_r_ce0;
reg output_r_we0;
reg[31:0] output_r_d0;
reg[9:0] output_r_address1;
reg output_r_ce1;
reg output_r_we1;
reg[31:0] output_r_d1;
reg[9:0] buf_det_address0;
reg buf_det_ce0;
reg[9:0] buf_det_address1;
reg buf_det_ce1;

(* fsm_encoding = "none" *) reg   [8:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [4:0] sigmoid_lut_address0;
reg    sigmoid_lut_ce0;
wire   [9:0] sigmoid_lut_q0;
wire   [3:0] gy_1_fu_271_p2;
reg   [3:0] gy_1_reg_630;
wire    ap_CS_fsm_state2;
wire   [7:0] tmp_75_cast_fu_285_p1;
reg   [7:0] tmp_75_cast_reg_635;
wire   [0:0] exitcond3_fu_265_p2;
wire   [3:0] gx_1_fu_295_p2;
reg   [3:0] gx_1_reg_643;
wire    ap_CS_fsm_state3;
wire   [7:0] tmp_s_fu_305_p2;
reg   [7:0] tmp_s_reg_648;
wire   [0:0] exitcond2_fu_289_p2;
wire   [11:0] tmp_78_cast_fu_310_p3;
reg   [11:0] tmp_78_cast_reg_657;
wire   [63:0] tmp_52_fu_326_p1;
reg   [63:0] tmp_52_reg_662;
wire   [1:0] b_1_fu_336_p2;
reg   [1:0] b_1_reg_670;
wire    ap_CS_fsm_state4;
wire   [3:0] offset_fu_346_p3;
reg   [3:0] offset_reg_675;
wire   [0:0] exitcond1_fu_330_p2;
wire   [60:0] tmp_34_fu_395_p1;
reg   [60:0] tmp_34_reg_693;
wire    ap_CS_fsm_state5;
wire   [8:0] tmp_35_fu_399_p1;
reg   [8:0] tmp_35_reg_698;
reg   [31:0] buf_det_load_4_reg_713;
wire   [11:0] tmp_85_cast_fu_444_p3;
reg   [11:0] tmp_85_cast_reg_720;
wire    ap_CS_fsm_state6;
wire   [0:0] tmp_i_fu_490_p2;
reg   [0:0] tmp_i_reg_731;
wire   [0:0] tmp_1_i_fu_495_p2;
reg   [0:0] tmp_1_i_reg_737;
wire   [4:0] tmp_24_cast_fu_571_p1;
reg   [4:0] tmp_24_cast_reg_747;
wire    ap_CS_fsm_state7;
wire   [2:0] c_cast_fu_579_p1;
reg   [2:0] c_cast_reg_752;
wire    ap_CS_fsm_state8;
wire   [1:0] c_1_fu_589_p2;
reg   [1:0] c_1_reg_760;
wire   [0:0] exitcond_fu_583_p2;
reg   [3:0] gy_reg_220;
reg   [3:0] gx_reg_231;
reg   [1:0] b_reg_242;
reg   [1:0] c_reg_254;
wire    ap_CS_fsm_state9;
wire   [63:0] tmp_53_fu_363_p1;
wire   [63:0] tmp_62_fu_381_p1;
wire   [63:0] tmp_36_fu_403_p2;
wire   [63:0] tmp_59_fu_422_p1;
wire   [63:0] tmp_60_fu_439_p1;
wire   [63:0] tmp_86_cast_fu_457_p1;
wire   [63:0] tmp_87_cast_fu_468_p1;
wire   [63:0] tmp_61_fu_485_p1;
wire   [63:0] tmp_3_i_fu_505_p1;
wire   [63:0] tmp_88_cast_fu_515_p1;
wire   [63:0] tmp_89_cast_fu_525_p1;
wire   [63:0] tmp_94_cast_fu_609_p1;
wire   [63:0] tmp_64_fu_619_p3;
wire   [31:0] p_0_i_cast_fu_561_p1;
wire   [6:0] tmp_fu_277_p3;
wire   [7:0] tmp_cast_fu_301_p1;
wire   [8:0] tmp_31_fu_318_p3;
wire   [0:0] tmp_32_fu_342_p1;
wire   [11:0] tmp_33_fu_354_p4;
wire   [3:0] tmp_21_fu_368_p2;
wire   [11:0] tmp_40_fu_374_p3;
wire   [63:0] tmp_14_fu_386_p1;
wire   [63:0] tmp_54_fu_390_p2;
wire   [3:0] tmp_15_fu_410_p2;
wire   [11:0] tmp_37_fu_415_p3;
wire   [3:0] tmp_17_fu_427_p2;
wire   [11:0] tmp_38_fu_432_p3;
wire   [11:0] tmp_55_fu_451_p2;
wire   [11:0] tmp_56_fu_462_p2;
wire   [3:0] tmp_19_fu_473_p2;
wire   [11:0] tmp_39_fu_478_p3;
wire   [31:0] tmp_2_i_fu_500_p2;
wire   [11:0] tmp_57_fu_510_p2;
wire   [11:0] tmp_58_fu_520_p2;
wire   [0:0] sel_tmp1_fu_530_p2;
wire   [0:0] sel_tmp2_fu_535_p2;
wire   [0:0] tmp_1_fu_548_p2;
wire   [9:0] sel_tmp_cast_fu_540_p3;
wire   [9:0] p_0_i_fu_553_p3;
wire   [3:0] tmp_24_fu_566_p2;
wire   [4:0] c_cast4_fu_575_p1;
wire   [4:0] tmp_25_fu_595_p2;
wire   [11:0] tmp_26_cast_fu_600_p1;
wire   [11:0] tmp_63_fu_604_p2;
wire   [2:0] tmp_27_fu_614_p2;
reg   [8:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_CS_fsm = 9'd1;
end

decode_sigmoid_lut #(
    .DataWidth( 10 ),
    .AddressRange( 17 ),
    .AddressWidth( 5 ))
sigmoid_lut_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(sigmoid_lut_address0),
    .ce0(sigmoid_lut_ce0),
    .q0(sigmoid_lut_q0)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state8) & (exitcond_fu_583_p2 == 1'd1))) begin
        b_reg_242 <= b_1_reg_670;
    end else if (((exitcond2_fu_289_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        b_reg_242 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        c_reg_254 <= c_1_reg_760;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        c_reg_254 <= 2'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_330_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
        gx_reg_231 <= gx_1_reg_643;
    end else if (((exitcond3_fu_265_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        gx_reg_231 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_289_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
        gy_reg_220 <= gy_1_reg_630;
    end else if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        gy_reg_220 <= 4'd0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        b_1_reg_670 <= b_1_fu_336_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_det_load_4_reg_713 <= buf_det_q1;
        tmp_34_reg_693 <= tmp_34_fu_395_p1;
        tmp_35_reg_698 <= tmp_35_fu_399_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        c_1_reg_760 <= c_1_fu_589_p2;
        c_cast_reg_752[1 : 0] <= c_cast_fu_579_p1[1 : 0];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        gx_1_reg_643 <= gx_1_fu_295_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        gy_1_reg_630 <= gy_1_fu_271_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond1_fu_330_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state4))) begin
        offset_reg_675[3] <= offset_fu_346_p3[3];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        tmp_1_i_reg_737 <= tmp_1_i_fu_495_p2;
        tmp_85_cast_reg_720[11 : 3] <= tmp_85_cast_fu_444_p3[11 : 3];
        tmp_i_reg_731 <= tmp_i_fu_490_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        tmp_24_cast_reg_747[3] <= tmp_24_cast_fu_571_p1[3];
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond2_fu_289_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        tmp_52_reg_662[8 : 1] <= tmp_52_fu_326_p1[8 : 1];
        tmp_78_cast_reg_657[11 : 4] <= tmp_78_cast_fu_310_p3[11 : 4];
        tmp_s_reg_648 <= tmp_s_fu_305_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((exitcond3_fu_265_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        tmp_75_cast_reg_635[6 : 3] <= tmp_75_cast_fu_285_p1[6 : 3];
    end
end

always @ (*) begin
    if ((((exitcond3_fu_265_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((exitcond3_fu_265_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        buf_det_address0 = tmp_61_fu_485_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_det_address0 = tmp_59_fu_422_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_det_address0 = tmp_53_fu_363_p1;
    end else begin
        buf_det_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state8)) begin
        buf_det_address1 = tmp_94_cast_fu_609_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        buf_det_address1 = tmp_60_fu_439_p1;
    end else if ((1'b1 == ap_CS_fsm_state4)) begin
        buf_det_address1 = tmp_62_fu_381_p1;
    end else begin
        buf_det_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        buf_det_ce0 = 1'b1;
    end else begin
        buf_det_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state4) | (1'b1 == ap_CS_fsm_state8) | (1'b1 == ap_CS_fsm_state5))) begin
        buf_det_ce1 = 1'b1;
    end else begin
        buf_det_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        output_r_address0 = tmp_89_cast_fu_525_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_r_address0 = tmp_86_cast_fu_457_p1;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        output_r_address0 = tmp_36_fu_403_p2;
    end else begin
        output_r_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state9)) begin
        output_r_address1 = tmp_64_fu_619_p3;
    end else if ((1'b1 == ap_CS_fsm_state7)) begin
        output_r_address1 = tmp_88_cast_fu_515_p1;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        output_r_address1 = tmp_87_cast_fu_468_p1;
    end else begin
        output_r_address1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        output_r_ce0 = 1'b1;
    end else begin
        output_r_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        output_r_ce1 = 1'b1;
    end else begin
        output_r_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        output_r_d0 = p_0_i_cast_fu_561_p1;
    end else if (((1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        output_r_d0 = buf_det_q0;
    end else begin
        output_r_d0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        output_r_d1 = buf_det_q0;
    end else if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state6))) begin
        output_r_d1 = buf_det_q1;
    end else begin
        output_r_d1 = 'bx;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6) | (1'b1 == ap_CS_fsm_state5))) begin
        output_r_we0 = 1'b1;
    end else begin
        output_r_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state9) | (1'b1 == ap_CS_fsm_state7) | (1'b1 == ap_CS_fsm_state6))) begin
        output_r_we1 = 1'b1;
    end else begin
        output_r_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        sigmoid_lut_ce0 = 1'b1;
    end else begin
        sigmoid_lut_ce0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((exitcond3_fu_265_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((exitcond2_fu_289_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            if (((exitcond1_fu_330_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state7;
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (exitcond_fu_583_p2 == 1'd1))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end
        end
        ap_ST_fsm_state9 : begin
            ap_NS_fsm = ap_ST_fsm_state8;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

assign b_1_fu_336_p2 = (b_reg_242 + 2'd1);

assign c_1_fu_589_p2 = (c_reg_254 + 2'd1);

assign c_cast4_fu_575_p1 = c_reg_254;

assign c_cast_fu_579_p1 = c_reg_254;

assign exitcond1_fu_330_p2 = ((b_reg_242 == 2'd2) ? 1'b1 : 1'b0);

assign exitcond2_fu_289_p2 = ((gx_reg_231 == 4'd8) ? 1'b1 : 1'b0);

assign exitcond3_fu_265_p2 = ((gy_reg_220 == 4'd8) ? 1'b1 : 1'b0);

assign exitcond_fu_583_p2 = ((c_reg_254 == 2'd3) ? 1'b1 : 1'b0);

assign gx_1_fu_295_p2 = (gx_reg_231 + 4'd1);

assign gy_1_fu_271_p2 = (gy_reg_220 + 4'd1);

assign offset_fu_346_p3 = {{tmp_32_fu_342_p1}, {3'd0}};

assign p_0_i_cast_fu_561_p1 = p_0_i_fu_553_p3;

assign p_0_i_fu_553_p3 = ((tmp_1_fu_548_p2[0:0] === 1'b1) ? sel_tmp_cast_fu_540_p3 : sigmoid_lut_q0);

assign sel_tmp1_fu_530_p2 = (tmp_i_reg_731 ^ 1'd1);

assign sel_tmp2_fu_535_p2 = (tmp_1_i_reg_737 & sel_tmp1_fu_530_p2);

assign sel_tmp_cast_fu_540_p3 = ((sel_tmp2_fu_535_p2[0:0] === 1'b1) ? 10'd1000 : 10'd0);

assign sigmoid_lut_address0 = tmp_3_i_fu_505_p1;

assign tmp_14_fu_386_p1 = b_reg_242;

assign tmp_15_fu_410_p2 = (offset_reg_675 | 4'd1);

assign tmp_17_fu_427_p2 = (offset_reg_675 | 4'd2);

assign tmp_19_fu_473_p2 = (offset_reg_675 | 4'd3);

assign tmp_1_fu_548_p2 = (tmp_i_reg_731 | sel_tmp2_fu_535_p2);

assign tmp_1_i_fu_495_p2 = (($signed(buf_det_load_4_reg_713) > $signed(32'd8)) ? 1'b1 : 1'b0);

assign tmp_21_fu_368_p2 = (offset_fu_346_p3 | 4'd4);

assign tmp_24_cast_fu_571_p1 = tmp_24_fu_566_p2;

assign tmp_24_fu_566_p2 = (offset_reg_675 | 4'd5);

assign tmp_25_fu_595_p2 = (tmp_24_cast_reg_747 + c_cast4_fu_575_p1);

assign tmp_26_cast_fu_600_p1 = tmp_25_fu_595_p2;

assign tmp_27_fu_614_p2 = ($signed(c_cast_reg_752) + $signed(3'd5));

assign tmp_2_i_fu_500_p2 = (32'd8 + buf_det_load_4_reg_713);

assign tmp_31_fu_318_p3 = {{tmp_s_fu_305_p2}, {1'd0}};

assign tmp_32_fu_342_p1 = b_reg_242[0:0];

assign tmp_33_fu_354_p4 = {{{tmp_s_reg_648}, {tmp_32_fu_342_p1}}, {3'd0}};

assign tmp_34_fu_395_p1 = tmp_54_fu_390_p2[60:0];

assign tmp_35_fu_399_p1 = tmp_54_fu_390_p2[8:0];

assign tmp_36_fu_403_p2 = tmp_54_fu_390_p2 << 64'd3;

assign tmp_37_fu_415_p3 = {{tmp_s_reg_648}, {tmp_15_fu_410_p2}};

assign tmp_38_fu_432_p3 = {{tmp_s_reg_648}, {tmp_17_fu_427_p2}};

assign tmp_39_fu_478_p3 = {{tmp_s_reg_648}, {tmp_19_fu_473_p2}};

assign tmp_3_i_fu_505_p1 = tmp_2_i_fu_500_p2;

assign tmp_40_fu_374_p3 = {{tmp_s_reg_648}, {tmp_21_fu_368_p2}};

assign tmp_52_fu_326_p1 = tmp_31_fu_318_p3;

assign tmp_53_fu_363_p1 = tmp_33_fu_354_p4;

assign tmp_54_fu_390_p2 = (tmp_52_reg_662 + tmp_14_fu_386_p1);

assign tmp_55_fu_451_p2 = (tmp_85_cast_fu_444_p3 | 12'd1);

assign tmp_56_fu_462_p2 = (tmp_85_cast_fu_444_p3 | 12'd2);

assign tmp_57_fu_510_p2 = (tmp_85_cast_reg_720 | 12'd3);

assign tmp_58_fu_520_p2 = (tmp_85_cast_reg_720 | 12'd4);

assign tmp_59_fu_422_p1 = tmp_37_fu_415_p3;

assign tmp_60_fu_439_p1 = tmp_38_fu_432_p3;

assign tmp_61_fu_485_p1 = tmp_39_fu_478_p3;

assign tmp_62_fu_381_p1 = tmp_40_fu_374_p3;

assign tmp_63_fu_604_p2 = (tmp_26_cast_fu_600_p1 + tmp_78_cast_reg_657);

assign tmp_64_fu_619_p3 = {{tmp_34_reg_693}, {tmp_27_fu_614_p2}};

assign tmp_75_cast_fu_285_p1 = tmp_fu_277_p3;

assign tmp_78_cast_fu_310_p3 = {{tmp_s_fu_305_p2}, {4'd0}};

assign tmp_85_cast_fu_444_p3 = {{tmp_35_reg_698}, {3'd0}};

assign tmp_86_cast_fu_457_p1 = tmp_55_fu_451_p2;

assign tmp_87_cast_fu_468_p1 = tmp_56_fu_462_p2;

assign tmp_88_cast_fu_515_p1 = tmp_57_fu_510_p2;

assign tmp_89_cast_fu_525_p1 = tmp_58_fu_520_p2;

assign tmp_94_cast_fu_609_p1 = tmp_63_fu_604_p2;

assign tmp_cast_fu_301_p1 = gx_reg_231;

assign tmp_fu_277_p3 = {{gy_reg_220}, {3'd0}};

assign tmp_i_fu_490_p2 = (($signed(buf_det_load_4_reg_713) < $signed(32'd4294967288)) ? 1'b1 : 1'b0);

assign tmp_s_fu_305_p2 = (tmp_cast_fu_301_p1 + tmp_75_cast_reg_635);

always @ (posedge ap_clk) begin
    tmp_75_cast_reg_635[2:0] <= 3'b000;
    tmp_75_cast_reg_635[7] <= 1'b0;
    tmp_78_cast_reg_657[3:0] <= 4'b0000;
    tmp_52_reg_662[0] <= 1'b0;
    tmp_52_reg_662[63:9] <= 55'b0000000000000000000000000000000000000000000000000000000;
    offset_reg_675[2:0] <= 3'b000;
    tmp_85_cast_reg_720[2:0] <= 3'b000;
    tmp_24_cast_reg_747[2:0] <= 3'b101;
    tmp_24_cast_reg_747[4] <= 1'b0;
    c_cast_reg_752[2] <= 1'b0;
end

endmodule //decode
